import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://xohftjaohhkwgxdnouoo.supabase.co';
const supabaseServiceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvaGZ0amFvaGhrd2d4ZG5vdW9vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDg2NzU5MywiZXhwIjoyMDkwNDQzNTkzfQ.65YGsr1ZbSgECaM0nUZ8-sJR7lezQPd7xWxwTDirZD4';

const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
});

async function main() {
  console.log('Seeding Supabase DB...');
  
  // 1. Seed Products
  const productsToSeed = [
    // ELITE / XH4 SERIES
    {
      slug: 'alkota-430xh',
      name: 'Alkota 430XH',
      series: 'XH4 Series',
      category: 'hot-water',
      tagline: 'Elite portable electric hot water — the benchmark.',
      description: 'The 430XH is the pinnacle of portable electric hot water pressure washing. Belt-driven triplex pump runs at lower RPM for a cooler, quieter, longer-lasting operation. Industry-leading hydro-insulated Schedule 80 coil with Soft Damping System. Comes standard with industrial hose, insulated trigger gun with safety lock, insulated wand, and quick-connect nozzles. Backed by Alkota\'s 7-year coil warranty — the best in the industry by far.',
      featured: true,
      active: true,
      flow_rate_gpm: 3.9,
      flow_rate_lpm: 14.8,
      pressure_psi: 3000,
      pressure_bar: 207,
      power_source: 'Electric 230V',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: '230V 1-Phase',
      portable: true,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['oil-gas', 'fleet-transport', 'food-processing', 'construction', 'manufacturing', 'agriculture'],
      sort_order: 10
    },
    {
      slug: 'alkota-420xh',
      name: 'Alkota 420XH',
      series: 'XH4 Series',
      category: 'hot-water',
      tagline: 'Standard industrial power in a proven portable frame.',
      description: 'The workhorse of the XH4 range. Belt-driven, oil-fired, delivering reliable 2000 PSI hot water cleaning across the most demanding industrial environments. The same 7-year coil warranty and Soft Damping System as its bigger sibling. Quiet, low-vibration operation. Four-wheel design rolls over any surface.',
      featured: true,
      active: true,
      flow_rate_gpm: 3.5,
      flow_rate_lpm: 13.2,
      pressure_psi: 2000,
      pressure_bar: 138,
      power_source: 'Electric 230V',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: '230V 1-Phase',
      portable: true,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['fleet-transport', 'construction', 'agriculture', 'waste-management', 'plant-hire'],
      sort_order: 20
    },
    {
      slug: 'alkota-330xh4',
      name: 'Alkota 330XH4',
      series: 'XH4 Series',
      category: 'hot-water',
      tagline: 'Compact high-pressure electric — maximum PSI, minimal footprint.',
      description: 'Where space is tight but performance cannot be compromised. The 330XH4 delivers a full 3000 PSI from a compact belt-driven electric frame. Same coil and pump engineering as the larger XH4 units. Ideal for workshops, plant rooms, and operations where portability is critical.',
      featured: false,
      active: true,
      flow_rate_gpm: 3.0,
      flow_rate_lpm: 11.4,
      pressure_psi: 3000,
      pressure_bar: 207,
      power_source: 'Electric 230V',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: '230V 1-Phase',
      portable: true,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['manufacturing', 'automotive', 'food-processing', 'marine'],
      sort_order: 30
    },
    // AX4 SERIES
    {
      slug: 'alkota-420ax4',
      name: 'Alkota 420AX4',
      series: 'AX4 Series',
      category: 'hot-water',
      tagline: 'Compact industrial power — the entry point to Alkota hot water.',
      description: 'The AX4 series brings genuine Alkota engineering to a compact, lightweight frame. Belt-driven pump, oil-fired heating, available in 115V or 230V to suit any power supply. Four-wheel portable. Perfect first machine for trades, small fleet operations, and agricultural businesses stepping up from consumer-grade kit.',
      featured: false,
      active: true,
      flow_rate_gpm: 3.5,
      flow_rate_lpm: 13.2,
      pressure_psi: 2000,
      pressure_bar: 138,
      power_source: 'Electric 115V / 230V',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: '115V or 230V',
      portable: true,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['agriculture', 'automotive', 'plant-hire', 'manufacturing'],
      sort_order: 40
    },
    {
      slug: 'alkota-216ax4',
      name: 'Alkota 216AX4',
      series: 'AX4 Series',
      category: 'hot-water',
      tagline: 'The compact 115V entry point to industrial hot water cleaning.',
      description: 'The most compact machine in the Alkota hot water range, running on a standard 115V supply. Oil-fired heat, belt-driven pump, fully portable. Ideal for workshops, garages, and small-scale industrial cleaning where a full-size machine would be overkill.',
      featured: false,
      active: true,
      flow_rate_gpm: 2.0,
      flow_rate_lpm: 7.6,
      pressure_psi: 1600,
      pressure_bar: 110,
      power_source: 'Electric 115V',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: '115V',
      portable: true,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['automotive', 'manufacturing', 'agriculture'],
      sort_order: 50
    },
    // X4 SERIES
    {
      slug: 'alkota-420x4',
      name: 'Alkota 420X4',
      series: 'X4 Series',
      category: 'hot-water',
      tagline: 'The industry workhorse. Decades of proven performance.',
      description: 'The X4 belt drive series has been the backbone of industrial hot water cleaning for decades. Heavy-gauge welded steel frame, belt-driven triplex pump, oil-fired heating. Available across a wide GPM and PSI range to match any application. When reliability is non-negotiable, this is the machine.',
      featured: true,
      active: true,
      flow_rate_gpm: 3.5,
      flow_rate_lpm: 13.2,
      pressure_psi: 2000,
      pressure_bar: 138,
      power_source: 'Electric 230V',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: '230V',
      portable: true,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['oil-gas', 'fleet-transport', 'construction', 'agriculture', 'waste-management', 'local-authorities'],
      sort_order: 60
    },
    // EN/HN SERIES
    {
      slug: 'alkota-5355hnl',
      name: 'Alkota 5355HNL',
      series: 'EN/HN Series',
      category: 'hot-water',
      tagline: 'Extreme-volume hot water for the heaviest industrial duty.',
      description: 'When the job demands serious volume, the HNL series delivers. Narrow-frame design allows deployment in tight spaces without sacrificing output. Diesel or gas engine driven — fully independent of mains power. Ideal for remote site operations, oil field maintenance, and heavy plant cleaning.',
      featured: true,
      active: true,
      flow_rate_gpm: 5.0,
      flow_rate_lpm: 18.9,
      pressure_psi: 3500,
      pressure_bar: 241,
      power_source: 'Gas / Diesel Engine',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: 'Engine Driven',
      portable: true,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['oil-gas', 'construction', 'plant-hire', 'mining', 'waste-management'],
      sort_order: 70
    },
    {
      slug: 'alkota-8405hnl',
      name: 'Alkota 8405HNL',
      series: 'EN/HN Series',
      category: 'hot-water',
      tagline: 'Maximum flow, maximum force — for the jobs nothing else can touch.',
      description: 'The most powerful portable hot water machine in the Alkota fleet. 8 GPM at 4000 PSI — the kind of output that strips years of industrial contamination in minutes. Engine-driven and fully self-contained. Designed for oil & gas, heavy construction, and any environment where performance is the only metric that matters.',
      featured: true,
      active: true,
      flow_rate_gpm: 8.0,
      flow_rate_lpm: 30.3,
      pressure_psi: 4000,
      pressure_bar: 276,
      power_source: 'Gas / Diesel Engine',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: 'Engine Driven',
      portable: true,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['oil-gas', 'mining', 'construction', 'waste-management', 'plant-hire'],
      sort_order: 80
    },
    {
      slug: 'alkota-7407dnl',
      name: 'Alkota 7407DNL',
      series: 'EN/HN Series',
      category: 'hot-water',
      tagline: 'Diesel-powered high-capacity hot water for remote and off-grid operations.',
      description: 'All-diesel operation — no mains power required anywhere. The 7407DNL brings 7 GPM at 4000 PSI to the most remote sites on the planet. Built on the same narrow-frame architecture as the HNL series for access where larger rigs can\'t go.',
      featured: false,
      active: true,
      flow_rate_gpm: 7.0,
      flow_rate_lpm: 26.5,
      pressure_psi: 4000,
      pressure_bar: 276,
      power_source: 'Diesel Engine',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: 'Engine Driven',
      portable: true,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['oil-gas', 'mining', 'construction', 'agriculture'],
      sort_order: 90
    },
    // XD4 SERIES
    {
      slug: 'alkota-4405xd4',
      name: 'Alkota 4405XD4',
      series: 'XD4 Series',
      category: 'hot-water',
      tagline: 'Flagship Honda-powered performance — mobile, unstoppable.',
      description: 'Honda GX engine. Direct drive. 4000 PSI. The XD4 is built for operators who need serious hot water performance with zero dependency on electrical infrastructure. Fully portable, oil-fired heat, and Honda\'s legendary engine reliability. The choice for mobile contract cleaners, oil field operators, and anyone working far from a plug socket.',
      featured: true,
      active: true,
      flow_rate_gpm: 4.0,
      flow_rate_lpm: 15.1,
      pressure_psi: 4000,
      pressure_bar: 276,
      power_source: 'Honda GX Engine',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: 'Engine Driven',
      portable: true,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['oil-gas', 'construction', 'fleet-transport', 'agriculture', 'plant-hire'],
      sort_order: 100
    },
    // GED 12V SKID
    {
      slug: 'alkota-4405f',
      name: 'Alkota 4405F',
      series: 'GED 12V Skid Series',
      category: 'hot-water',
      tagline: 'Versatile gasoline skid unit — trailer and vehicle mount ready.',
      description: 'Skid-mount design built for integration into trailer rigs, flatbeds, and service vehicles. Gasoline engine, 12V ignition system, oil-fired heat. 4000 PSI output. Pairs perfectly with Alkota\'s bespoke trailer programme — specify this unit as the heart of a custom mobile wash rig.',
      featured: false,
      active: true,
      flow_rate_gpm: 4.0,
      flow_rate_lpm: 15.1,
      pressure_psi: 4000,
      pressure_bar: 276,
      power_source: 'Gasoline Engine',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: '12V Engine Driven',
      portable: false,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['fleet-transport', 'oil-gas', 'construction', 'plant-hire'],
      sort_order: 110
    },
    // DED SERIES
    {
      slug: 'alkota-10307kk',
      name: 'Alkota 10307KK',
      series: 'DED Series',
      category: 'hot-water',
      tagline: 'The heavy-duty diesel workhorse — 10 GPM, no compromise.',
      description: 'The biggest, most capable machine in the Alkota portable hot water range. Diesel engine driven with 10 GPM flow and 3000 PSI — designed for operations that run all day, every day. Used in the most demanding environments on earth: mining, offshore support, heavy plant, and large-scale fleet operations. Self-contained diesel power means it goes anywhere.',
      featured: true,
      active: true,
      flow_rate_gpm: 10.0,
      flow_rate_lpm: 37.9,
      pressure_psi: 3000,
      pressure_bar: 207,
      power_source: 'Diesel Engine',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: 'Engine Driven',
      portable: false,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['oil-gas', 'mining', 'construction', 'waste-management', 'plant-hire'],
      sort_order: 120
    },
    // GAS FIRED STATIONARY
    {
      slug: 'alkota-gas-fired-stationary',
      name: 'Alkota Gas Fired Stationary Series',
      series: 'Gas Fired Series',
      category: 'hot-water',
      tagline: 'High-output stationary hot water — gas-fired for permanent installations.',
      description: 'The Gas Fired Series is designed for permanent or semi-permanent installation where mains gas (LP or natural gas) is available. Output ranges from 2.1 GPM up to 10 GPM at pressures up to 5000 PSI — the highest PSI in the Alkota range. Ideal for vehicle wash bays, wash pads, abattoirs, food processing facilities, and any fixed industrial wash station needing maximum performance.',
      featured: false,
      active: true,
      flow_rate_gpm: 5.0,
      flow_rate_lpm: 18.9,
      pressure_psi: 5000,
      pressure_bar: 345,
      power_source: 'Electric Motor',
      heating_fuel: 'Gas (LP or Natural Gas)',
      voltage: '230V / 415V 3-Phase',
      portable: false,
      warranty_years: 7,
      certifications: ['CE', 'UKCA'],
      industries: ['food-processing', 'agriculture', 'fleet-transport', 'manufacturing', 'local-authorities'],
      sort_order: 130
    },
    // COLD WATER MACHINES
    {
      slug: 'alkota-530bd',
      name: 'Alkota 530BD',
      series: 'BD Industrial Series',
      category: 'cold-water',
      tagline: 'Industrial cabinet cold water — portable or stationary, built to last.',
      description: 'The BD Industrial series is the benchmark for cold water pressure washing in UK industry. Cabinet-style enclosed frame protects all components from the elements. Belt-driven pump runs quieter and cooler than direct drive. Available from 2 to 5 GPM at pressures up to 3000 PSI. 115V or 230V power options. Portable or stationary configurations.',
      featured: true,
      active: true,
      flow_rate_gpm: 4.0,
      flow_rate_lpm: 15.1,
      pressure_psi: 3000,
      pressure_bar: 207,
      power_source: 'Electric 115V / 230V',
      heating_fuel: 'N/A — Cold Water',
      voltage: '115V or 230V',
      portable: true,
      warranty_years: 5,
      certifications: ['CE', 'UKCA'],
      industries: ['manufacturing', 'agriculture', 'fleet-transport', 'construction', 'automotive'],
      sort_order: 200
    },
    {
      slug: 'alkota-s-sh-electric',
      name: 'Alkota S & SH Electric Series',
      series: 'S & SH Series',
      category: 'cold-water',
      tagline: 'High-pressure electric cold water — up to 5000 PSI.',
      description: 'The S and SH series covers the widest pressure range in cold water cleaning, from 3 GPM right up to 8 GPM and 5000 PSI. S-frame heavy-gauge steel construction. 230V electric — direct drive for maximum pressure output. The SH variant adds hot water capability for crossover applications. The choice when maximum PSI is the priority.',
      featured: true,
      active: true,
      flow_rate_gpm: 5.0,
      flow_rate_lpm: 18.9,
      pressure_psi: 5000,
      pressure_bar: 345,
      power_source: 'Electric 230V',
      heating_fuel: 'N/A — Cold Water',
      voltage: '230V',
      portable: true,
      warranty_years: 5,
      certifications: ['CE', 'UKCA'],
      industries: ['oil-gas', 'mining', 'construction', 'manufacturing'],
      sort_order: 210
    },
    {
      slug: 'alkota-sg-sm-gas-diesel',
      name: 'Alkota SG / SM Gas & Diesel Series',
      series: 'SG/SM Series',
      category: 'cold-water',
      tagline: 'Gas and diesel cold water — full independence from the mains.',
      description: 'When the site has no power supply, the SG (gas) and SM (gasoline) series step in. Ranging from 3.4 to 8.5 GPM at pressures up to an extraordinary 8500 PSI — among the highest cold water outputs available anywhere. Engine-driven skid or portable configurations. The definitive choice for remote industrial and civil engineering sites.',
      featured: false,
      active: true,
      flow_rate_gpm: 5.0,
      flow_rate_lpm: 18.9,
      pressure_psi: 8500,
      pressure_bar: 586,
      power_source: 'Gas / Diesel Engine',
      heating_fuel: 'N/A — Cold Water',
      voltage: 'Engine Driven',
      portable: true,
      warranty_years: 5,
      certifications: ['CE', 'UKCA'],
      industries: ['construction', 'oil-gas', 'mining', 'plant-hire', 'agriculture'],
      sort_order: 220
    },
    {
      slug: 'alkota-challenger',
      name: 'Alkota Challenger Series',
      series: 'Challenger Series',
      category: 'cold-water',
      tagline: 'Aluminium frame cold water — lightweight, durable, versatile.',
      description: 'The Challenger series brings aluminium frame construction to cold water pressure washing — significantly lighter than steel frame alternatives without sacrificing durability. Available in electric (115V or 220V) and gas engine versions from 2 to 4 GPM at up to 4000 PSI. Ideal where portability and weight are key considerations.',
      featured: false,
      active: true,
      flow_rate_gpm: 3.0,
      flow_rate_lpm: 11.4,
      pressure_psi: 4000,
      pressure_bar: 276,
      power_source: 'Electric 115V / 230V or Gas Engine',
      heating_fuel: 'N/A — Cold Water',
      voltage: '115V / 230V or Engine',
      portable: true,
      warranty_years: 5,
      certifications: ['CE', 'UKCA'],
      industries: ['agriculture', 'automotive', 'construction', 'plant-hire'],
      sort_order: 230
    },
    {
      slug: 'alkota-hhs-farm',
      name: 'Alkota HHS Farm Series',
      series: 'HHS Series',
      category: 'cold-water',
      tagline: 'Purpose-built cold water for livestock and agricultural cleaning.',
      description: 'The HHS series was engineered specifically for the demands of livestock and agricultural cleaning — hog barns, poultry units, cattle sheds, dairy washdowns. High flow rates from 3.5 to 9.2 GPM at pressures up to 4000 PSI. 230V electric. Built to survive the corrosive, high-humidity environments that destroy lesser machines.',
      featured: true,
      active: true,
      flow_rate_gpm: 6.0,
      flow_rate_lpm: 22.7,
      pressure_psi: 4000,
      pressure_bar: 276,
      power_source: 'Electric 230V',
      heating_fuel: 'N/A — Cold Water',
      voltage: '230V',
      portable: true,
      warranty_years: 5,
      certifications: ['CE', 'UKCA'],
      industries: ['agriculture'],
      sort_order: 240
    },
    {
      slug: 'alkota-jetter',
      name: 'Alkota Jetter Series',
      series: 'Jetter Series',
      category: 'cold-water',
      tagline: 'Electric and gas drain jetter — blast through blocked pipes and drains.',
      description: 'Designed specifically for drain, sewer, and pipe jetting applications. High pressure (up to 4000 PSI) combined with specialist jetting lances and nozzles cuts through blockages, root intrusion, and decades of built-up scale. Electric (115V) and gasoline engine variants. 2 to 8 GPM flow range. The choice for drainage contractors, local authorities, and utilities.',
      featured: false,
      active: true,
      flow_rate_gpm: 4.0,
      flow_rate_lpm: 15.1,
      pressure_psi: 4000,
      pressure_bar: 276,
      power_source: 'Electric 115V or Gas Engine',
      heating_fuel: 'N/A — Cold Water',
      voltage: '115V or Engine',
      portable: true,
      warranty_years: 5,
      certifications: ['CE', 'UKCA'],
      industries: ['local-authorities', 'construction', 'waste-management', 'manufacturing'],
      sort_order: 250
    },
    {
      slug: 'alkota-wash-cannon-2110',
      name: 'Alkota Wash Cannon 2110',
      series: 'Wash Cannon Series',
      category: 'cold-water',
      tagline: 'High-volume cold water cannon — 21-25 GPM for rapid bulk cleaning.',
      description: 'When speed matters more than pressure. The Wash Cannon delivers 21-25 GPM at up to 1000 PSI — extraordinary volume for rapid flushing of large areas, livestock housing, vehicle yards, and construction sites. Gas or electric. Clears a yard in minutes rather than hours.',
      featured: false,
      active: true,
      flow_rate_gpm: 23.0,
      flow_rate_lpm: 87.1,
      pressure_psi: 1000,
      pressure_bar: 69,
      power_source: 'Gas Engine or Electric',
      heating_fuel: 'N/A — Cold Water',
      voltage: 'Engine or Electric',
      portable: true,
      warranty_years: 5,
      certifications: ['CE', 'UKCA'],
      industries: ['agriculture', 'construction', 'waste-management', 'local-authorities'],
      sort_order: 260
    },
    {
      slug: 'alkota-219cse',
      name: 'Alkota 219CSE',
      series: '219CSE',
      category: 'cold-water',
      tagline: 'Compact electric cold water — portable, powerful, plug-and-go.',
      description: 'The most portable machine in the Alkota range. 115V plug-in, lightweight, genuine Alkota build quality in a compact form factor. 2000 PSI — far beyond any consumer-grade machine. The ideal first Alkota for tradespeople, small businesses, and anyone needing professional-grade results from the most portable possible unit.',
      featured: false,
      active: true,
      flow_rate_gpm: 1.7,
      flow_rate_lpm: 6.4,
      pressure_psi: 2000,
      pressure_bar: 138,
      power_source: 'Electric 115V',
      heating_fuel: 'N/A — Cold Water',
      voltage: '115V',
      portable: true,
      warranty_years: 5,
      certifications: ['CE', 'UKCA'],
      industries: ['automotive', 'agriculture', 'manufacturing'],
      sort_order: 270
    },
    // STEAM CLEANERS
    {
      slug: 'alkota-steam-111',
      name: 'Alkota Model 111',
      series: 'Steam Series',
      category: 'steam',
      tagline: 'High-pressure steam cleaning — sanitise without chemicals.',
      description: 'Steam cleaning delivers a level of sanitisation that pressure washing alone cannot match. Alkota\'s oil-fired steam cleaners produce high-pressure steam for instant emulsification of grease, oil, and biological contamination. No chemicals required for many applications — the heat alone does the work. Widely used in food production, agriculture, and anywhere chemical-free sanitisation is required.',
      featured: false,
      active: true,
      flow_rate_gpm: 0,
      flow_rate_lpm: 0,
      pressure_psi: 0,
      pressure_bar: 0,
      power_source: 'Electric Motor',
      heating_fuel: 'Oil (Diesel / Kerosene)',
      voltage: '230V',
      portable: true,
      warranty_years: 5,
      certifications: ['CE', 'UKCA'],
      industries: ['food-processing', 'agriculture', 'manufacturing', 'automotive'],
      sort_order: 300
    },
    // PARTS WASHERS
    {
      slug: 'alkota-parts-washer-compact',
      name: 'Alkota Compact Top-Load Parts Washer',
      series: 'Parts Washer Series',
      category: 'parts-washer',
      tagline: 'Aqueous parts washing — grease-free in minutes, no solvents.',
      description: 'Industrial aqueous parts washers that use hot water and biodegradable detergent to remove grease and contamination from components — no hazardous solvents or aerosols. Turntable design: load parts, close lid, set timer. Compact top-load models for smaller components; larger cabinet models for heavy parts. The sustainable, COSHH-compliant alternative to solvent degreasing.',
      featured: false,
      active: true,
      flow_rate_gpm: 0,
      flow_rate_lpm: 0,
      pressure_psi: 0,
      pressure_bar: 0,
      power_source: 'Electric 230V',
      heating_fuel: 'N/A',
      voltage: '230V',
      portable: false,
      warranty_years: 3,
      certifications: ['CE', 'UKCA'],
      industries: ['manufacturing', 'automotive', 'agriculture', 'construction'],
      sort_order: 400
    },
    // WATER TREATMENT
    {
      slug: 'alkota-vfs-1',
      name: 'Alkota VFS-1 Vacuum Filtration System',
      series: 'Water Treatment',
      category: 'water-treatment',
      tagline: 'Portable closed-loop water recovery — Environment Agency compliant.',
      description: 'The VFS-1 (Vacuum Filtration System) is a portable wash water recovery and recycling unit that allows fully compliant pressure washing in areas subject to Environment Agency wash water discharge regulations. Recovers wash water from up to 100 metres away, filters to remove 99% of free petroleum hydrocarbons, and recycles clean water back to the pressure washer. Prevents contaminated runoff from reaching surface drains, watercourses, and soakaways.',
      featured: false,
      active: true,
      flow_rate_gpm: 0,
      flow_rate_lpm: 0,
      pressure_psi: 0,
      pressure_bar: 0,
      power_source: 'Electric',
      heating_fuel: 'N/A',
      voltage: '230V',
      portable: true,
      warranty_years: 3,
      certifications: ['CE', 'UKCA'],
      industries: ['oil-gas', 'fleet-transport', 'local-authorities', 'construction', 'mining'],
      sort_order: 500
    },
    {
      slug: 'alkota-csf-10',
      name: 'Alkota CSF-10 Media Sand Filtration',
      series: 'Water Treatment',
      category: 'water-treatment',
      tagline: 'Low-maintenance wash pad water recycling for permanent installations.',
      description: 'The CSF-10 is a cost-effective, ultra-low-maintenance closed-loop filtration system for wash pads and fixed wash bays. 10 GPM filtration capacity, 300 lb sand media bed, auto-backwash. Allows full compliance with local authority discharge conditions without the operational complexity of more advanced systems.',
      featured: false,
      active: true,
      flow_rate_gpm: 0,
      flow_rate_lpm: 0,
      pressure_psi: 0,
      pressure_bar: 0,
      power_source: 'Electric',
      heating_fuel: 'N/A',
      voltage: '230V',
      portable: false,
      warranty_years: 3,
      certifications: ['CE', 'UKCA'],
      industries: ['fleet-transport', 'local-authorities', 'food-processing', 'manufacturing'],
      sort_order: 510
    },
    {
      slug: 'alkota-evaporator',
      name: 'Alkota Evaporator Series',
      series: 'Water Treatment',
      category: 'water-treatment',
      tagline: 'Wastewater evaporation — eliminate disposal costs entirely.',
      description: 'For wash water that is too contaminated to filter and too expensive to pump away. The Alkota Evaporator burns off bulk wastewater cleanly and efficiently using LP or natural gas, evaporating up to 480 gallons per day. Massively reduces or eliminates liquid waste disposal costs. Quiet LP/NG combustion, built-in defoamer pump.',
      featured: false,
      active: true,
      flow_rate_gpm: 0,
      flow_rate_lpm: 0,
      pressure_psi: 0,
      pressure_bar: 0,
      power_source: 'LP / Natural Gas',
      heating_fuel: 'Gas (LP or NG)',
      voltage: 'Gas Fired',
      portable: false,
      warranty_years: 3,
      certifications: ['CE', 'UKCA'],
      industries: ['oil-gas', 'manufacturing', 'food-processing', 'waste-management'],
      sort_order: 520
    }
  ];

  const chemicalsToSeed = [
    {
      slug: 'farm-soap-tr440',
      name: 'Farm Soap TR-440',
      code: 'TR-440',
      category: 'industrial',
      tagline: 'Alkota\'s flagship agricultural & equipment detergent — removes oxidation and renews paint.',
      description: 'Farm Soap TR-440 is the undisputed benchmark for agricultural machinery, civil earthmoving equipment, and heavy transport. Formulated with a proprietary blend of alkaline builders, wetting surfactants, natural citrus solvency, and water-softening agents. TR-440 actively breaks down micro-oxidised surface paint layers on weathered equipment, restoring deep luster while emulsifying caked clay, manure grease, and hydraulic oil.',
      active: true,
      featured: true,
      uk_status: 'published',
      sort_order: 10,
      form: 'Concentrated Liquid',
      appearance: 'Clear Amber Liquid with Subtle Citrus Aroma',
      ph_level: '11.8 – 12.2',
      specific_gravity: '1.09 @ 20°C',
      active_ingredients: ['Alkaline Builders', 'Linear Alkyl Surfactants', 'd-Limonene Citrus Fraction', 'Scale Stop Chelating Agent'],
      voc_content: 'Low VOC (<15 g/L)',
      biodegradability_claim: 'Readily Biodegradable (OECD 301B)',
      biodegradable: true,
      hazardous: false,
      food_safe: false,
      use_cases: ['Tractors & Combines', 'Heavy Excavators', 'Agricultural Trailers', 'Grain Processing Plant'],
      compatible_surfaces: ['Painted Mild Steel', 'Powder-Coated Agricultural Panels', 'Cast Iron Frames', 'Heavy Galvanised Steel'],
      not_suitable_for: ['Polished Unlacquered Aluminium', 'Magnesium Alloy Components'],
      contamination_types: ['Heavy Agricultural Soil & Clay', 'Manure & Slurry Residues', 'Hydraulic Oil & Grease', 'Faded Oxidised Paint'],
      application_methods: ['Downstream Hot Injector', 'Low-Pressure Foam Cannon', 'Manual Brush Wash'],
      compatible_equipment_types: ['Hot Water Pressure Washers', 'Cold Water High-Volume Units', 'Trailer Rigs'],
      dilution_hot: '1:50 to 1:120',
      dilution_cold: '1:30 to 1:80',
      water_recovery_compatible: true,
      separator_compatible: true,
      recycling_compatible: true,
      available_sizes: ['5L', '25L', '200L Drum', '1000L IBC'],
      price_5l: 22.50,
      price_25l: 85.00,
      price_200l: 340.00,
      hazard_classification: 'Skin Irrit. 2; Eye Irrit. 2 (GB CLP / UK REACH)',
      signal_word: 'WARNING',
      hazard_statements: ['H315: Causes skin irritation', 'H319: Causes serious eye irritation'],
      precautionary_statements: ['P280: Wear protective gloves and eye protection'],
      sds_url: '/documents/sds/alkota-sds-tr440-farm-soap.pdf',
      sds_revision_date: '14 January 2024 (Rev 4.1)',
      tds_url: '/documents/tds/alkota-tds-tr440-farm-soap.pdf',
      tds_revision_date: '02 March 2024',
      primary_image_url: '/assets/products/tr440-farm-soap.png'
    },
    {
      slug: 'grease-cutter-de703',
      name: 'Grease Cutter DE-703',
      code: 'DE-703',
      category: 'degreasers',
      tagline: 'High-alkaline hydrocarbon dissolver for fifth wheels, engine blocks and industrial grease.',
      description: 'Grease Cutter DE-703 is a concentrated industrial degreaser engineered to attack heavy grease, crude oil residues, bitumen, and carbon deposits on contact. Formulated with synergistic solvent-boosted surfactants that penetrate dense hydrocarbon sludge, creating a chemical barrier that prevents soil redeposition during high-pressure washdown.',
      active: true,
      featured: true,
      uk_status: 'published',
      sort_order: 20,
      form: 'Concentrated Liquid',
      appearance: 'Clear Fluorescent Green Liquid',
      ph_level: '12.8 – 13.2',
      specific_gravity: '1.07 @ 20°C',
      active_ingredients: ['Potassium Hydroxide', 'Solvent-Coupled Surfactants'],
      voc_content: 'Low VOC (<25 g/L)',
      biodegradability_claim: 'Readily Biodegradable (OECD 301D)',
      biodegradable: true,
      hazardous: true,
      food_safe: false,
      use_cases: ['Fifth-Wheel Couplings', 'Engine Blocks', 'Forklift Mast Chains', 'Drilling Substructures', 'Workshop Pits'],
      compatible_surfaces: ['Heavy Carbon Steel', 'Cast Iron Machinery', 'Concrete Floors', 'Epoxy Slabs'],
      not_suitable_for: ['Polished Aluminium Wheels', 'Soft Aluminium Panels', 'Galvanised Metal'],
      contamination_types: ['Heavy Mineral Grease & Pitch', 'Burnt Engine Oil & Sludge', 'Bitumen & Asphalt Tack'],
      application_methods: ['Downstream Hot Injector', 'Manual Pre-Sprayer (5 min dwell)', 'Immersion Soak Tank'],
      compatible_equipment_types: ['Alkota Hot Water Washers', 'Alkota Steam Cleaners'],
      dilution_hot: '1:30 to 1:80',
      dilution_cold: '1:15 to 1:30',
      water_recovery_compatible: true,
      separator_compatible: true,
      recycling_compatible: false,
      available_sizes: ['5L', '25L', '200L Drum', '1000L IBC'],
      price_5l: 26.00,
      price_25l: 96.00,
      price_200l: 375.00,
      hazard_classification: 'Skin Corr. 1B; Eye Dam. 1 (GB CLP / UK REACH)',
      signal_word: 'DANGER',
      hazard_statements: ['H314: Causes severe skin burns and eye damage'],
      precautionary_statements: ['P280: Wear protective gloves and eye/face protection'],
      sds_url: '/documents/sds/alkota-sds-de703-grease-cutter.pdf',
      sds_revision_date: '08 February 2024 (Rev 3.2)',
      tds_url: '/documents/tds/alkota-tds-de703-grease-cutter.pdf',
      tds_revision_date: '10 February 2024',
      primary_image_url: '/assets/products/de703-grease-cutter.png'
    },
    {
      slug: 'power-blast-tr407',
      name: 'Power Blast TR-407',
      code: 'TR-407',
      category: 'fleet-vehicle',
      tagline: 'All-round commercial fleet & HGV wash — safe across paint, glass, and polished metal.',
      description: 'Power Blast TR-407 is the foundational fleet detergent for high-volume commercial vehicle operations. Engineered to dissolve stubborn electrostatic road film, diesel soot, and bug residue without damaging vehicle clear coats, polished aluminium trim, or window rubbers.',
      active: true,
      featured: true,
      uk_status: 'published',
      sort_order: 30,
      form: 'Concentrated Liquid',
      appearance: 'Clear Blue Liquid',
      ph_level: '9.5 – 10.2',
      specific_gravity: '1.04 @ 20°C',
      active_ingredients: ['Anti-Static Surfactants', 'Water Conditioners', 'Gloss Restorers'],
      voc_content: 'Zero VOC (<1 g/L)',
      biodegradability_claim: '100% Readily Biodegradable (OECD 301B)',
      biodegradable: true,
      hazardous: false,
      food_safe: false,
      use_cases: ['HGV Haulage Fleets', 'Delivery Vans', 'Bus & Coach Operators', 'Municipal Fleets'],
      compatible_surfaces: ['Automotive Clear Coat', 'Commercial Polyurethane', 'Polished Aluminium Wheels', 'Glass & Mirror Systems'],
      not_suitable_for: [],
      contamination_types: ['Electrostatic Traffic Film', 'Diesel Exhaust Stains', 'Bug & Insect Splatter', 'Winter Salt'],
      application_methods: ['Downstream Chemical Injector', 'Low-Pressure Foam Lance', 'Drive-Through Fleet Arch'],
      compatible_equipment_types: ['Hot Water Washers', 'Cold Water Washers', 'Alkota Wash Trailers'],
      dilution_hot: '1:60 to 1:120',
      dilution_cold: '1:40 to 1:80',
      water_recovery_compatible: true,
      separator_compatible: true,
      recycling_compatible: true,
      available_sizes: ['5L', '25L', '200L Drum', '1000L IBC'],
      price_5l: 19.50,
      price_25l: 76.00,
      price_200l: 295.00,
      hazard_classification: 'Eye Irrit. 2 (GB CLP / UK REACH)',
      signal_word: 'WARNING',
      hazard_statements: ['H319: Causes serious eye irritation'],
      precautionary_statements: ['P280: Wear eye protection'],
      sds_url: '/documents/sds/alkota-sds-tr407-power-blast.pdf',
      sds_revision_date: '20 January 2024 (Rev 5.0)',
      tds_url: '/documents/tds/alkota-tds-tr407-power-blast.pdf',
      tds_revision_date: '22 January 2024',
      primary_image_url: '/assets/products/truck-plant-wash.png'
    },
    {
      slug: 'touchless-tr470',
      name: 'Touchless TR-470',
      code: 'TR-470',
      category: 'fleet-vehicle',
      tagline: 'High-performance touchless vehicle wash — road film elimination with zero brush contact.',
      description: 'Touchless TR-470 is formulated specifically for operators who want high-gloss wash quality without physical brush contact. Its advanced surfactant formulation breaks the electrical bond between traffic film and painted bodywork, allowing road film, bug proteins, and salt crust to slide away during a high-pressure rinse.',
      active: true,
      featured: false,
      uk_status: 'published',
      sort_order: 40,
      form: 'Concentrated Liquid',
      appearance: 'Clear Straw-Coloured Liquid',
      ph_level: '10.5 – 11.0',
      specific_gravity: '1.06 @ 20°C',
      active_ingredients: ['Ionic & Non-Ionic Surfactants', 'Sequestering Agents'],
      voc_content: 'Low VOC (<5 g/L)',
      biodegradability_claim: 'Readily Biodegradable (OECD 301B)',
      biodegradable: true,
      hazardous: false,
      food_safe: false,
      use_cases: ['Drive-Through Fleet Bays', 'Curtainsider HGVs', 'Livery Protected Vans'],
      compatible_surfaces: ['Vinyl Fleet Wraps', 'Commercial Enamels', 'Aluminium Extrusions'],
      not_suitable_for: [],
      contamination_types: ['Electrostatic Traffic Film', 'Diesel Exhaust Staining', 'Road De-icing Salts'],
      application_methods: ['High-Pressure Foam Cannon', 'Drive-Through Arch'],
      compatible_equipment_types: ['Hot Water Pressure Washers', 'Cold Water Washers'],
      dilution_hot: '1:40 to 1:80',
      dilution_cold: '1:20 to 1:50',
      water_recovery_compatible: true,
      separator_compatible: true,
      recycling_compatible: true,
      available_sizes: ['25L Drum', '200L Drum', '1000L IBC'],
      price_25l: 88.00,
      price_200l: 345.00,
      hazard_classification: 'Skin Irrit. 2; Eye Irrit. 2 (GB CLP / UK REACH)',
      signal_word: 'WARNING',
      hazard_statements: ['H315: Causes skin irritation', 'H319: Causes serious eye irritation'],
      precautionary_statements: ['P280: Wear protective gloves and eye protection'],
      sds_url: '/documents/sds/alkota-sds-tr470-touchless.pdf',
      sds_revision_date: '04 February 2024',
      tds_url: '/documents/tds/alkota-tds-tr470-touchless.pdf',
      tds_revision_date: '04 February 2024',
      primary_image_url: '/assets/products/auto-shampoo.png'
    },
    {
      slug: 'apw-pro-clean',
      name: 'APW Pro Clean',
      code: 'APW-PC',
      category: 'parts-washers',
      tagline: 'Multi-metal aqueous parts washer detergent — low foaming with 60-day flash rust inhibition.',
      description: 'APW Pro Clean is an engineered aqueous detergent developed specifically for automatic rotary parts washers and immersion wash tanks. Formulated with low-foaming surfactants that remain stable under 10+ BAR mechanical spray pressures at 60°C–80°C.',
      active: true,
      featured: true,
      uk_status: 'published',
      sort_order: 60,
      form: 'Concentrated Liquid',
      appearance: 'Clear Pale Amber Liquid',
      ph_level: '9.2 – 9.8',
      specific_gravity: '1.05 @ 20°C',
      active_ingredients: ['Non-Foaming Surfactants', 'Vapour Phase Rust Inhibitors'],
      voc_content: 'Zero VOC (<1 g/L)',
      biodegradability_claim: '100% Readily Biodegradable (OECD 301B)',
      biodegradable: true,
      hazardous: false,
      food_safe: false,
      use_cases: ['Automatic Turntable Parts Washers', 'Ultrasonic Cleaning Tanks', 'Engine Rebuild Workshops'],
      compatible_surfaces: ['Aluminium Heads', 'Alloy Tool Steels', 'Cast Iron Blocks', 'Brass & Bronze Bushings'],
      not_suitable_for: [],
      contamination_types: ['Synthetic Engine Oils', 'Machining Coolants & Swarf', 'Heavy Gear Lube'],
      application_methods: ['Automatic Parts Washer Tank Charge (5–10% Vol)', 'Ultrasonic Bath'],
      compatible_equipment_types: ['Alkota APW Parts Washers', 'Heated Soak Tanks'],
      dilution_hot: '3% to 8% concentration by volume',
      dilution_cold: '5% to 10% concentration',
      water_recovery_compatible: true,
      separator_compatible: true,
      recycling_compatible: true,
      available_sizes: ['25L Drum', '200L Drum'],
      price_25l: 98.00,
      price_200l: 390.00,
      hazard_classification: 'Eye Irrit. 2 (GB CLP / UK REACH)',
      signal_word: 'WARNING',
      hazard_statements: ['H319: Causes serious eye irritation'],
      precautionary_statements: ['P280: Wear eye protection'],
      sds_url: '/documents/sds/alkota-sds-apw-pro-clean.pdf',
      sds_revision_date: '12 January 2024 (Rev 4.0)',
      tds_url: '/documents/tds/alkota-tds-apw-pro-clean.pdf',
      tds_revision_date: '15 January 2024',
      primary_image_url: '/assets/products/food-safe-cleaner.png'
    },
    {
      slug: 'scale-stop-coil-protector',
      name: 'Scale Stop Coil Protector',
      code: 'Scale Stop',
      category: 'specialty',
      tagline: 'Chemicially binds calcium and magnesium carbonates to prevent heating coil burnout.',
      description: 'The UK has some of the hardest water in Europe. When water is heated beyond 65°C inside Schedule 80 coils, calcium and magnesium carbonates precipitate out into dense rock-hard limescale. Scale Stop chelates minerals on the fly, keeping them in suspension through the burner loop and preserving Alkota\'s 7-year coil warranty.',
      active: true,
      featured: true,
      uk_status: 'published',
      sort_order: 70,
      form: 'Liquid Additive',
      appearance: 'Clear Colourless Liquid',
      ph_level: '7.0 – 7.5 (Neutral)',
      specific_gravity: '1.12 @ 20°C',
      active_ingredients: ['Polyphosphates', 'Polymer Dispersants'],
      voc_content: 'Zero VOC',
      biodegradability_claim: 'Non-persistent, Environmentally Neutral',
      biodegradable: true,
      hazardous: false,
      food_safe: false,
      use_cases: ['All Alkota Hot Water Pressure Washers', 'Dry Steam Cleaners', 'Mobile Trailer Units'],
      compatible_surfaces: ['Schedule 80 ASTM A53 Carbon Steel Coils', 'Brass Pump Heads', 'Ceramic Plungers'],
      not_suitable_for: [],
      contamination_types: ['Calcium Carbonate Limescale', 'Magnesium Mineral Encrustation'],
      application_methods: ['Automatic Float Tank Injection', 'Direct Header Tank Dosing'],
      compatible_equipment_types: ['All Alkota Hot Water Machines', 'All Alkota Steamers'],
      dilution_hot: 'Continuous metering at 1:1000 to 1:2000 (approx. 50–100 ml per 100L)',
      water_recovery_compatible: true,
      separator_compatible: true,
      recycling_compatible: true,
      available_sizes: ['5L Container', '25L Heavy Duty Drum'],
      price_5l: 24.00,
      price_25l: 92.00,
      hazard_classification: 'Non-Hazardous according to GB CLP regulations',
      signal_word: 'NONE',
      hazard_statements: [],
      precautionary_statements: ['P102: Keep out of reach of children'],
      sds_url: '/documents/sds/alkota-sds-scale-stop.pdf',
      sds_revision_date: '02 January 2024 (Rev 6.0)',
      tds_url: '/documents/tds/alkota-tds-scale-stop.pdf',
      tds_revision_date: '02 January 2024',
      primary_image_url: '/assets/products/scale-stop.png'
    },
    {
      slug: 'citrus-blast-de721',
      name: 'Citrus Blast DE-721',
      code: 'DE-721',
      category: 'degreasers',
      tagline: 'Neutral pH natural citrus degreaser — green, powerful, and safe on polished metals.',
      description: 'A chemically neutral, non-acid, non-alkaline heavy duty degreaser powered by concentrated natural citrus terpenes. Releases natural solvency to break down hydrocarbon grease, adhesive residues, and bitumen without attacking polished aluminium or delicate metals.',
      active: true,
      featured: false,
      uk_status: 'published',
      sort_order: 80,
      form: 'Concentrated Liquid',
      appearance: 'Clear Golden Liquid with Citrus Aroma',
      ph_level: '7.0 – 7.5',
      specific_gravity: '0.98 @ 20°C',
      active_ingredients: ['High Purity d-Limonene', 'Non-Ionic Surfactants'],
      voc_content: 'Medium VOC (Natural Terpenes)',
      biodegradability_claim: '100% Readily Biodegradable (OECD 301B)',
      biodegradable: true,
      hazardous: false,
      food_safe: false,
      use_cases: ['Polished Aluminium Tanker Degreasing', 'Food Preparation Equipment (Rinse after)', 'Workbenches'],
      compatible_surfaces: ['Mirror Polished Aluminium', 'Stainless Steel', 'Anodised Metal', 'Brass'],
      not_suitable_for: [],
      contamination_types: ['Heavy Grease', 'Adhesive Tape Glue', 'Bitumen Splatter', 'Food Fats'],
      application_methods: ['Pre-Spray Manual Trigger', 'Hot Water Pressure Washer'],
      compatible_equipment_types: ['Hot Water Washers', 'Cold Water Washers'],
      dilution_hot: '1:30 to 1:80',
      dilution_cold: '1:10 to 1:40',
      water_recovery_compatible: true,
      separator_compatible: true,
      recycling_compatible: true,
      available_sizes: ['5L', '25L', '200L Drum'],
      price_5l: 28.00,
      price_25l: 110.00,
      price_200l: 420.00,
      hazard_classification: 'Skin Sens. 1; Eye Irrit. 2 (GB CLP / UK REACH)',
      signal_word: 'WARNING',
      hazard_statements: ['H317: May cause an allergic skin reaction', 'H319: Causes serious eye irritation'],
      precautionary_statements: ['P280: Wear protective gloves and eye protection'],
      sds_url: '/documents/sds/alkota-sds-de721-citrus-blast.pdf',
      sds_revision_date: '10 January 2024',
      tds_url: '/documents/tds/alkota-tds-de721-citrus-blast.pdf',
      tds_revision_date: '10 January 2024',
      primary_image_url: '/assets/products/food-safe-cleaner.png'
    },
    {
      slug: 'crete-clean',
      name: 'Crete Clean Masonry Restorer',
      code: 'Crete Clean',
      category: 'masonry',
      tagline: 'Deep-penetrating masonry & concrete restorer — removes efflorescence, cement scale, and rust stains.',
      description: 'A specialised acidic cleaning formulation engineered for commercial concrete slabs, architectural block paving, and clay brickwork. Penetrates dense pores to dissolve carbonate efflorescence blooms, mortar smear, iron oxidation rust stains, and atmospheric grime.',
      active: true,
      featured: false,
      uk_status: 'published',
      sort_order: 100,
      form: 'Liquid Concentrate',
      appearance: 'Clear Light Straw Liquid',
      ph_level: '1.5 – 2.0 (Acidic)',
      specific_gravity: '1.10 @ 20°C',
      active_ingredients: ['Inhibited Organic Acids', 'Surfactant Penetrants'],
      voc_content: 'Zero VOC',
      biodegradability_claim: 'Biodegradable Organic Acid Base',
      biodegradable: true,
      hazardous: true,
      food_safe: false,
      use_cases: ['Brickwork Mortar Cleanup', 'Concrete Floor Efflorescence', 'Commercial Block Paving'],
      compatible_surfaces: ['Engineered Concrete', 'Clay Brickwork', 'Granite & Dense Stone'],
      not_suitable_for: ['Polished Marble', 'Limestone', 'Travertine', 'Raw Aluminium', 'Galvanised Metal'],
      contamination_types: ['Mortar Smear', 'Efflorescence Salt Blooms', 'Iron Rust Stains', 'Atmospheric Soot'],
      application_methods: ['Low-Pressure Acid-Resistant Pump Sprayer', 'Hot Water Pressure Washer Rinse'],
      compatible_equipment_types: ['Alkota Hot Water Washers', 'Rotary Flat Surface Cleaners'],
      dilution_hot: '1:5 to 1:20',
      dilution_cold: '1:3 to 1:10',
      water_recovery_compatible: false,
      separator_compatible: false,
      recycling_compatible: false,
      available_sizes: ['5L', '25L'],
      price_5l: 22.00,
      price_25l: 86.00,
      hazard_classification: 'Skin Corr. 1B; Eye Dam. 1 (GB CLP / UK REACH)',
      signal_word: 'DANGER',
      hazard_statements: ['H314: Causes severe skin burns and eye damage'],
      precautionary_statements: ['P280: Wear acid-resistant gloves, clothing and eye protection'],
      sds_url: '/documents/sds/alkota-sds-crete-clean.pdf',
      sds_revision_date: '05 January 2024',
      tds_url: '/documents/tds/alkota-tds-crete-clean.pdf',
      tds_revision_date: '05 January 2024',
      primary_image_url: '/assets/products/masonry-cleaner.png'
    }
  ];

  const bespokeToSeed = [
    {
      slug: 'standard-trailer-single-axle',
      name: 'Single-Axle Mobile Wash Trailer',
      build_type: 'trailer',
      tagline: 'Road-legal, wash-ready. Your mobile cleaning operation starts here.',
      description: 'Our single-axle bespoke trailer builds are designed around your pressure washer specification, your water supply needs, and your industry. Every trailer is engineered from the ground up by our UK team — not a standard unit with a machine bolted on. Full VTA/IVA road compliance, baffled water tanks up to 1,000L, integrated fuel tanks, dual hose reels, and tool storage. Available with hot or cold water machines, steam output, or combinations of both. GVW from 750kg to 1,500kg. We design, specify, and build to your exact brief.',
      featured: true,
      active: true,
      industries: ['fleet-transport', 'oil-gas', 'agriculture', 'local-authorities', 'plant-hire', 'construction'],
      spec_highlights: [
        { label: 'GVW Range', value: '750kg – 1,500kg' },
        { label: 'Water Tank', value: 'Up to 1,000L baffled onboard tank' },
        { label: 'Road Compliance', value: 'Full UK VTA / IVA compliant' },
        { label: 'Hose Reels', value: 'Up to 2 × 50m reels' },
        { label: 'Power Options', value: 'Hot water, cold water, or steam' },
        { label: 'Build Time', value: 'Typically 4–8 weeks from sign-off' }
      ],
      sort_order: 10
    },
    {
      slug: 'standard-trailer-tandem-axle',
      name: 'Tandem-Axle Heavy-Duty Wash Trailer',
      build_type: 'trailer',
      tagline: 'Multi-crew. Multi-machine. Maximum mobile capability.',
      description: 'Our tandem-axle builds are for operations that need serious mobile washing power — multiple machines, large water reserves, generator systems, and heavy-duty deployment capability. Built on tandem axle platforms from 1,500kg to 3,500kg GVW, these rigs carry everything a contract cleaning or emergency response team needs on a single road-legal trailer. Fully custom — every tandem build starts with a conversation about your operation.',
      featured: true,
      active: true,
      industries: ['oil-gas', 'fleet-transport', 'local-authorities', 'construction', 'waste-management', 'mining'],
      spec_highlights: [
        { label: 'GVW Range', value: '1,500kg – 3,500kg' },
        { label: 'Water Tank', value: 'Up to 2,091L baffled onboard tank' },
        { label: 'Road Compliance', value: 'Full UK VTA / IVA compliant' },
        { label: 'Machine Capacity', value: 'Dual machine configuration available' },
        { label: 'Generator', value: 'Silent onboard generator option' },
        { label: 'Hose Reels', value: 'Up to 4 × 100m reels' },
        { label: 'Lighting', value: 'Full site work lighting package' }
      ],
      sort_order: 20
    },
    {
      slug: 'wash-plant-mat-access-panel',
      name: 'Automated Mat & Access Panel Wash Plant',
      build_type: 'wash-plant',
      tagline: '360° automated wash. A 14ft rig mat cleaned in under 4 minutes.',
      description: 'The Alkota Wash Plant is a patent-pending 360° automated conveyor cleaning system for rig mats, access panels, and large-format industrial matting. Purpose-built for the oil & gas, construction, and plant hire industries where mat cleaning is a significant operational cost and environmental compliance obligation. The system passes mats through a wash station built over an automated variable-speed conveyor. 20 rotating cleaning arms deliver 40 GPM at 4,000 PSI to the top, bottom, and sides simultaneously — more cleaning power in 4 minutes than a single operator in 45. On-demand hot water from dual one-million BTU heaters. Closed-loop water recycling reduces water consumption by over 250 gallons per mat compared to manual methods — eliminating water hauling and disposal costs entirely. Optional chlorination system for invasive species compliance.',
      featured: true,
      active: true,
      industries: ['oil-gas', 'construction', 'plant-hire', 'mining'],
      spec_highlights: [
        { label: 'Cleaning Speed', value: '14ft mat in under 4 minutes' },
        { label: 'Pump Output', value: '40 GPM at 4,000 PSI' },
        { label: 'Cleaning Arms', value: '20 rotating nozzle arms — 360° coverage' },
        { label: 'Hot Water', value: 'Dual 1,000,000 BTU heaters — up to 135°F rise' },
        { label: 'Conveyor Speed', value: 'Variable — up to 20 linear ft/min (5HP Servo Motor)' },
        { label: 'Max Mat Thickness', value: '12 inches — height adjustable wash station' },
        { label: 'Max Mat Length', value: 'Standard 20ft — extended tables for 40ft mats' },
        { label: 'Water Recycling', value: 'Closed-loop — saves 250+ gallons per mat' },
        { label: 'Filtration', value: 'Down to 20 micron — auto backwash media filters' },
        { label: 'Chlorination', value: 'Optional — dilution-controlled chlorine system' },
        { label: 'Compliance', value: 'Meets EA wash water discharge regulations' }
      ],
      sort_order: 30
    },
    {
      slug: 'skid-unit-custom',
      name: 'Custom Skid-Mount Pressure Washing Unit',
      build_type: 'skid-unit',
      tagline: 'Permanent skid integration — for vehicles, flatbeds, and fixed plant.',
      description: 'Custom skid-mount units are designed for permanent integration onto service vehicles, flatbed trucks, offshore containers, and fixed plant installations. Each skid is engineered to the exact footprint and power supply of the intended platform. Available with hot or cold water machines, steam output, water tanks, generator systems, and any combination of ancillary equipment. UK ATEX zone compliance available for hazardous area applications.',
      featured: false,
      active: true,
      industries: ['oil-gas', 'fleet-transport', 'mining', 'manufacturing'],
      spec_highlights: [
        { label: 'Mounting', value: 'Vehicle, flatbed, container, or static' },
        { label: 'Power', value: 'Mains, generator, or engine driven' },
        { label: 'ATEX', value: 'Zone 1 / Zone 2 hazardous area versions available' },
        { label: 'Output', value: 'Hot water, cold water, steam, or combination' }
      ],
      sort_order: 40
    }
  ];

  try {
    // Delete existing
    await supabaseAdmin.from('products').delete().neq('slug', 'test-dummy-xyz');
    await supabaseAdmin.from('chemicals').delete().neq('slug', 'test-dummy-xyz');
    await supabaseAdmin.from('bespoke_builds').delete().neq('slug', 'test-dummy-xyz');

    // Insert
    const { error: pe } = await supabaseAdmin.from('products').insert(productsToSeed);
    if (pe) throw new Error('Products error: ' + pe.message);
    
    const { error: ce } = await supabaseAdmin.from('chemicals').insert(chemicalsToSeed);
    if (ce) throw new Error('Chemicals error: ' + ce.message);

    const { error: be } = await supabaseAdmin.from('bespoke_builds').insert(bespokeToSeed);
    if (be) throw new Error('Bespoke builds error: ' + be.message);

    console.log('Seeding completed successfully!');
  } catch (err: any) {
    console.error('Seeding failed:', err.message);
    process.exit(1);
  }
}

main();
