import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase/server';
import { verifyToken, COOKIE_NAME } from '@/lib/auth';

async function requireAdmin(req: NextRequest) {
  const token = req.cookies.get(COOKIE_NAME)?.value;
  if (!token) return false;
  return !!(await verifyToken(token));
}

export async function GET(req: NextRequest) {
  if (!(await requireAdmin(req))) {
    return NextResponse.json({ error: 'Unauthorised' }, { status: 401 });
  }
  try {
    // 1. Seed Products
    const productsToSeed = [
      // ELITE / XH4 SERIES
      {
        slug: 'alkota-430xh',
        name: 'Alkota 430XH',
        series: 'XH4 Series',
        category: 'hot-water',
        tagline: 'Elite portable electric hot water — the benchmark.',
        description: 'The 430XH is the pinnacle of portable electric hot water pressure washing. Belt-driven triplex pump runs at lower RPM for a cooler, quieter, longer-lasting operation. Industry-leading hydro-insulated Schedule 80 coil with Soft Damping System. Comes standard with industrial hose, insulated trigger gun with safety lock, insulated wand, and quick-connect nozzles. Backed by Alkota\'s 7-year coil warranty — the best in the industry by far.',
        featured: true,
        active: true,
        flow_rate_gpm: 3.9,
        flow_rate_lpm: 14.8,
        pressure_psi: 3000,
        pressure_bar: 207,
        power_source: 'Electric 230V',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: '230V 1-Phase',
        portable: true,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['oil-gas', 'fleet-transport', 'food-processing', 'construction', 'manufacturing', 'agriculture'],
        sort_order: 10
      },
      {
        slug: 'alkota-420xh',
        name: 'Alkota 420XH',
        series: 'XH4 Series',
        category: 'hot-water',
        tagline: 'Standard industrial power in a proven portable frame.',
        description: 'The workhorse of the XH4 range. Belt-driven, oil-fired, delivering reliable 2000 PSI hot water cleaning across the most demanding industrial environments. The same 7-year coil warranty and Soft Damping System as its bigger sibling. Quiet, low-vibration operation. Four-wheel design rolls over any surface.',
        featured: true,
        active: true,
        flow_rate_gpm: 3.5,
        flow_rate_lpm: 13.2,
        pressure_psi: 2000,
        pressure_bar: 138,
        power_source: 'Electric 230V',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: '230V 1-Phase',
        portable: true,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['fleet-transport', 'construction', 'agriculture', 'waste-management', 'plant-hire'],
        sort_order: 20
      },
      {
        slug: 'alkota-330xh4',
        name: 'Alkota 330XH4',
        series: 'XH4 Series',
        category: 'hot-water',
        tagline: 'Compact high-pressure electric — maximum PSI, minimal footprint.',
        description: 'Where space is tight but performance cannot be compromised. The 330XH4 delivers a full 3000 PSI from a compact belt-driven electric frame. Same coil and pump engineering as the larger XH4 units. Ideal for workshops, plant rooms, and operations where portability is critical.',
        featured: false,
        active: true,
        flow_rate_gpm: 3.0,
        flow_rate_lpm: 11.4,
        pressure_psi: 3000,
        pressure_bar: 207,
        power_source: 'Electric 230V',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: '230V 1-Phase',
        portable: true,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['manufacturing', 'automotive', 'food-processing', 'marine'],
        sort_order: 30
      },
      // AX4 SERIES
      {
        slug: 'alkota-420ax4',
        name: 'Alkota 420AX4',
        series: 'AX4 Series',
        category: 'hot-water',
        tagline: 'Compact industrial power — the entry point to Alkota hot water.',
        description: 'The AX4 series brings genuine Alkota engineering to a compact, lightweight frame. Belt-driven pump, oil-fired heating, available in 115V or 230V to suit any power supply. Four-wheel portable. Perfect first machine for trades, small fleet operations, and agricultural businesses stepping up from consumer-grade kit.',
        featured: false,
        active: true,
        flow_rate_gpm: 3.5,
        flow_rate_lpm: 13.2,
        pressure_psi: 2000,
        pressure_bar: 138,
        power_source: 'Electric 115V / 230V',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: '115V or 230V',
        portable: true,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['agriculture', 'automotive', 'plant-hire', 'manufacturing'],
        sort_order: 40
      },
      {
        slug: 'alkota-216ax4',
        name: 'Alkota 216AX4',
        series: 'AX4 Series',
        category: 'hot-water',
        tagline: 'The compact 115V entry point to industrial hot water cleaning.',
        description: 'The most compact machine in the Alkota hot water range, running on a standard 115V supply. Oil-fired heat, belt-driven pump, fully portable. Ideal for workshops, garages, and small-scale industrial cleaning where a full-size machine would be overkill.',
        featured: false,
        active: true,
        flow_rate_gpm: 2.0,
        flow_rate_lpm: 7.6,
        pressure_psi: 1600,
        pressure_bar: 110,
        power_source: 'Electric 115V',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: '115V',
        portable: true,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['automotive', 'manufacturing', 'agriculture'],
        sort_order: 50
      },
      // X4 SERIES
      {
        slug: 'alkota-420x4',
        name: 'Alkota 420X4',
        series: 'X4 Series',
        category: 'hot-water',
        tagline: 'The industry workhorse. Decades of proven performance.',
        description: 'The X4 belt drive series has been the backbone of industrial hot water cleaning for decades. Heavy-gauge welded steel frame, belt-driven triplex pump, oil-fired heating. Available across a wide GPM and PSI range to match any application. When reliability is non-negotiable, this is the machine.',
        featured: true,
        active: true,
        flow_rate_gpm: 3.5,
        flow_rate_lpm: 13.2,
        pressure_psi: 2000,
        pressure_bar: 138,
        power_source: 'Electric 230V',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: '230V',
        portable: true,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['oil-gas', 'fleet-transport', 'construction', 'agriculture', 'waste-management', 'local-authorities'],
        sort_order: 60
      },
      // EN/HN SERIES
      {
        slug: 'alkota-5355hnl',
        name: 'Alkota 5355HNL',
        series: 'EN/HN Series',
        category: 'hot-water',
        tagline: 'Extreme-volume hot water for the heaviest industrial duty.',
        description: 'When the job demands serious volume, the HNL series delivers. Narrow-frame design allows deployment in tight spaces without sacrificing output. Diesel or gas engine driven — fully independent of mains power. Ideal for remote site operations, oil field maintenance, and heavy plant cleaning.',
        featured: true,
        active: true,
        flow_rate_gpm: 5.0,
        flow_rate_lpm: 18.9,
        pressure_psi: 3500,
        pressure_bar: 241,
        power_source: 'Gas / Diesel Engine',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: 'Engine Driven',
        portable: true,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['oil-gas', 'construction', 'plant-hire', 'mining', 'waste-management'],
        sort_order: 70
      },
      {
        slug: 'alkota-8405hnl',
        name: 'Alkota 8405HNL',
        series: 'EN/HN Series',
        category: 'hot-water',
        tagline: 'Maximum flow, maximum force — for the jobs nothing else can touch.',
        description: 'The most powerful portable hot water machine in the Alkota fleet. 8 GPM at 4000 PSI — the kind of output that strips years of industrial contamination in minutes. Engine-driven and fully self-contained. Designed for oil & gas, heavy construction, and any environment where performance is the only metric that matters.',
        featured: true,
        active: true,
        flow_rate_gpm: 8.0,
        flow_rate_lpm: 30.3,
        pressure_psi: 4000,
        pressure_bar: 276,
        power_source: 'Gas / Diesel Engine',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: 'Engine Driven',
        portable: true,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['oil-gas', 'mining', 'construction', 'waste-management', 'plant-hire'],
        sort_order: 80
      },
      {
        slug: 'alkota-7407dnl',
        name: 'Alkota 7407DNL',
        series: 'EN/HN Series',
        category: 'hot-water',
        tagline: 'Diesel-powered high-capacity hot water for remote and off-grid operations.',
        description: 'All-diesel operation — no mains power required anywhere. The 7407DNL brings 7 GPM at 4000 PSI to the most remote sites on the planet. Built on the same narrow-frame architecture as the HNL series for access where larger rigs can\'t go.',
        featured: false,
        active: true,
        flow_rate_gpm: 7.0,
        flow_rate_lpm: 26.5,
        pressure_psi: 4000,
        pressure_bar: 276,
        power_source: 'Diesel Engine',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: 'Engine Driven',
        portable: true,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['oil-gas', 'mining', 'construction', 'agriculture'],
        sort_order: 90
      },
      // XD4 SERIES
      {
        slug: 'alkota-4405xd4',
        name: 'Alkota 4405XD4',
        series: 'XD4 Series',
        category: 'hot-water',
        tagline: 'Flagship Honda-powered performance — mobile, unstoppable.',
        description: 'Honda GX engine. Direct drive. 4000 PSI. The XD4 is built for operators who need serious hot water performance with zero dependency on electrical infrastructure. Fully portable, oil-fired heat, and Honda\'s legendary engine reliability. The choice for mobile contract cleaners, oil field operators, and anyone working far from a plug socket.',
        featured: true,
        active: true,
        flow_rate_gpm: 4.0,
        flow_rate_lpm: 15.1,
        pressure_psi: 4000,
        pressure_bar: 276,
        power_source: 'Honda GX Engine',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: 'Engine Driven',
        portable: true,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['oil-gas', 'construction', 'fleet-transport', 'agriculture', 'plant-hire'],
        sort_order: 100
      },
      // GED 12V SKID
      {
        slug: 'alkota-4405f',
        name: 'Alkota 4405F',
        series: 'GED 12V Skid Series',
        category: 'hot-water',
        tagline: 'Versatile gasoline skid unit — trailer and vehicle mount ready.',
        description: 'Skid-mount design built for integration into trailer rigs, flatbeds, and service vehicles. Gasoline engine, 12V ignition system, oil-fired heat. 4000 PSI output. Pairs perfectly with Alkota\'s bespoke trailer programme — specify this unit as the heart of a custom mobile wash rig.',
        featured: false,
        active: true,
        flow_rate_gpm: 4.0,
        flow_rate_lpm: 15.1,
        pressure_psi: 4000,
        pressure_bar: 276,
        power_source: 'Gasoline Engine',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: '12V Engine Driven',
        portable: false,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['fleet-transport', 'oil-gas', 'construction', 'plant-hire'],
        sort_order: 110
      },
      // DED SERIES
      {
        slug: 'alkota-10307kk',
        name: 'Alkota 10307KK',
        series: 'DED Series',
        category: 'hot-water',
        tagline: 'The heavy-duty diesel workhorse — 10 GPM, no compromise.',
        description: 'The biggest, most capable machine in the Alkota portable hot water range. Diesel engine driven with 10 GPM flow and 3000 PSI — designed for operations that run all day, every day. Used in the most demanding environments on earth: mining, offshore support, heavy plant, and large-scale fleet operations. Self-contained diesel power means it goes anywhere.',
        featured: true,
        active: true,
        flow_rate_gpm: 10.0,
        flow_rate_lpm: 37.9,
        pressure_psi: 3000,
        pressure_bar: 207,
        power_source: 'Diesel Engine',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: 'Engine Driven',
        portable: false,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['oil-gas', 'mining', 'construction', 'waste-management', 'plant-hire'],
        sort_order: 120
      },
      // GAS FIRED STATIONARY
      {
        slug: 'alkota-gas-fired-stationary',
        name: 'Alkota Gas Fired Stationary Series',
        series: 'Gas Fired Series',
        category: 'hot-water',
        tagline: 'High-output stationary hot water — gas-fired for permanent installations.',
        description: 'The Gas Fired Series is designed for permanent or semi-permanent installation where mains gas (LP or natural gas) is available. Output ranges from 2.1 GPM up to 10 GPM at pressures up to 5000 PSI — the highest PSI in the Alkota range. Ideal for vehicle wash bays, wash pads, abattoirs, food processing facilities, and any fixed industrial wash station needing maximum performance.',
        featured: false,
        active: true,
        flow_rate_gpm: 5.0,
        flow_rate_lpm: 18.9,
        pressure_psi: 5000,
        pressure_bar: 345,
        power_source: 'Electric Motor',
        heating_fuel: 'Gas (LP or Natural Gas)',
        voltage: '230V / 415V 3-Phase',
        portable: false,
        warranty_years: 7,
        certifications: ['CE', 'UKCA'],
        industries: ['food-processing', 'agriculture', 'fleet-transport', 'manufacturing', 'local-authorities'],
        sort_order: 130
      },
      // COLD WATER MACHINES
      {
        slug: 'alkota-530bd',
        name: 'Alkota 530BD',
        series: 'BD Industrial Series',
        category: 'cold-water',
        tagline: 'Industrial cabinet cold water — portable or stationary, built to last.',
        description: 'The BD Industrial series is the benchmark for cold water pressure washing in UK industry. Cabinet-style enclosed frame protects all components from the elements. Belt-driven pump runs quieter and cooler than direct drive. Available from 2 to 5 GPM at pressures up to 3000 PSI. 115V or 230V power options. Portable or stationary configurations.',
        featured: true,
        active: true,
        flow_rate_gpm: 4.0,
        flow_rate_lpm: 15.1,
        pressure_psi: 3000,
        pressure_bar: 207,
        power_source: 'Electric 115V / 230V',
        heating_fuel: 'N/A — Cold Water',
        voltage: '115V or 230V',
        portable: true,
        warranty_years: 5,
        certifications: ['CE', 'UKCA'],
        industries: ['manufacturing', 'agriculture', 'fleet-transport', 'construction', 'automotive'],
        sort_order: 200
      },
      {
        slug: 'alkota-s-sh-electric',
        name: 'Alkota S & SH Electric Series',
        series: 'S & SH Series',
        category: 'cold-water',
        tagline: 'High-pressure electric cold water — up to 5000 PSI.',
        description: 'The S and SH series covers the widest pressure range in cold water cleaning, from 3 GPM right up to 8 GPM and 5000 PSI. S-frame heavy-gauge steel construction. 230V electric — direct drive for maximum pressure output. The SH variant adds hot water capability for crossover applications. The choice when maximum PSI is the priority.',
        featured: true,
        active: true,
        flow_rate_gpm: 5.0,
        flow_rate_lpm: 18.9,
        pressure_psi: 5000,
        pressure_bar: 345,
        power_source: 'Electric 230V',
        heating_fuel: 'N/A — Cold Water',
        voltage: '230V',
        portable: true,
        warranty_years: 5,
        certifications: ['CE', 'UKCA'],
        industries: ['oil-gas', 'mining', 'construction', 'manufacturing'],
        sort_order: 210
      },
      {
        slug: 'alkota-sg-sm-gas-diesel',
        name: 'Alkota SG / SM Gas & Diesel Series',
        series: 'SG/SM Series',
        category: 'cold-water',
        tagline: 'Gas and diesel cold water — full independence from the mains.',
        description: 'When the site has no power supply, the SG (gas) and SM (gasoline) series step in. Ranging from 3.4 to 8.5 GPM at pressures up to an extraordinary 8500 PSI — among the highest cold water outputs available anywhere. Engine-driven skid or portable configurations. The definitive choice for remote industrial and civil engineering sites.',
        featured: false,
        active: true,
        flow_rate_gpm: 5.0,
        flow_rate_lpm: 18.9,
        pressure_psi: 8500,
        pressure_bar: 586,
        power_source: 'Gas / Diesel Engine',
        heating_fuel: 'N/A — Cold Water',
        voltage: 'Engine Driven',
        portable: true,
        warranty_years: 5,
        certifications: ['CE', 'UKCA'],
        industries: ['construction', 'oil-gas', 'mining', 'plant-hire', 'agriculture'],
        sort_order: 220
      },
      {
        slug: 'alkota-challenger',
        name: 'Alkota Challenger Series',
        series: 'Challenger Series',
        category: 'cold-water',
        tagline: 'Aluminium frame cold water — lightweight, durable, versatile.',
        description: 'The Challenger series brings aluminium frame construction to cold water pressure washing — significantly lighter than steel frame alternatives without sacrificing durability. Available in electric (115V or 220V) and gas engine versions from 2 to 4 GPM at up to 4000 PSI. Ideal where portability and weight are key considerations.',
        featured: false,
        active: true,
        flow_rate_gpm: 3.0,
        flow_rate_lpm: 11.4,
        pressure_psi: 4000,
        pressure_bar: 276,
        power_source: 'Electric 115V / 230V or Gas Engine',
        heating_fuel: 'N/A — Cold Water',
        voltage: '115V / 230V or Engine',
        portable: true,
        warranty_years: 5,
        certifications: ['CE', 'UKCA'],
        industries: ['agriculture', 'automotive', 'construction', 'plant-hire'],
        sort_order: 230
      },
      {
        slug: 'alkota-hhs-farm',
        name: 'Alkota HHS Farm Series',
        series: 'HHS Series',
        category: 'cold-water',
        tagline: 'Purpose-built cold water for livestock and agricultural cleaning.',
        description: 'The HHS series was engineered specifically for the demands of livestock and agricultural cleaning — hog barns, poultry units, cattle sheds, dairy washdowns. High flow rates from 3.5 to 9.2 GPM at pressures up to 4000 PSI. 230V electric. Built to survive the corrosive, high-humidity environments that destroy lesser machines.',
        featured: true,
        active: true,
        flow_rate_gpm: 6.0,
        flow_rate_lpm: 22.7,
        pressure_psi: 4000,
        pressure_bar: 276,
        power_source: 'Electric 230V',
        heating_fuel: 'N/A — Cold Water',
        voltage: '230V',
        portable: true,
        warranty_years: 5,
        certifications: ['CE', 'UKCA'],
        industries: ['agriculture'],
        sort_order: 240
      },
      {
        slug: 'alkota-jetter',
        name: 'Alkota Jetter Series',
        series: 'Jetter Series',
        category: 'cold-water',
        tagline: 'Electric and gas drain jetter — blast through blocked pipes and drains.',
        description: 'Designed specifically for drain, sewer, and pipe jetting applications. High pressure (up to 4000 PSI) combined with specialist jetting lances and nozzles cuts through blockages, root intrusion, and decades of built-up scale. Electric (115V) and gasoline engine variants. 2 to 8 GPM flow range. The choice for drainage contractors, local authorities, and utilities.',
        featured: false,
        active: true,
        flow_rate_gpm: 4.0,
        flow_rate_lpm: 15.1,
        pressure_psi: 4000,
        pressure_bar: 276,
        power_source: 'Electric 115V or Gas Engine',
        heating_fuel: 'N/A — Cold Water',
        voltage: '115V or Engine',
        portable: true,
        warranty_years: 5,
        certifications: ['CE', 'UKCA'],
        industries: ['local-authorities', 'construction', 'waste-management', 'manufacturing'],
        sort_order: 250
      },
      {
        slug: 'alkota-wash-cannon-2110',
        name: 'Alkota Wash Cannon 2110',
        series: 'Wash Cannon Series',
        category: 'cold-water',
        tagline: 'High-volume cold water cannon — 21-25 GPM for rapid bulk cleaning.',
        description: 'When speed matters more than pressure. The Wash Cannon delivers 21-25 GPM at up to 1000 PSI — extraordinary volume for rapid flushing of large areas, livestock housing, vehicle yards, and construction sites. Gas or electric. Clears a yard in minutes rather than hours.',
        featured: false,
        active: true,
        flow_rate_gpm: 23.0,
        flow_rate_lpm: 87.1,
        pressure_psi: 1000,
        pressure_bar: 69,
        power_source: 'Gas Engine or Electric',
        heating_fuel: 'N/A — Cold Water',
        voltage: 'Engine or Electric',
        portable: true,
        warranty_years: 5,
        certifications: ['CE', 'UKCA'],
        industries: ['agriculture', 'construction', 'waste-management', 'local-authorities'],
        sort_order: 260
      },
      {
        slug: 'alkota-219cse',
        name: 'Alkota 219CSE',
        series: '219CSE',
        category: 'cold-water',
        tagline: 'Compact electric cold water — portable, powerful, plug-and-go.',
        description: 'The most portable machine in the Alkota range. 115V plug-in, lightweight, genuine Alkota build quality in a compact form factor. 2000 PSI — far beyond any consumer-grade machine. The ideal first Alkota for tradespeople, small businesses, and anyone needing professional-grade results from the most portable possible unit.',
        featured: false,
        active: true,
        flow_rate_gpm: 1.7,
        flow_rate_lpm: 6.4,
        pressure_psi: 2000,
        pressure_bar: 138,
        power_source: 'Electric 115V',
        heating_fuel: 'N/A — Cold Water',
        voltage: '115V',
        portable: true,
        warranty_years: 5,
        certifications: ['CE', 'UKCA'],
        industries: ['automotive', 'agriculture', 'manufacturing'],
        sort_order: 270
      },
      // STEAM CLEANERS
      {
        slug: 'alkota-steam-111',
        name: 'Alkota Model 111',
        series: 'Steam Series',
        category: 'steam',
        tagline: 'High-pressure steam cleaning — sanitise without chemicals.',
        description: 'Steam cleaning delivers a level of sanitisation that pressure washing alone cannot match. Alkota\'s oil-fired steam cleaners produce high-pressure steam for instant emulsification of grease, oil, and biological contamination. No chemicals required for many applications — the heat alone does the work. Widely used in food production, agriculture, and anywhere chemical-free sanitisation is required.',
        featured: false,
        active: true,
        flow_rate_gpm: 0,
        flow_rate_lpm: 0,
        pressure_psi: 0,
        pressure_bar: 0,
        power_source: 'Electric Motor',
        heating_fuel: 'Oil (Diesel / Kerosene)',
        voltage: '230V',
        portable: true,
        warranty_years: 5,
        certifications: ['CE', 'UKCA'],
        industries: ['food-processing', 'agriculture', 'manufacturing', 'automotive'],
        sort_order: 300
      },
      // PARTS WASHERS
      {
        slug: 'alkota-parts-washer-compact',
        name: 'Alkota Compact Top-Load Parts Washer',
        series: 'Parts Washer Series',
        category: 'parts-washer',
        tagline: 'Aqueous parts washing — grease-free in minutes, no solvents.',
        description: 'Industrial aqueous parts washers that use hot water and biodegradable detergent to remove grease and contamination from components — no hazardous solvents or aerosols. Turntable design: load parts, close lid, set timer. Compact top-load models for smaller components; larger cabinet models for heavy parts. The sustainable, COSHH-compliant alternative to solvent degreasing.',
        featured: false,
        active: true,
        flow_rate_gpm: 0,
        flow_rate_lpm: 0,
        pressure_psi: 0,
        pressure_bar: 0,
        power_source: 'Electric 230V',
        heating_fuel: 'N/A',
        voltage: '230V',
        portable: false,
        warranty_years: 3,
        certifications: ['CE', 'UKCA'],
        industries: ['manufacturing', 'automotive', 'agriculture', 'construction'],
        sort_order: 400
      },
      // WATER TREATMENT
      {
        slug: 'alkota-vfs-1',
        name: 'Alkota VFS-1 Vacuum Filtration System',
        series: 'Water Treatment',
        category: 'water-treatment',
        tagline: 'Portable closed-loop water recovery — Environment Agency compliant.',
        description: 'The VFS-1 (Vacuum Filtration System) is a portable wash water recovery and recycling unit that allows fully compliant pressure washing in areas subject to Environment Agency wash water discharge regulations. Recovers wash water from up to 100 metres away, filters to remove 99% of free petroleum hydrocarbons, and recycles clean water back to the pressure washer. Prevents contaminated runoff from reaching surface drains, watercourses, and soakaways.',
        featured: false,
        active: true,
        flow_rate_gpm: 0,
        flow_rate_lpm: 0,
        pressure_psi: 0,
        pressure_bar: 0,
        power_source: 'Electric',
        heating_fuel: 'N/A',
        voltage: '230V',
        portable: true,
        warranty_years: 3,
        certifications: ['CE', 'UKCA'],
        industries: ['oil-gas', 'fleet-transport', 'local-authorities', 'construction', 'mining'],
        sort_order: 500
      },
      {
        slug: 'alkota-csf-10',
        name: 'Alkota CSF-10 Media Sand Filtration',
        series: 'Water Treatment',
        category: 'water-treatment',
        tagline: 'Low-maintenance wash pad water recycling for permanent installations.',
        description: 'The CSF-10 is a cost-effective, ultra-low-maintenance closed-loop filtration system for wash pads and fixed wash bays. 10 GPM filtration capacity, 300 lb sand media bed, auto-backwash. Allows full compliance with local authority discharge conditions without the operational complexity of more advanced systems.',
        featured: false,
        active: true,
        flow_rate_gpm: 0,
        flow_rate_lpm: 0,
        pressure_psi: 0,
        pressure_bar: 0,
        power_source: 'Electric',
        heating_fuel: 'N/A',
        voltage: '230V',
        portable: false,
        warranty_years: 3,
        certifications: ['CE', 'UKCA'],
        industries: ['fleet-transport', 'local-authorities', 'food-processing', 'manufacturing'],
        sort_order: 510
      },
      {
        slug: 'alkota-evaporator',
        name: 'Alkota Evaporator Series',
        series: 'Water Treatment',
        category: 'water-treatment',
        tagline: 'Wastewater evaporation — eliminate disposal costs entirely.',
        description: 'For wash water that is too contaminated to filter and too expensive to pump away. The Alkota Evaporator burns off bulk wastewater cleanly and efficiently using LP or natural gas, evaporating up to 480 gallons per day. Massively reduces or eliminates liquid waste disposal costs. Quiet LP/NG combustion, built-in defoamer pump.',
        featured: false,
        active: true,
        flow_rate_gpm: 0,
        flow_rate_lpm: 0,
        pressure_psi: 0,
        pressure_bar: 0,
        power_source: 'LP / Natural Gas',
        heating_fuel: 'Gas (LP or NG)',
        voltage: 'Gas Fired',
        portable: false,
        warranty_years: 3,
        certifications: ['CE', 'UKCA'],
        industries: ['oil-gas', 'manufacturing', 'food-processing', 'waste-management'],
        sort_order: 520
      }
    ];

    // Delete existing products to avoid conflicts or clean seed
    await supabaseAdmin.from('products').delete().neq('id', '00000000-0000-0000-0000-000000000000');

    // Insert products
    const { error: pError } = await supabaseAdmin.from('products').insert(productsToSeed);
    if (pError) throw new Error(`Products insertion failed: ${pError.message}`);

    // 2. Seed Chemicals
    const chemicalsToSeed = [
      {
        slug: 'grease-cutter-de703',
        name: 'Grease Cutter DE-703',
        code: 'DE-703',
        category: 'degreaser',
        tagline: 'Concentrated grease penetrator — leaves surfaces spotless.',
        description: 'A concentrated formula that penetrates grease, oil and dirt on contact, then creates a barrier between the stain and surface. Attacks the most difficult cleaning projects and leaves an extremely clean, free-rinsing surface. Non-hazardous biodegradable additive — safe for use in hot or cold water washers or as a pre-spray.',
        featured: true,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['engines', 'vehicles', 'fifth-wheels', 'industrial equipment', 'workshop floors'],
        compatible_surfaces: ['painted metal', 'steel', 'most industrial surfaces'],
        not_suitable_for: [],
        available_sizes: ['5L', '25L', '200L Drum', '1000L IBC'],
        sort_order: 10
      },
      {
        slug: 'mach1-de-tr413',
        name: 'Mach 1 Degreaser TR-413',
        code: 'TR-413',
        category: 'degreaser',
        tagline: 'Quick-release biodegradable degreaser — safe on painted surfaces.',
        description: 'A blend of surfactants, alcohol and natural citrus byproduct. Quick-release, readily biodegradable and environmentally friendly. Safe on carts, trucks, recreational vehicles, decks, sidewalks and driveways. Helps restore and renew old oxidised paint and vinyl surfaces. Safe for use in food preparation areas.',
        featured: false,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['trucks', 'vehicles', 'decks', 'house siding', 'food prep areas'],
        compatible_surfaces: ['painted surfaces', 'vinyl', 'aluminium', 'glass'],
        not_suitable_for: [],
        available_sizes: ['5L', '25L', '200L Drum'],
        sort_order: 20
      },
      {
        slug: 'citrus-blast-de721',
        name: 'Citrus Blast DE-721',
        code: 'DE-721',
        category: 'degreaser',
        tagline: 'Neutral pH natural citrus degreaser — green, powerful, food-safe.',
        description: 'A chemically neutral, non-acid, non-alkaline, natural-based heavy duty degreaser. Environmentally friendly "green" formula. Works well in food prep areas and as a standalone degreaser or additive to other detergents. Releases the natural power of citrus to dissolve grease, grime and tough dirt. Works particularly well combined with Iron Phosphatizer SD-919.',
        featured: false,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['food processing equipment', 'engines', 'industrial machinery', 'food prep areas'],
        compatible_surfaces: ['all surfaces including aluminium and polished aluminium'],
        not_suitable_for: [],
        available_sizes: ['5L', '25L', '200L Drum'],
        sort_order: 30
      },
      {
        slug: 'super-red-de750',
        name: 'Super Red Degreaser DE-750',
        code: 'DE-750',
        category: 'degreaser',
        tagline: 'Heavy-duty hydroxide degreaser for the toughest industrial applications.',
        description: 'Specifically formulated with a balanced blend of hydroxides and butyl to work on the toughest degreasing jobs. Removes smoke, carbon, greases, oils, carbonaceous soils and built-up road film. Excellent for cleaning engines, fifth-wheels, mining equipment, logging and oil field equipment, fork trucks, construction equipment and floors.',
        featured: true,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['engines', 'mining equipment', 'oil field equipment', 'fork trucks', 'construction equipment', 'floors'],
        compatible_surfaces: ['steel', 'painted metal', 'industrial surfaces'],
        not_suitable_for: ['aluminium', 'polished aluminium', 'magnesium', 'galvanised metals'],
        available_sizes: ['5L', '25L', '200L Drum', '1000L IBC'],
        sort_order: 40
      },
      {
        slug: 'ready-clean-de782',
        name: 'Ready Clean DE-782',
        code: 'DE-782',
        category: 'degreaser',
        tagline: 'High-foaming pre-spray degreaser with exclusive corrosion inhibitor.',
        description: 'Contains the newest blend of soil-penetrating surfactants, solvents and water-softening agents for highly efficient cleaning. High-foaming — ideal as a pre-spray or through the pressure washer. Effective in cold or hot water. Penetrates and removes the toughest soils including oil, carbon, and road film. Contains an exclusive corrosion inhibitor package to protect equipment.',
        featured: false,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['trucks', 'drilling rigs', 'mining equipment', 'off-road equipment', 'tractor-trailers'],
        compatible_surfaces: ['painted metal', 'steel'],
        not_suitable_for: [],
        available_sizes: ['5L', '25L', '200L Drum'],
        sort_order: 50
      },
      {
        slug: 'farm-soap-tr440',
        name: 'Farm Soap TR-440',
        code: 'TR-440',
        category: 'farm-ag',
        tagline: 'Revolutionary Ag cleaner — removes oxidation and restores painted surfaces.',
        description: 'A highly concentrated non-corrosive detergent containing a special blend of alkaline builders, surfactants, natural citrus and water-softening agents. Farm Soap TR-440 actually removes the micro-layers of faded oxidised paint on metal equipment, making this a permanent change and keeping equipment looking like new. The top-selling chemical in the Alkota Ag range.',
        featured: true,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['tractors', 'agricultural machinery', 'farm equipment', 'painted metal surfaces'],
        compatible_surfaces: ['painted metal', 'steel', 'aluminium'],
        not_suitable_for: [],
        available_sizes: ['5L', '25L', '200L Drum', '1000L IBC'],
        sort_order: 100
      },
      {
        slug: 'raptor-tr428',
        name: 'Raptor TR-428',
        code: 'TR-428',
        category: 'farm-ag',
        tagline: 'Biodegradable industrial detergent — safe on food surfaces.',
        description: 'A biodegradable industrial detergent for use on industrial equipment, heavy off-road equipment, tractors, and more. Contains a natural citrus package. Safe to use on food surfaces followed by a thorough potable water rinse. Safe on stainless steel, aluminium, metals and painted surfaces when used as directed. Free-rinsing surfactant package.',
        featured: false,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['agricultural equipment', 'off-road equipment', 'tractors', 'food surfaces (rinse after)'],
        compatible_surfaces: ['stainless steel', 'aluminium', 'painted metal'],
        not_suitable_for: [],
        available_sizes: ['5L', '25L', '200L Drum'],
        sort_order: 110
      },
      {
        slug: 'power-blast-tr407',
        name: 'Power Blast TR-407',
        code: 'TR-407',
        category: 'transportation-fleet',
        tagline: 'Completely biodegradable alkaline vehicle wash.',
        description: 'A completely biodegradable alkaline detergent. Very versatile — safe on cars, trucks, SUVs, recreational vehicles, and commercial fleet. Removes road film, bugs, and general grime efficiently. The go-to starting-point fleet wash for operators who need a safe, reliable result across mixed vehicle fleets.',
        featured: true,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['HGVs', 'fleet vehicles', 'cars', 'vans', 'buses', 'agricultural vehicles'],
        compatible_surfaces: ['painted surfaces', 'glass', 'rubber', 'trim'],
        not_suitable_for: [],
        available_sizes: ['5L', '25L', '200L Drum', '1000L IBC'],
        sort_order: 200
      },
      {
        slug: 'rigcleaner-tr420',
        name: 'Rigcleaner TR-420',
        code: 'TR-420',
        category: 'transportation-fleet',
        tagline: 'Powder vehicle cleaner — restores and renews faded paintwork.',
        description: 'A completely biodegradable, mild alkaline general-purpose powder detergent. Restores and renews faded and oxidised painted surfaces. Safe for use on aluminium and polished aluminium when used as directed. Works well in food process areas. Quick-release, environmentally green. Ideally suited for use with oily water separators and recycling systems.',
        featured: false,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['trucks', 'vehicles', 'food processing vehicles', 'fleet'],
        compatible_surfaces: ['painted metal', 'aluminium', 'polished aluminium'],
        not_suitable_for: [],
        available_sizes: ['5L', '25L', '200L Drum'],
        sort_order: 210
      },
      {
        slug: 'xtreme-tr422',
        name: 'Xtreme TR-422',
        code: 'TR-422',
        category: 'transportation-fleet',
        tagline: 'Natural citrus truck wash with heavy rust and corrosion inhibitors.',
        description: 'A readily biodegradable industrial car and truck wash with natural citrus degreasing action. Heavy blend of rust and corrosion inhibitors — safe on most painted surfaces, cars, trucks, RVs, and watercraft when used as directed. Loosens grime quickly and rinses easily. Ideally suited for oily water separators and detergent recycling systems.',
        featured: true,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['HGVs', 'fleet vehicles', 'cars', 'vans', 'watercraft'],
        compatible_surfaces: ['painted surfaces', 'aluminium', 'polished aluminium', 'glass'],
        not_suitable_for: [],
        available_sizes: ['5L', '25L', '200L Drum', '1000L IBC'],
        sort_order: 220
      },
      {
        slug: 'touchless-tr470',
        name: 'Touchless TR-470',
        code: 'TR-470',
        category: 'transportation-fleet',
        tagline: 'Touchless vehicle wash — road film and bugs, zero surface damage.',
        description: 'A powerful, completely biodegradable liquid vehicle wash. Mild alkaline formula — safe for aluminium, trim, and non-painted surfaces that corrosive detergents would damage. Designed specifically to remove road film and bugs. Works across trucks, RVs, watercraft, and off-road equipment. Protects trim from rust and corrosion.',
        featured: false,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['trucks', 'RVs', 'watercraft', 'off-road equipment', 'aluminium vehicles'],
        compatible_surfaces: ['painted surfaces', 'polished aluminium', 'aluminium', 'trim'],
        not_suitable_for: [],
        available_sizes: ['5L', '25L', '200L Drum'],
        sort_order: 230
      },
      {
        slug: 'super-luster-tr600',
        name: 'Super Luster TR-600',
        code: 'TR-600',
        category: 'transportation-fleet',
        tagline: 'Heavy-duty truck wash — streak-free shine on tankers and stainless.',
        description: 'A super heavy-duty industrial transportation cleaner designed for truck wash applications. Formulated with sodium hydroxide, natural citrus degreasers, alcohols and butyl to tackle the toughest degreasing while leaving a streak-free shine. Used on stainless tankers, trucks, garbage trucks, mining equipment, logging and oil field equipment. Removes smoke, carbon, greases, oils, and built-up road film.',
        featured: true,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['stainless tankers', 'HGVs', 'garbage trucks', 'mining equipment', 'logging equipment'],
        compatible_surfaces: ['stainless steel', 'painted metal', 'steel'],
        not_suitable_for: ['aluminium', 'polished aluminium', 'magnesium', 'galvanised metals'],
        available_sizes: ['5L', '25L', '200L Drum', '1000L IBC'],
        sort_order: 240
      },
      {
        slug: 'power-blast-2-ts608',
        name: 'Power Blast 2 TS-608',
        code: 'TS-608',
        category: 'heavy-industrial',
        tagline: 'Extreme-duty industrial detergent — the heaviest soil problems solved.',
        description: 'An extremely heavy duty industrial detergent for the toughest soil problems. Effective on engines, fifth-wheels, off-road equipment, garbage trucks, dumpsters, livestock trailers, rendering trucks, and construction equipment. Contains 17% active ingredients at pH 12.4. Anti-scale system protects coils. HAZARDOUS — Corrosive Liquid. NOT for use on aluminium, polished aluminium, magnesium or galvanised metals.',
        featured: true,
        active: true,
        biodegradable: false,
        hazardous: true,
        use_cases: ['engines', 'off-road equipment', 'garbage trucks', 'construction equipment', 'rendering trucks'],
        compatible_surfaces: ['steel', 'painted metal'],
        not_suitable_for: ['aluminium', 'polished aluminium', 'magnesium', 'galvanised metals', 'cars and regular vehicles'],
        available_sizes: ['5L', '25L', '200L Drum'],
        sort_order: 300
      },
      {
        slug: 'power-blast-3-sd926',
        name: 'Power Blast 3 SD-926',
        code: 'SD-926',
        category: 'heavy-industrial',
        tagline: 'Caustic cleaner for carbon build-up — cooking hoods, fryers, paper mills.',
        description: 'A heavy-duty caustic cleaner for the toughest cleaning applications. Most effective for cooking hoods, deep fat fryers, grills and restaurant cooking equipment. Great for cleaning dryers in paper mills, screens in corn milling, and other heavy carbon build-ups. Undiluted, it can strip paint and polyester powder coatings. HAZARDOUS — handle with full PPE.',
        featured: false,
        active: true,
        biodegradable: false,
        hazardous: true,
        use_cases: ['cooking hoods', 'deep fat fryers', 'grills', 'paper mill dryers', 'corn mill screens'],
        compatible_surfaces: ['stainless steel', 'steel'],
        not_suitable_for: ['aluminium', 'painted surfaces'],
        available_sizes: ['5L', '25L'],
        sort_order: 310
      },
      {
        slug: 'scale-stop-coil-protector',
        name: 'Scale Stop Coil Protector',
        code: 'Scale Stop',
        category: 'scale-stop',
        tagline: 'Protect your coil investment — scale prevention in hard water areas.',
        description: 'The UK has some of the hardest water in Europe. Hard water scale is the single biggest cause of premature coil failure in hot water pressure washers. Scale Stop is Hydrus Detergents\' purpose-formulated coil protection additive — used with every wash cycle in hard water areas, it prevents scale accumulation that destroys coils and pumps. An essential monthly operating cost that protects a significant capital investment. Pairs with every Alkota hot water machine.',
        featured: true,
        active: true,
        biodegradable: true,
        hazardous: false,
        use_cases: ['hot water pressure washer coils', 'pumps', 'high pressure components'],
        compatible_surfaces: ['internal machine components'],
        not_suitable_for: [],
        available_sizes: ['5L', '25L'],
        sort_order: 400
      }
    ];

    // Delete existing chemicals
    await supabaseAdmin.from('chemicals').delete().neq('id', '00000000-0000-0000-0000-000000000000');

    // Insert chemicals
    const { error: cError } = await supabaseAdmin.from('chemicals').insert(chemicalsToSeed);
    if (cError) throw new Error(`Chemicals insertion failed: ${cError.message}`);

    // 3. Seed Bespoke Builds
    const bespokeToSeed = [
      {
        slug: 'standard-trailer-single-axle',
        name: 'Single-Axle Mobile Wash Trailer',
        build_type: 'trailer',
        tagline: 'Road-legal, wash-ready. Your mobile cleaning operation starts here.',
        description: 'Our single-axle bespoke trailer builds are designed around your pressure washer specification, your water supply needs, and your industry. Every trailer is engineered from the ground up by our UK team — not a standard unit with a machine bolted on. Full VTA/IVA road compliance, baffled water tanks up to 1,000L, integrated fuel tanks, dual hose reels, and tool storage. Available with hot or cold water machines, steam output, or combinations of both. GVW from 750kg to 1,500kg. We design, specify, and build to your exact brief.',
        featured: true,
        active: true,
        industries: ['fleet-transport', 'oil-gas', 'agriculture', 'local-authorities', 'plant-hire', 'construction'],
        spec_highlights: [
          { label: 'GVW Range', value: '750kg – 1,500kg' },
          { label: 'Water Tank', value: 'Up to 1,000L baffled onboard tank' },
          { label: 'Road Compliance', value: 'Full UK VTA / IVA compliant' },
          { label: 'Hose Reels', value: 'Up to 2 × 50m reels' },
          { label: 'Power Options', value: 'Hot water, cold water, or steam' },
          { label: 'Build Time', value: 'Typically 4–8 weeks from sign-off' }
        ],
        sort_order: 10
      },
      {
        slug: 'standard-trailer-tandem-axle',
        name: 'Tandem-Axle Heavy-Duty Wash Trailer',
        build_type: 'trailer',
        tagline: 'Multi-crew. Multi-machine. Maximum mobile capability.',
        description: 'Our tandem-axle builds are for operations that need serious mobile washing power — multiple machines, large water reserves, generator systems, and heavy-duty deployment capability. Built on tandem axle platforms from 1,500kg to 3,500kg GVW, these rigs carry everything a contract cleaning or emergency response team needs on a single road-legal trailer. Fully custom — every tandem build starts with a conversation about your operation.',
        featured: true,
        active: true,
        industries: ['oil-gas', 'fleet-transport', 'local-authorities', 'construction', 'waste-management', 'mining'],
        spec_highlights: [
          { label: 'GVW Range', value: '1,500kg – 3,500kg' },
          { label: 'Water Tank', value: 'Up to 2,091L baffled onboard tank' },
          { label: 'Road Compliance', value: 'Full UK VTA / IVA compliant' },
          { label: 'Machine Capacity', value: 'Dual machine configuration available' },
          { label: 'Generator', value: 'Silent onboard generator option' },
          { label: 'Hose Reels', value: 'Up to 4 × 100m reels' },
          { label: 'Lighting', value: 'Full site work lighting package' }
        ],
        sort_order: 20
      },
      {
        slug: 'wash-plant-mat-access-panel',
        name: 'Automated Mat & Access Panel Wash Plant',
        build_type: 'wash-plant',
        tagline: '360° automated wash. A 14ft rig mat cleaned in under 4 minutes.',
        description: 'The Alkota Wash Plant is a patent-pending 360° automated conveyor cleaning system for rig mats, access panels, and large-format industrial matting. Purpose-built for the oil & gas, construction, and plant hire industries where mat cleaning is a significant operational cost and environmental compliance obligation. The system passes mats through a wash station built over an automated variable-speed conveyor. 20 rotating cleaning arms deliver 40 GPM at 4,000 PSI to the top, bottom, and sides simultaneously — more cleaning power in 4 minutes than a single operator in 45. On-demand hot water from dual one-million BTU heaters. Closed-loop water recycling reduces water consumption by over 250 gallons per mat compared to manual methods — eliminating water hauling and disposal costs entirely. Optional chlorination system for invasive species compliance.',
        featured: true,
        active: true,
        industries: ['oil-gas', 'construction', 'plant-hire', 'mining'],
        spec_highlights: [
          { label: 'Cleaning Speed', value: '14ft mat in under 4 minutes' },
          { label: 'Pump Output', value: '40 GPM at 4,000 PSI' },
          { label: 'Cleaning Arms', value: '20 rotating nozzle arms — 360° coverage' },
          { label: 'Hot Water', value: 'Dual 1,000,000 BTU heaters — up to 135°F rise' },
          { label: 'Conveyor Speed', value: 'Variable — up to 20 linear ft/min (5HP Servo Motor)' },
          { label: 'Max Mat Thickness', value: '12 inches — height adjustable wash station' },
          { label: 'Max Mat Length', value: 'Standard 20ft — extended tables for 40ft mats' },
          { label: 'Water Recycling', value: 'Closed-loop — saves 250+ gallons per mat' },
          { label: 'Filtration', value: 'Down to 20 micron — auto backwash media filters' },
          { label: 'Chlorination', value: 'Optional — dilution-controlled chlorine system' },
          { label: 'Compliance', value: 'Meets EA wash water discharge regulations' }
        ],
        sort_order: 30
      },
      {
        slug: 'skid-unit-custom',
        name: 'Custom Skid-Mount Pressure Washing Unit',
        build_type: 'skid-unit',
        tagline: 'Permanent skid integration — for vehicles, flatbeds, and fixed plant.',
        description: 'Custom skid-mount units are designed for permanent integration onto service vehicles, flatbed trucks, offshore containers, and fixed plant installations. Each skid is engineered to the exact footprint and power supply of the intended platform. Available with hot or cold water machines, steam output, water tanks, generator systems, and any combination of ancillary equipment. UK ATEX zone compliance available for hazardous area applications.',
        featured: false,
        active: true,
        industries: ['oil-gas', 'fleet-transport', 'mining', 'manufacturing'],
        spec_highlights: [
          { label: 'Mounting', value: 'Vehicle, flatbed, container, or static' },
          { label: 'Power', value: 'Mains, generator, or engine driven' },
          { label: 'ATEX', value: 'Zone 1 / Zone 2 hazardous area versions available' },
          { label: 'Output', value: 'Hot water, cold water, steam, or combination' }
        ],
        sort_order: 40
      }
    ];

    // Delete existing bespoke builds
    await supabaseAdmin.from('bespoke_builds').delete().neq('id', '00000000-0000-0000-0000-000000000000');

    // Insert bespoke builds
    const { error: bError } = await supabaseAdmin.from('bespoke_builds').insert(bespokeToSeed);
    if (bError) throw new Error(`Bespoke builds insertion failed: ${bError.message}`);

    return NextResponse.json({ success: true, message: 'All tables successfully seeded!' });
  } catch (error: any) {
    return NextResponse.json({ error: true, message: error.message }, { status: 500 });
  }
}
