import { Part } from '@/lib/types/parts';

export const PARTS_CATALOGUE_V2: Omit<Part, 'id' | 'created_at' | 'updated_at'>[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // 1. ALKOTA OEM GENUINE PARTS (brand: 'alkota')
  // ═══════════════════════════════════════════════════════════════════════════

  // --- Pumps & Plungers ---
  {
    part_number: '20-001',
    name: 'General Pump TS2021 Triplex Plunger Pump',
    slug: 'general-pump-ts2021',
    description: 'The benchmark triplex plunger pump used across Alkota heavy-duty hot and cold water pressure washers. Features forged brass manifold, solid ceramic plungers, unitised stainless steel inlet/discharge valves, and heavy die-cast anodised aluminium crankcase.',
    category: 'pumps',
    brand: 'alkota',
    manufacturer: 'General Pump / Alkota OEM',
    price: 645.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 14.5,
    technical_notes: 'Rated for 5.6 GPM (21.2 LPM) @ 3500 PSI (240 BAR) at 1450 RPM. Requires 1.1L 30W Non-Detergent Pump Oil.',
    compatible_machines: ['420X4', '430XH4', '4358', '216X4', 'TRAILER-SINGLE'],
    image_url: '/assets/products/pump-ts2021.png',
    oem_genuine: true,
    featured: true,
    is_attachment: false,
    tags: ['pump', 'triplex', 'ts2021', 'general pump', 'plunger'],
    active: true,
    sort_order: 10
  },
  {
    part_number: '20-002',
    name: 'General Pump TS2031 Triplex Plunger Pump',
    slug: 'general-pump-ts2031',
    description: 'Heavy continuous-duty triplex plunger pump designed for higher flow requirements in commercial plant wash bays. Solid ceramic plungers and oversize tapered roller bearings.',
    category: 'pumps',
    brand: 'alkota',
    manufacturer: 'General Pump / Alkota OEM',
    price: 725.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 15.0,
    technical_notes: 'Rated for 8.0 GPM (30.3 LPM) @ 2500 PSI (175 BAR) at 1450 RPM.',
    compatible_machines: ['8305A', '8358', 'TRAILER-TANDEM'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['pump', 'triplex', 'ts2031', 'high flow'],
    active: true,
    sort_order: 15
  },
  {
    part_number: '20-010',
    name: 'Cat Pump 5CP2120W Industrial Plunger Pump',
    slug: 'cat-pump-5cp2120w',
    description: 'High-temperature industrial triplex pump with special blend high-pressure seals, concentric solid ceramic plungers, and 316 stainless steel valve seats for severe continuous-duty wash bay service.',
    category: 'pumps',
    brand: 'alkota',
    manufacturer: 'Cat Pumps / Alkota OEM',
    price: 890.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 16.2,
    technical_notes: 'Rated for 4.0 GPM (15.1 LPM) @ 2500 PSI at 950 RPM. Safe for inlet water temperatures up to 70°C.',
    compatible_machines: ['31105', '5305A', 'DED-SERIES'],
    image_url: null,
    oem_genuine: true,
    featured: true,
    is_attachment: false,
    tags: ['pump', 'cat pump', 'high temperature', '5cp'],
    active: true,
    sort_order: 20
  },
  {
    part_number: '20-015',
    name: 'AR RKV4G40 Direct-Drive Plunger Pump',
    slug: 'ar-rkv4g40',
    description: 'Compact high-pressure direct-drive triplex plunger pump designed for engine-driven mobile power wash packages.',
    category: 'pumps',
    brand: 'alkota',
    manufacturer: 'AR North America / Alkota OEM',
    price: 580.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 9.8,
    technical_notes: 'Rated for 4.0 GPM @ 4000 PSI at 3400 RPM with 1" hollow shaft.',
    compatible_machines: ['GED-12V', '4305XD4'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['pump', 'direct drive', 'annovi reverberi'],
    active: true,
    sort_order: 25
  },
  {
    part_number: '21-001',
    name: 'General Pump TS2021 Complete Packing Seal Kit',
    slug: 'ts2021-packing-seal-kit',
    description: 'OEM replacement seal kit for TS2021 pump. Contains high and low pressure V-packings, brass support rings, and O-rings for complete 3-cylinder service.',
    category: 'seals-o-rings',
    brand: 'alkota',
    manufacturer: 'General Pump / Alkota OEM',
    price: 34.50,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.25,
    technical_notes: 'Includes 3x high pressure packings (90.2705.00) and 3x low pressure packings (90.2703.00).',
    compatible_machines: ['420X4', '430XH4', '4358'],
    image_url: null,
    oem_genuine: true,
    featured: true,
    is_attachment: false,
    tags: ['seals', 'packings', 'ts2021', 'rebuild'],
    active: true,
    sort_order: 30
  },
  {
    part_number: '21-010',
    name: 'TS2021 Solid Ceramic Plunger Cylinder (Pack of 3)',
    slug: 'ts2021-ceramic-plungers-pack-3',
    description: 'Set of 3 precision-ground solid ceramic plungers. Resists thermal shock, chemical corrosion, and abrasive wear.',
    category: 'pumps',
    brand: 'alkota',
    manufacturer: 'General Pump / Alkota OEM',
    price: 68.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.45,
    technical_notes: '20mm diameter. Includes copper sealing washers and stainless plunger bolts.',
    compatible_machines: ['420X4', '430XH4', '4358'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['ceramic', 'plungers', 'ts2021'],
    active: true,
    sort_order: 35
  },

  // --- Burner & Ignition ---
  {
    part_number: '30-101',
    name: 'Beckett AFG Industrial Diesel Burner Assembly',
    slug: 'beckett-afg-burner-assembly',
    description: 'Factory original Beckett AFG oil burner engineered specifically for Alkota vertical Schedule 80 combustion chambers. Features solid-state electronic ignitor, CleanCut fuel pump with solenoid shut-off, and high-velocity blower wheel.',
    category: 'burners',
    brand: 'alkota',
    manufacturer: 'Beckett / Alkota OEM',
    price: 495.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 12.0,
    technical_notes: '230V 50Hz single phase. Firing rate 0.50 to 3.00 GPH. 385,000 BTU maximum input.',
    compatible_machines: ['420X4', '430XH4', '4358', '5305A'],
    image_url: null,
    oem_genuine: true,
    featured: true,
    is_attachment: false,
    tags: ['burner', 'beckett', 'afg', 'combustion', 'diesel'],
    active: true,
    sort_order: 40
  },
  {
    part_number: '30-105',
    name: 'Beckett Solid-State Electronic Ignition Transformer (240V)',
    slug: 'beckett-ignition-transformer-240v',
    description: 'High-voltage electronic ignitor for rapid, continuous spark across burner electrodes. Sealed moisture-resistant epoxy casing.',
    category: 'burners',
    brand: 'alkota',
    manufacturer: 'Beckett / Alkota OEM',
    price: 85.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.85,
    technical_notes: 'Primary: 240V AC 50Hz. Secondary: 20kV peak continuous spark.',
    compatible_machines: ['420X4', '430XH4', '4358', '216X4'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['ignitor', 'transformer', 'beckett', '240v'],
    active: true,
    sort_order: 45
  },
  {
    part_number: '30-110',
    name: 'Alkota Burner Ignition Electrode Pair with Lead Wires',
    slug: 'alkota-burner-electrode-pair',
    description: 'Matched pair of high-alumina glazed ceramic ignition electrodes with stainless spark rods and silicone high-tension insulated lead wires.',
    category: 'burners',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: 18.50,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.15,
    technical_notes: 'Pre-gapped to 3.2mm spark distance. Factory replacement for Beckett burner chassis.',
    compatible_machines: ['420X4', '430XH4', '4358', '216X4', '5305A'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['electrodes', 'spark rods', 'ignition'],
    active: true,
    sort_order: 50
  },
  {
    part_number: '30-120',
    name: 'Suntec A2VA Fuel Pump with 240V Solenoid Shut-Off',
    slug: 'suntec-a2va-fuel-pump',
    description: 'Single-stage oil burner fuel pump with integral pressure regulator and instantaneous 240V solenoid cut-off valve to prevent burner smoking on shutdown.',
    category: 'burners',
    brand: 'alkota',
    manufacturer: 'Suntec / Alkota Approved',
    price: 125.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 1.8,
    technical_notes: 'Rated up to 200 PSI operating pressure at 2850 RPM. 1/8" NPT nozzle port.',
    compatible_machines: ['420X4', '430XH4', '4358', '5305A'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['fuel pump', 'suntec', 'solenoid', 'burner'],
    active: true,
    sort_order: 55
  },
  {
    part_number: '31-015',
    name: 'Delavan 1.50 GPH 80°A Solid Cone Oil Burner Nozzle',
    slug: 'delavan-1-50-gph-80a-burner-nozzle',
    description: 'Precision sintered-filter atomising oil burner nozzle. Produces uniform hollow-cone spray pattern for complete clean combustion in Alkota heating coils.',
    category: 'burners',
    brand: 'alkota',
    manufacturer: 'Delavan / Alkota OEM',
    price: 8.50,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.05,
    technical_notes: '1.50 GPH at 100 PSI fuel pressure with 80° spray angle.',
    compatible_machines: ['420X4', '430XH4'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['nozzle', 'burner nozzle', 'delavan', '1.50 gph'],
    active: true,
    sort_order: 60
  },
  {
    part_number: '31-020',
    name: 'Delavan 2.00 GPH 80°B Solid Cone Oil Burner Nozzle',
    slug: 'delavan-2-00-gph-80b-burner-nozzle',
    description: 'Precision solid-cone oil atomising nozzle for high-BTU Alkota 4358 and XH4 series hot water pressure washers.',
    category: 'burners',
    brand: 'alkota',
    manufacturer: 'Delavan / Alkota OEM',
    price: 8.50,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.05,
    technical_notes: '2.00 GPH at 100 PSI with 80° solid cone distribution.',
    compatible_machines: ['4358', '5305A', '8305A'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['nozzle', 'delavan', '2.00 gph', 'high btu'],
    active: true,
    sort_order: 65
  },

  // --- Heating Coils & Insulation ---
  {
    part_number: '40-200',
    name: 'Alkota Schedule 80 ASTM A53 Heating Coil — 200/300 Series',
    slug: 'alkota-schedule-80-coil-200-series',
    description: 'Continuous-wound Schedule 80 ASTM A53 carbon steel heating coil. Hydrostatically tested to 10,000 PSI. Uniquely engineered with cold-rolled continuous spiral geometry for maximum heat transfer and zero weld seam fatigue.',
    category: 'coils',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: null, // POA
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 58.0,
    technical_notes: 'Standard fit on Alkota 216X4, 31105, and 420X4. Backed by Alkota 7-Year Coil Prorated Warranty.',
    compatible_machines: ['216X4', '31105', '420X4'],
    image_url: null,
    oem_genuine: true,
    featured: true,
    is_attachment: false,
    tags: ['heating coil', 'schedule 80', 'astm a53', '7 year warranty'],
    active: true,
    sort_order: 70
  },
  {
    part_number: '40-400',
    name: 'Alkota Schedule 80 ASTM A53 Heating Coil — 4000/XH4 Series',
    slug: 'alkota-schedule-80-coil-4000-series',
    description: 'Heavy industrial Schedule 80 continuous spiral coil with extended heating surface area for high-volume commercial wash bays and dual-gun installations.',
    category: 'coils',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: null, // POA
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 74.0,
    technical_notes: '3/4" Schedule 80 heavy wall pipe. Hydro-tested to 12,000 PSI.',
    compatible_machines: ['430XH4', '4358', '5305A'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['heating coil', 'xh4', '4000 series', 'heavy wall'],
    active: true,
    sort_order: 75
  },
  {
    part_number: '41-010',
    name: 'Alkota High-Density Ceramic Bottom Insulation Disc',
    slug: 'alkota-ceramic-bottom-disc',
    description: 'Pre-molded ceramic fiber refractory bottom pan disc. Withstands direct flame exposure up to 1260°C and prevents heat transfer to machine chassis.',
    category: 'coils',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: 24.50,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 2.2,
    technical_notes: '16" diameter x 1.5" thick. Fits all standard Alkota vertical combustion chambers.',
    compatible_machines: ['216X4', '420X4', '430XH4', '4358'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['insulation', 'refractory', 'ceramic disc'],
    active: true,
    sort_order: 80
  },

  // --- Trigger Guns & Spray Handles ---
  {
    part_number: '10-151',
    name: 'Alkota Easy-Pull Industrial Trigger Gun',
    slug: 'alkota-easy-pull-gun-10151',
    description: 'Proprietary fatigue-reducing trigger gun designed specifically for 8-hour commercial wash shifts. Features light trigger hold-open force, impact-resistant composite housing, and stainless steel ball and seat.',
    category: 'trigger-guns',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine Equipment',
    price: 78.50,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.95,
    technical_notes: 'Rated up to 5000 PSI (345 BAR), 12 GPM (45 LPM), and 150°C. 3/8" FPT inlet, 1/4" FPT outlet.',
    compatible_machines: ['420X4', '430XH4', '4358', '216X4', '31105', '5305A'],
    image_url: '/assets/products/easy-pull-gun.png',
    oem_genuine: true,
    featured: true,
    is_attachment: false,
    tags: ['trigger gun', 'easy-pull', 'spray handle', '5000 psi'],
    active: true,
    sort_order: 85
  },
  {
    part_number: '10-152',
    name: 'Suttner ST-1500 Industrial High-Pressure Spray Gun',
    slug: 'suttner-st1500-spray-gun',
    description: 'Industry benchmark linear trigger gun built with solid forged brass body, stainless valve needle, and unitised trigger lock mechanism.',
    category: 'trigger-guns',
    brand: 'alkota',
    manufacturer: 'Suttner / Alkota Approved',
    price: 64.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.85,
    technical_notes: 'Rated 4000 PSI (275 BAR) @ 10.5 GPM, 150°C.',
    compatible_machines: ['420X4', '430XH4', '4358'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['suttner', 'st-1500', 'spray gun'],
    active: true,
    sort_order: 90
  },
  {
    part_number: '10-162',
    name: 'Alkota Steam Dump Gun Assembly (140°C Saturated Steam)',
    slug: 'alkota-steam-dump-gun-10162',
    description: 'Specialised open-circuit steam dump gun for saturated dry vapour steam units. Diverts flow on trigger release to prevent thermal coil overpressure.',
    category: 'trigger-guns',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine Equipment',
    price: 95.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 1.1,
    technical_notes: 'Rated for 160°C dry steam service up to 300 PSI.',
    compatible_machines: ['STEAM-OIL', 'STEAM-GAS'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['steam gun', 'dump gun', 'vapour'],
    active: true,
    sort_order: 95
  },

  // --- High-Pressure Hoses ---
  {
    part_number: '12-101',
    name: '10m 3/8" Single-Wire Braided High-Pressure Hose (300 BAR)',
    slug: '10m-3-8-300bar-hose',
    description: 'High-tensile steel wire braided pressure hose with oil-resistant synthetic rubber core and abrasion-resistant outer jacket. Includes heavy-duty molded bend restrictors.',
    category: 'hoses',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: 65.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 3.2,
    technical_notes: 'Rated 4000 PSI (300 BAR) @ 120°C. 3/8" MPT solid x 3/8" MPT swivel fittings.',
    compatible_machines: ['420X4', '430XH4', '216X4', '4305XD4'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['hose', '10m', '300 bar', 'high pressure'],
    active: true,
    sort_order: 100
  },
  {
    part_number: '12-102',
    name: '20m 3/8" Double-Wire Braided Extreme-Duty Hose (400 BAR)',
    slug: '20m-3-8-400bar-hose',
    description: 'Double steel braided wire hose for heavy commercial contractors. Maximum kink resistance and burst protection for yard work.',
    category: 'hoses',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: 105.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 6.8,
    technical_notes: 'Rated 6000 PSI (400 BAR) @ 150°C. Wrapped abrasion cover.',
    compatible_machines: ['430XH4', '4358', '5305A', 'TRAILER-SINGLE'],
    image_url: null,
    oem_genuine: true,
    featured: true,
    is_attachment: false,
    tags: ['hose', '20m', 'double wire', '400 bar'],
    active: true,
    sort_order: 105
  },
  {
    part_number: '12-105',
    name: '15m 3/8" Non-Marking Gray Commercial Wash Hose',
    slug: '15m-3-8-non-marking-gray-hose',
    description: 'Special non-marking gray rubber jacket designed specifically for food processing plants, vehicle showrooms, and concrete forecourts where black marks are prohibited.',
    category: 'hoses',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: 115.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 4.8,
    technical_notes: 'Rated 4000 PSI @ 120°C. Non-marking outer rubber cover.',
    compatible_machines: ['420X4', '430XH4', '31105'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['hose', 'non-marking', 'gray hose', 'food processing'],
    active: true,
    sort_order: 110
  },

  // --- Lances & Nozzles ---
  {
    part_number: '14-048',
    name: '1000mm Insulated Molded Grip Stainless Steel Lance',
    slug: '1000mm-insulated-molded-lance',
    description: 'Seamless 316 stainless steel high-pressure wand with ergonomic ribbed thermal grip for operator heat protection during continuous hot water washing.',
    category: 'lances-nozzles',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: 34.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.9,
    technical_notes: '1/4" MPT inlet x 1/4" FPT nozzle holder. Rated 5000 PSI @ 150°C.',
    compatible_machines: ['420X4', '430XH4', '4358', '216X4'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['lance', 'wand', 'insulated', '1000mm'],
    active: true,
    sort_order: 115
  },
  {
    part_number: '15-004',
    name: 'Alkota QC Color-Coded Stainless Nozzle 4-Pack (Size 04)',
    slug: 'alkota-qc-nozzle-4-pack-size-04',
    description: 'Set of 4 hardened stainless steel quick-connect tips: Red (0° blasting), Yellow (15° stripping), Green (25° washing), White (40° rinsing).',
    category: 'lances-nozzles',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: 22.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.15,
    technical_notes: 'Size 04 orifice matched for 3.5 to 4.5 GPM machines.',
    compatible_machines: ['420X4', '430XH4', '4305XD4'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['nozzles', 'quick connect', 'spray tips', 'size 04'],
    active: true,
    sort_order: 120
  },
  {
    part_number: '15-040',
    name: 'Suttner ST-357 Rotating Turbo Jet Nozzle (Size 04)',
    slug: 'suttner-st357-turbo-nozzle-04',
    description: 'High-RPM zero-degree rotating pencil jet that combines the aggressive impact of a 0° blast with the wide coverage of a 25° fan.',
    category: 'lances-nozzles',
    brand: 'alkota',
    manufacturer: 'Suttner / Alkota Approved',
    price: 48.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.35,
    technical_notes: 'Rated up to 3600 PSI @ 100°C. Ceramic seat and rotor.',
    compatible_machines: ['420X4', '430XH4', '216X4'],
    image_url: null,
    oem_genuine: true,
    featured: true,
    is_attachment: true,
    tags: ['turbo nozzle', 'rotary jet', 'suttner', 'concrete stripping'],
    active: true,
    sort_order: 125
  },

  // --- Unloader Valves & Hydraulics ---
  {
    part_number: '50-001',
    name: 'VRT3-310 Trapped-Pressure Unloader Valve with Microswitch',
    slug: 'vrt3-unloader-valve',
    description: 'Heavy forged brass unloader valve with internal bypass and electric microswitch for automatic timed total-stop burner/motor shutdown.',
    category: 'valves-unloaders',
    brand: 'alkota',
    manufacturer: 'PA SpA / Alkota Approved',
    price: 68.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 1.1,
    technical_notes: 'Rated 4500 PSI (310 BAR) @ 10.5 GPM, 90°C. 3/8" BSP inlet/outlet.',
    compatible_machines: ['420X4', '430XH4', '4358'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['unloader', 'vrt3', 'pressure regulator', 'bypass'],
    active: true,
    sort_order: 130
  },
  {
    part_number: '50-020',
    name: 'Alkota High-Pressure Safety Burst Disc 5000 PSI',
    slug: 'safety-burst-disc-5000psi',
    description: 'Certified rupture disc safety valve that provides instant positive overpressure relief if the primary unloader valve binds or freezes.',
    category: 'valves-unloaders',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: 32.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.15,
    technical_notes: 'Factory burst preset at 5000 PSI (345 BAR). 1/4" MPT solid hex brass body.',
    compatible_machines: ['420X4', '430XH4', '4358', '5305A'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['burst disc', 'safety relief', 'overpressure'],
    active: true,
    sort_order: 135
  },
  {
    part_number: '50-030',
    name: 'Brass Thermal Relief Valve 60°C (1/2" MPT)',
    slug: 'thermal-relief-valve-60c',
    description: 'Automatic thermal dump valve that opens to eject hot recirculating bypass water before pump packings overheat during closed-gun idling.',
    category: 'valves-unloaders',
    brand: 'alkota',
    manufacturer: 'General Pump / Alkota OEM',
    price: 24.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.1,
    technical_notes: 'Dumps at 60°C (140°F) water temp. Resets automatically upon cool water intake.',
    compatible_machines: ['420X4', '430XH4', '216X4', '4305XD4'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['thermal relief', 'pump protector', 'bypass cooler'],
    active: true,
    sort_order: 140
  },

  // --- Electrical, Switches & Thermostats ---
  {
    part_number: '60-010',
    name: 'Alkota Adjustable Dial Thermostat (0°C – 130°C)',
    slug: 'adjustable-dial-thermostat-0-130c',
    description: 'Precision bulb-and-capillary thermostat with front-panel rotary temperature selector dial. Controls burner ignition solenoid for exact water temperature regulation.',
    category: 'electrical-switches',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: 42.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.3,
    technical_notes: '1500mm stainless capillary with 1/4" NPT immersion well probe. 16A 250V microswitch.',
    compatible_machines: ['420X4', '430XH4', '4358', '216X4', '5305A'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['thermostat', 'temperature control', 'dial'],
    active: true,
    sort_order: 145
  },
  {
    part_number: '60-020',
    name: 'General Pump Magnetic Reed Flow Switch (3/8" MPT)',
    slug: 'gp-magnetic-flow-switch',
    description: 'In-line safety flow switch that prevents burner combustion unless water is actively flowing through the heating coil.',
    category: 'electrical-switches',
    brand: 'alkota',
    manufacturer: 'General Pump / Alkota OEM',
    price: 38.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.4,
    technical_notes: 'Activates at 1.0 GPM minimum flow. Rated up to 4500 PSI.',
    compatible_machines: ['420X4', '430XH4', '4358', '216X4'],
    image_url: null,
    oem_genuine: true,
    featured: false,
    is_attachment: false,
    tags: ['flow switch', 'burner safety', 'reed switch'],
    active: true,
    sort_order: 150
  },

  // --- Scheduled Service Kits ---
  {
    part_number: 'ALK-KIT-200',
    name: 'Alkota 500-Hour / Annual PPM Service Kit — 200 Series',
    slug: 'annual-service-kit-200-series',
    description: 'Complete scheduled maintenance kit containing fuel filter, water strainer mesh, Delavan burner nozzle, ignition electrode pair, pump oil, and high-pressure unloader rebuild O-rings.',
    category: 'service-kits',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: 145.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 2.8,
    technical_notes: 'Recommended for 500-hour or annual preventive service on Alkota 216X4 and 420X4 machines.',
    compatible_machines: ['216X4', '420X4'],
    image_url: null,
    oem_genuine: true,
    featured: true,
    is_attachment: false,
    tags: ['service kit', 'annual maintenance', '200 series', 'ppm'],
    active: true,
    sort_order: 155
  },
  {
    part_number: 'ALK-KIT-4000',
    name: 'Alkota 500-Hour PPM Service Kit — 4000 & XH4 Series',
    slug: 'annual-service-kit-4000-series',
    description: 'Comprehensive commercial maintenance kit including spin-on 10-micron fuel water separator, Viton pump packing seals, 2.0 GPH burner nozzle, burner electrodes, flow switch service kit, and non-detergent pump oil.',
    category: 'service-kits',
    brand: 'alkota',
    manufacturer: 'Alkota Genuine',
    price: 175.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 3.5,
    technical_notes: 'Engineered for high-volume commercial duty Alkota 430XH4 and 4358 models.',
    compatible_machines: ['430XH4', '4358', '5305A'],
    image_url: null,
    oem_genuine: true,
    featured: true,
    is_attachment: false,
    tags: ['service kit', 'xh4', '4000 series', 'ppm', 'viton'],
    active: true,
    sort_order: 160
  },


  // ═══════════════════════════════════════════════════════════════════════════
  // 2. MOSMATIC SWITZERLAND (brand: 'mosmatic')
  // ═══════════════════════════════════════════════════════════════════════════
  {
    part_number: 'MOS-80.751',
    name: 'Mosmatic DL-UHD 46 Heavy-Duty Flat Surface Cleaner (18")',
    slug: 'mosmatic-dl-uhd-46',
    description: 'Swiss-engineered commercial rotary surface cleaner built with 18" heavy-gauge stainless steel deck housing, four stainless caster wheels, high-RPM dual-bearing carbide swivel union, and lance mounting bracket. Eliminates zebra striping on concrete forecourts.',
    category: 'surface-cleaners',
    brand: 'mosmatic',
    manufacturer: 'Mosmatic AG',
    price: 485.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 9.8,
    technical_notes: 'Rated for 500 BAR (7300 PSI) @ 120°C, 30 LPM. 2x 1/8" NPT nozzle ports.',
    compatible_machines: ['420X4', '430XH4', '4358', 'TRAILER-SINGLE'],
    image_url: null,
    oem_genuine: false,
    featured: true,
    is_attachment: true,
    tags: ['mosmatic', 'surface cleaner', 'swiss', 'flat surface', '500 bar'],
    active: true,
    sort_order: 200
  },
  {
    part_number: 'MOS-80.750',
    name: 'Mosmatic DL-UHD 43 Stainless Surface Cleaner (12")',
    slug: 'mosmatic-dl-uhd-43',
    description: 'Compact 12" stainless steel surface cleaner for tight walkways, fuel islands, and commercial kitchen floor sanitisation.',
    category: 'surface-cleaners',
    brand: 'mosmatic',
    manufacturer: 'Mosmatic AG',
    price: 445.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 7.2,
    technical_notes: 'Rated for 500 BAR @ 120°C. Integrated brush ring skirt.',
    compatible_machines: ['420X4', '430XH4'],
    image_url: null,
    oem_genuine: false,
    featured: false,
    is_attachment: true,
    tags: ['mosmatic', 'compact', 'surface cleaner', '12 inch'],
    active: true,
    sort_order: 205
  },
  {
    part_number: 'MOS-80.082',
    name: 'Mosmatic UC-E Stainless Undercarriage Vehicle Wash Rig',
    slug: 'mosmatic-uc-e-undercarriage-cleaner',
    description: 'High-clearance vehicle chassis cleaner with 4x high-velocity rotor arms and low-profile caster wheels. Rolls smoothly under trucks, plant machinery, and council fleets to blast road salt and mud.',
    category: 'surface-cleaners',
    brand: 'mosmatic',
    manufacturer: 'Mosmatic AG',
    price: 385.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 8.5,
    technical_notes: 'Rated 275 BAR @ 120°C. Ground clearance 140mm.',
    compatible_machines: ['420X4', '430XH4', '4358', 'TRAILER-SINGLE'],
    image_url: null,
    oem_genuine: false,
    featured: true,
    is_attachment: true,
    tags: ['mosmatic', 'undercarriage', 'chassis wash', 'fleet cleaning'],
    active: true,
    sort_order: 210
  },
  {
    part_number: 'MOS-25.050',
    name: 'Mosmatic DGV High-RPM Live Swivel Union (3/8" NPT)',
    slug: 'mosmatic-dgv-live-swivel-3-8',
    description: 'Maintenance-free Swiss stainless steel live swivel union with tungsten-carbide mechanical face seals. Eliminates hose twisting at the spray gun inlet and reduces operator wrist fatigue.',
    category: 'fittings-couplers',
    brand: 'mosmatic',
    manufacturer: 'Mosmatic AG',
    price: 85.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.28,
    technical_notes: 'Rated 500 BAR (7300 PSI) @ 120°C. 30 RPM live rotation under full operating pressure.',
    compatible_machines: ['420X4', '430XH4', '4358', '216X4'],
    image_url: null,
    oem_genuine: false,
    featured: false,
    is_attachment: true,
    tags: ['mosmatic', 'swivel', 'rotary union', 'live swivel'],
    active: true,
    sort_order: 215
  },
  {
    part_number: 'MOS-43.050',
    name: 'Mosmatic WDB High-Pressure 90° Swivel Joint (1/2" NPT)',
    slug: 'mosmatic-wdb-90-swivel-joint',
    description: 'Heavy industrial 90-degree rotary union for high-pressure hose reel fluid paths and ceiling boom wash bay installations.',
    category: 'fittings-couplers',
    brand: 'mosmatic',
    manufacturer: 'Mosmatic AG',
    price: 155.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.65,
    technical_notes: 'Rated 350 BAR @ 120°C. Stainless steel fluid path.',
    compatible_machines: ['TRAILER-SINGLE', 'TRAILER-TANDEM'],
    image_url: null,
    oem_genuine: false,
    featured: false,
    is_attachment: true,
    tags: ['mosmatic', '90 degree', 'hose reel swivel', 'boom'],
    active: true,
    sort_order: 220
  },
  {
    part_number: 'MOS-80.952',
    name: 'Mosmatic TurboKing 6" High-Impact Rotary Jet Head',
    slug: 'mosmatic-turboking-6-rotary-jet',
    description: 'Heavy handheld circular blaster housing a twin-jet high-RPM rotor head for intensive concrete curb, brickwork, and graffiti stripping.',
    category: 'lances-nozzles',
    brand: 'mosmatic',
    manufacturer: 'Mosmatic AG',
    price: 165.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 1.4,
    technical_notes: 'Rated 350 BAR @ 90°C. M22 or 1/4" QC connection.',
    compatible_machines: ['420X4', '430XH4', '4305XD4'],
    image_url: null,
    oem_genuine: false,
    featured: false,
    is_attachment: true,
    tags: ['mosmatic', 'turboking', 'rotary jet', 'graffiti'],
    active: true,
    sort_order: 225
  },
  {
    part_number: 'MOS-FL-M-2.5',
    name: 'Mosmatic Commercial Foam Cannon 2.5L System',
    slug: 'mosmatic-commercial-foam-cannon-2-5l',
    description: 'Industrial high-expansion foam lance with calibrated air induction and stainless mesh aerator. Delivers thick clinging detergent foam for fleet degreasing.',
    category: 'attachments',
    brand: 'mosmatic',
    manufacturer: 'Mosmatic AG',
    price: 125.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 1.2,
    technical_notes: 'Rated 250 BAR @ 60°C. 2.5L chemical bottle with measurement markings.',
    compatible_machines: ['420X4', '430XH4', '216X4'],
    image_url: null,
    oem_genuine: false,
    featured: true,
    is_attachment: true,
    tags: ['mosmatic', 'foam lance', 'chemical cannon', 'fleet foam'],
    active: true,
    sort_order: 230
  },


  // ═══════════════════════════════════════════════════════════════════════════
  // 3. COX REELS USA (brand: 'cox-reels')
  // ═══════════════════════════════════════════════════════════════════════════
  {
    part_number: 'COX-1125-3-100',
    name: 'Cox Reels 1125 Series Hand-Crank Hose Reel (3/8" x 30m)',
    slug: 'cox-reels-1125-3-100',
    description: 'American heavy-duty hand-crank hose reel with one-piece all-welded steel A-frame base, CNC spun disc ribs, proprietary CPC™ blue powder coating, and dual-axle Super Hub™ drum support.',
    category: 'hoses',
    brand: 'cox-reels',
    manufacturer: 'Cox Reels USA',
    price: 285.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 14.5,
    technical_notes: 'Rated 4000 PSI (275 BAR). Holds 30m of 3/8" high-pressure hose. 1/2" NPT inlet swivel.',
    compatible_machines: ['TRAILER-SINGLE', 'TRAILER-TANDEM', 'STATIONARY-SKID'],
    image_url: null,
    oem_genuine: false,
    featured: true,
    is_attachment: true,
    tags: ['cox reels', 'hose reel', 'hand crank', '1125 series', 'usa'],
    active: true,
    sort_order: 300
  },
  {
    part_number: 'COX-1125-3-50',
    name: 'Cox Reels 1125 Compact Hand-Crank Reel (3/8" x 15m)',
    slug: 'cox-reels-1125-3-50',
    description: 'Compact A-frame reel for mobile service vans and tight utility vehicle installs.',
    category: 'hoses',
    brand: 'cox-reels',
    manufacturer: 'Cox Reels USA',
    price: 225.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 11.2,
    technical_notes: 'Rated 4000 PSI. Holds 15m of 3/8" hose.',
    compatible_machines: ['TRAILER-SINGLE', '4305XD4'],
    image_url: null,
    oem_genuine: false,
    featured: false,
    is_attachment: true,
    tags: ['cox reels', 'compact reel', '15m'],
    active: true,
    sort_order: 305
  },
  {
    part_number: 'COX-1175-5-100',
    name: 'Cox Reels 1175 Motorised 12V Electric Rewind Reel (1/2" x 30m)',
    slug: 'cox-reels-1175-5-100-motorised',
    description: 'Electric power-rewind hose reel equipped with heavy-duty 12V DC electric motor, chain and sprocket reduction drive, and push-button control switch for fast single-operator hose recovery.',
    category: 'hoses',
    brand: 'cox-reels',
    manufacturer: 'Cox Reels USA',
    price: 645.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 22.0,
    technical_notes: 'Rated 3000 PSI. 12V DC 1/3 HP motor. Holds 30m of 1/2" or 45m of 3/8" hose.',
    compatible_machines: ['TRAILER-SINGLE', 'TRAILER-TANDEM'],
    image_url: null,
    oem_genuine: false,
    featured: true,
    is_attachment: true,
    tags: ['cox reels', 'electric reel', '12v rewind', 'motorised'],
    active: true,
    sort_order: 310
  },
  {
    part_number: 'COX-1300-3-50',
    name: 'Cox Reels 1300 Series Heavy-Duty Stainless Fluid Reel',
    slug: 'cox-reels-1300-3-50-stainless',
    description: 'Severe-duty hose reel featuring full 316 stainless steel fluid path and electro-polished drum components for harsh chemical, saline, and coastal wash environments.',
    category: 'hoses',
    brand: 'cox-reels',
    manufacturer: 'Cox Reels USA',
    price: 385.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 16.0,
    technical_notes: 'Rated 4000 PSI. 316 Stainless steel fluid swivel and internal riser.',
    compatible_machines: ['TRAILER-TANDEM', 'WASH-PLANT'],
    image_url: null,
    oem_genuine: false,
    featured: false,
    is_attachment: true,
    tags: ['cox reels', 'stainless reel', 'chemical safe'],
    active: true,
    sort_order: 315
  },
  {
    part_number: 'COX-BRK-WM',
    name: 'Cox Reels Universal Wall / Van Mount Stiffener Bracket',
    slug: 'cox-reels-wall-mount-bracket',
    description: 'Heavy 5mm powder-coated steel mounting bracket for installing 1125 and 1175 series reels onto masonry walls or van bulkheads.',
    category: 'attachments',
    brand: 'cox-reels',
    manufacturer: 'Cox Reels USA',
    price: 45.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 3.5,
    technical_notes: 'Pre-punched mounting slots for quick alignment.',
    compatible_machines: ['TRAILER-SINGLE', 'TRAILER-TANDEM'],
    image_url: null,
    oem_genuine: false,
    featured: false,
    is_attachment: true,
    tags: ['cox reels', 'bracket', 'wall mount'],
    active: true,
    sort_order: 320
  },


  // ═══════════════════════════════════════════════════════════════════════════
  // 4. STEEL EAGLE USA (brand: 'steel-eagle')
  // ═══════════════════════════════════════════════════════════════════════════
  {
    part_number: 'SE-SC-16',
    name: 'Steel Eagle SE-16 Classic Commercial Surface Cleaner (16")',
    slug: 'steel-eagle-se-16',
    description: 'Professional commercial rotary surface cleaner with heavy spun aluminium deck, greaseable dual-bearing swivel union, and twin 25° wash nozzles. Built for multi-hour car park washing.',
    category: 'surface-cleaners',
    brand: 'steel-eagle',
    manufacturer: 'Steel Eagle USA',
    price: 225.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 7.8,
    technical_notes: 'Rated 4000 PSI @ 90°C. 2x 1/4" MEG nozzles.',
    compatible_machines: ['420X4', '430XH4', '216X4'],
    image_url: null,
    oem_genuine: false,
    featured: true,
    is_attachment: true,
    tags: ['steel eagle', 'surface cleaner', '16 inch', 'aluminium deck'],
    active: true,
    sort_order: 400
  },
  {
    part_number: 'SE-SC-20',
    name: 'Steel Eagle SE-20 Heavy Commercial Surface Cleaner (20")',
    slug: 'steel-eagle-se-20',
    description: 'Heavy 20" diameter rotary cleaner with ergonomic handle, integrated spray gun, and vacuum port connection for closed-loop wastewater recovery.',
    category: 'surface-cleaners',
    brand: 'steel-eagle',
    manufacturer: 'Steel Eagle USA',
    price: 295.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 9.5,
    technical_notes: 'Rated 4000 PSI @ 100°C. 2" vacuum recovery port connection.',
    compatible_machines: ['430XH4', '4358', 'TRAILER-SINGLE'],
    image_url: null,
    oem_genuine: false,
    featured: true,
    is_attachment: true,
    tags: ['steel eagle', '20 inch', 'vacuum port', 'surface cleaner'],
    active: true,
    sort_order: 405
  },
  {
    part_number: 'SE-BN-48',
    name: 'Steel Eagle 48" Multi-Nozzle Spray Bar Attachment',
    slug: 'steel-eagle-48-bar-nozzle',
    description: 'Wide-sweep high-pressure road and runway spray bar with 6x staggered fan nozzles and adjustable wheel height brackets.',
    category: 'lances-nozzles',
    brand: 'steel-eagle',
    manufacturer: 'Steel Eagle USA',
    price: 145.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 4.8,
    technical_notes: 'Rated 4000 PSI. 48" effective cleaning sweep width.',
    compatible_machines: ['4358', 'TRAILER-SINGLE', 'TRAILER-TANDEM'],
    image_url: null,
    oem_genuine: false,
    featured: false,
    is_attachment: true,
    tags: ['steel eagle', 'spray bar', 'road wash', '48 inch'],
    active: true,
    sort_order: 410
  },


  // ═══════════════════════════════════════════════════════════════════════════
  // 5. DUAL PUMPS UK (brand: 'dual-pumps')
  // ═══════════════════════════════════════════════════════════════════════════
  {
    part_number: 'DP-BM-25',
    name: 'Dual Pumps BM25 High-Pressure Bypass Manifold Assembly',
    slug: 'dual-pumps-bm25-bypass-manifold',
    description: 'UK-assembled brass bypass manifold unit with integrated thermal safety port, pressure gauge take-off, and chemical injection check valve.',
    category: 'valves-unloaders',
    brand: 'dual-pumps',
    manufacturer: 'Dual Pumps UK',
    price: 85.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 1.6,
    technical_notes: 'Rated 250 BAR @ 85°C. 3/8" BSP connections.',
    compatible_machines: ['420X4', '4305XD4'],
    image_url: null,
    oem_genuine: false,
    featured: false,
    is_attachment: false,
    tags: ['dual pumps', 'bypass manifold', 'valves', 'uk'],
    active: true,
    sort_order: 500
  },
  {
    part_number: 'DP-FP-12V',
    name: 'Dual Pumps 12V DC High-Volume Fuel Transfer Pump (40 LPM)',
    slug: 'dual-pumps-fp-12v-transfer-pump',
    description: 'Rotary vane diesel and kerosene transfer pump with 12V DC motor, internal bypass valve, and heavy cable clamps for trailer tank refuelling.',
    category: 'engines-motors',
    brand: 'dual-pumps',
    manufacturer: 'Dual Pumps UK',
    price: 145.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 4.2,
    technical_notes: 'Flow rate 40 LPM at 1.5 BAR. 30-minute duty cycle.',
    compatible_machines: ['TRAILER-SINGLE', 'TRAILER-TANDEM'],
    image_url: null,
    oem_genuine: false,
    featured: true,
    is_attachment: true,
    tags: ['dual pumps', '12v pump', 'fuel transfer', 'diesel'],
    active: true,
    sort_order: 505
  },
  {
    part_number: 'DP-GAUGE-400',
    name: 'Dual Pumps Stainless Glycerine Pressure Gauge (0–400 BAR)',
    slug: 'dual-pumps-glycerine-gauge-400-bar',
    description: 'Stainless steel case glycerine-filled pressure gauge with bottom 1/4" BSP connection. Liquid dampening eliminates pointer vibration for accurate system monitoring.',
    category: 'electrical-switches',
    brand: 'dual-pumps',
    manufacturer: 'Dual Pumps UK',
    price: 35.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.35,
    technical_notes: 'Dual scale 0-400 BAR / 0-5800 PSI. 63mm face diameter.',
    compatible_machines: ['420X4', '430XH4', '4358', '216X4'],
    image_url: null,
    oem_genuine: false,
    featured: false,
    is_attachment: false,
    tags: ['gauge', 'pressure gauge', 'glycerine', '400 bar'],
    active: true,
    sort_order: 510
  },
  {
    part_number: 'DP-CHEM-DOSE',
    name: 'Dual Pumps Venturi Chemical Dosing Injector Assembly',
    slug: 'dual-pumps-chemical-dosing-injector',
    description: 'Adjustable high-pressure downstream chemical injector with metering knob and clear braided suction hose with brass weighted filter foot.',
    category: 'attachments',
    brand: 'dual-pumps',
    manufacturer: 'Dual Pumps UK',
    price: 48.00,
    in_stock: true,
    availability_status: 'in_stock',
    weight_kg: 0.6,
    technical_notes: 'Draws chemical up to 20% ratio at working pressures up to 350 BAR.',
    compatible_machines: ['420X4', '430XH4', '216X4'],
    image_url: null,
    oem_genuine: false,
    featured: false,
    is_attachment: true,
    tags: ['dual pumps', 'chemical injector', 'venturi', 'detergent dosing'],
    active: true,
    sort_order: 515
  }
];
