import { MASTER_TAXONOMY } from './taxonomy';

export const COMPREHENSIVE_BRANDS = [
  { slug: 'alkota', name: 'Alkota', tagline: 'OEM Genuine Parts & Coils', country_of_origin: 'USA / UK', website_url: 'https://alkota.co.uk', sort_order: 1, is_featured: true },
  { slug: 'giant-pumps', name: 'Giant Pumps', tagline: 'Industrial High-Pressure Pumps', country_of_origin: 'USA / Germany', website_url: 'https://giantpumps.com', sort_order: 2, is_featured: true },
  { slug: 'interpump', name: 'Interpump Group', tagline: 'Italian Engineering Excellence', country_of_origin: 'Italy', website_url: 'https://interpumpgroup.it', sort_order: 3, is_featured: true },
  { slug: 'general-pump', name: 'General Pump', tagline: 'Triplex Plunger Technology', country_of_origin: 'USA / Italy', website_url: 'https://generalpump.com', sort_order: 4, is_featured: true },
  { slug: 'cat-pumps', name: 'CAT Pumps', tagline: 'The Pumps with Nine Lives', country_of_origin: 'USA / UK', website_url: 'https://catpumps.co.uk', sort_order: 5, is_featured: true },
  { slug: 'hawk', name: 'Hawk Pumps', tagline: 'Lechler High Pressure Innovation', country_of_origin: 'Italy', website_url: 'https://hawkpumps.com', sort_order: 6, is_featured: false },
  { slug: 'annovi-reverberi', name: 'Annovi Reverberi (AR)', tagline: 'Diaphragm & Plunger Pumps', country_of_origin: 'Italy', website_url: 'https://annovireverberi.it', sort_order: 7, is_featured: false },
  { slug: 'comet', name: 'Comet Pumps', tagline: 'Industrial & Agricultural Pumps', country_of_origin: 'Italy', website_url: 'https://comet-spa.com', sort_order: 8, is_featured: false },
  { slug: 'udor', name: 'Udor Pumps', tagline: 'Heavy Duty Plunger Pumps', country_of_origin: 'Italy', website_url: 'https://udor.it', sort_order: 9, is_featured: false },
  { slug: 'speck', name: 'Speck Triplex', tagline: 'German Precision Pumps', country_of_origin: 'Germany', website_url: 'https://speck-triplex.de', sort_order: 10, is_featured: false },
  { slug: 'pratissoli', name: 'Pratissoli Pompe', tagline: 'Ultra High Pressure Systems', country_of_origin: 'Italy', website_url: 'https://pratissolipompe.com', sort_order: 11, is_featured: false },
  { slug: 'pa', name: 'PA SpA', tagline: 'Valves & Pressure Accessories', country_of_origin: 'Italy', website_url: 'https://pa-etl.it', sort_order: 12, is_featured: true },
  { slug: 'mosmatic', name: 'Mosmatic AG', tagline: 'Swiss Rotating Precision', country_of_origin: 'Switzerland', website_url: 'https://mosmatic.com', sort_order: 13, is_featured: true },
  { slug: 'suttner', name: 'Suttner / R+M', tagline: 'German Professional Spray Equipment', country_of_origin: 'Germany', website_url: 'https://rm-suttner.com', sort_order: 14, is_featured: true },
  { slug: 'cox-reels', name: 'CoxREELS', tagline: 'Heavy Duty USA Hose Reels', country_of_origin: 'USA', website_url: 'https://coxreels.com', sort_order: 15, is_featured: true },
  { slug: 'steel-eagle', name: 'Steel Eagle', tagline: 'Commercial Surface Cleaners', country_of_origin: 'USA', website_url: 'https://steeleagle.com', sort_order: 16, is_featured: true },
  { slug: 'spraying-systems', name: 'Spraying Systems Co.', tagline: 'Precision Spray Nozzle Technology', country_of_origin: 'USA', website_url: 'https://spray.com', sort_order: 17, is_featured: false },
  { slug: 'nito', name: 'NiTO', tagline: 'Danish Heavy Duty Couplings', country_of_origin: 'Denmark', website_url: 'https://nito.dk', sort_order: 18, is_featured: false },
  { slug: 'mtm-hydro', name: 'MTM Hydro', tagline: 'Italian Foam & Spray Tooling', country_of_origin: 'Italy', website_url: 'https://mtmhydro.it', sort_order: 19, is_featured: false },
  { slug: 'idrobase', name: 'Idrobase Group', tagline: 'High Pressure Water Technology', country_of_origin: 'Italy', website_url: 'https://idrobasegroup.com', sort_order: 20, is_featured: false },
  { slug: 'dual-pumps', name: 'Dual Pumps', tagline: 'UK High Pressure Components', country_of_origin: 'UK', website_url: 'https://dualpumps.co.uk', sort_order: 21, is_featured: true },
  { slug: 'riello', name: 'Riello Burners', tagline: 'Combustion Excellence', country_of_origin: 'Italy', website_url: 'https://rielloburners.co.uk', sort_order: 22, is_featured: false },
  { slug: 'beckett', name: 'Beckett', tagline: 'OEM Burner Heads & Electrodes', country_of_origin: 'USA', website_url: 'https://beckettcorp.com', sort_order: 23, is_featured: false },
  { slug: 'honda', name: 'Honda Power Equipment', tagline: 'Commercial GX Engine Technology', country_of_origin: 'Japan', website_url: 'https://engines.honda.com', sort_order: 24, is_featured: false },
  { slug: 'vanguard', name: 'Vanguard Commercial', tagline: 'Commercial V-Twin Power', country_of_origin: 'USA', website_url: 'https://vanguardpower.com', sort_order: 25, is_featured: false },
];

export const COMPREHENSIVE_APPLICATIONS = [
  {
    slug: 'vehicle-fleet-cleaning',
    name: 'Vehicle & Fleet Cleaning',
    tagline: 'Haulage, plant hire, agricultural machinery, and municipal fleet washdown.',
    hero_image_url: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=2000&q=80',
    editorial_intro: 'Fleet operations demand rapid cycle times, high chemical dwell effectiveness, and durable foaming attachments capable of removing road film without damaging vehicle livery or chassis electronics.',
    buying_guidance: 'For commercial fleet cleaning, select high-flow hot water systems (15-21 LPM) paired with dual-lance spray handles and downstream chemical injectors. Rotary undercarriage cleaners protect chassis longevity.',
    recommended_specs: '150-200 Bar · 15-21 LPM · 60-80°C Hot Water · Foam Lances & Undercarriage Tooling',
    sort_order: 1,
  },
  {
    slug: 'industrial-machinery-cleaning',
    name: 'Industrial Machinery Cleaning',
    tagline: 'Heavy grease extraction, CNC degreasing, factory maintenance, and hydraulic washdown.',
    hero_image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=2000&q=80',
    editorial_intro: 'Manufacturing and production plant environments require high-temperature thermal cutting power to break down hardened grease, carbonised hydraulic oil, and industrial residues without excessive water flooding.',
    buying_guidance: 'Combine Schedule 80 hot water coils with Alkota steam combination valves (140°C saturated dry steam) and zero-degree rotating turbo tips for precision grease stripping.',
    recommended_specs: '200-250 Bar · 15 LPM · Up to 140°C Steam Mode · Trapped Pressure Unloaders',
    sort_order: 2,
  },
  {
    slug: 'concrete-hard-surface-cleaning',
    name: 'Concrete & Hard Surface Cleaning',
    tagline: 'Car parks, pedestrian precincts, block paving, loading bays, and forecourts.',
    hero_image_url: 'https://images.unsplash.com/photo-1590496793929-36417d3117de?auto=format&fit=crop&w=2000&q=80',
    editorial_intro: 'Surface cleaning contractors need wide-path rotary surface cleaners that eliminate zebra striping and process thousands of square metres per hour with maximum operator ergonomics.',
    buying_guidance: 'Pair Mosmatic or Steel Eagle 20" to 30" rotary surface cleaners with double-wire braided hoses and live fluid swivels to prevent hose binding.',
    recommended_specs: '200-300 Bar · 18-25 LPM · 20"-30" Rotary Cleaners · Live Swivels',
    sort_order: 3,
  },
  {
    slug: 'agricultural-cleaning',
    name: 'Agricultural Cleaning',
    tagline: 'Poultry sheds, livestock housing, tractors, harvesters, and biosecurity sanitation.',
    hero_image_url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=2000&q=80',
    editorial_intro: 'Farming environments require robust high-volume water throughput (20-30+ LPM) to flush out heavy organic build-up and achieve DEFRA-compliant sanitisation in poultry and livestock sheds.',
    buying_guidance: 'High-volume triplex pumps with ceramic plungers and heavy-duty unloader valves ensure continuous duty under rigorous farm conditions.',
    recommended_specs: '150-200 Bar · 20-30 LPM · High-Volume Triplex Pumps · 50m Hose Reels',
    sort_order: 4,
  },
  {
    slug: 'drain-sewer-jetting',
    name: 'Drain & Sewer Jetting',
    tagline: 'Blockage clearance, root cutting, grease descaling, and stormwater line maintenance.',
    hero_image_url: 'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=2000&q=80',
    editorial_intro: 'Drain contractors rely on precision-machined rear-propulsion jetting nozzles and ultra-slick micro-bore thermoplastic jetting hoses to negotiate tight pipe bends and clear grease fatbergs.',
    buying_guidance: 'Match flow rate to pipe diameter: 15 LPM for 50-100mm domestic lines, 30+ LPM for 150-225mm commercial culverts.',
    recommended_specs: '150-250 Bar · 15-40 LPM · Specialist Jetting Nozzles · Thermoplastic Hoses',
    sort_order: 5,
  },
  {
    slug: 'food-production-washdown',
    name: 'Food & Production Washdown',
    tagline: 'Abattoirs, dairies, bakeries, food packaging lines, and hygiene compliance.',
    hero_image_url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=2000&q=80',
    editorial_intro: 'Food manufacturing facilities require 316 stainless steel components, non-marking blue and grey hoses, and FDA-approved food-safe lubricants to prevent contamination.',
    buying_guidance: 'Specify stainless steel quick couplers, food-grade hoses, and chemical dosing injectors for accurate sanitiser application.',
    recommended_specs: '80-150 Bar · 12-18 LPM · Non-Marking Hoses · 316 Stainless Couplers',
    sort_order: 6,
  },
  {
    slug: 'building-facilities-cleaning',
    name: 'Building & Facilities Cleaning',
    tagline: 'Cladding washdown, brickwork restoration, render cleaning, and architectural maintenance.',
    hero_image_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=2000&q=80',
    editorial_intro: 'Building exteriors often require delicate low-pressure softwashing chemical application followed by temperature-controlled hot water rinsing to protect modern renders and heritage stone.',
    buying_guidance: 'Telescopic carbon fibre lances up to 10m allow ground-level cleaning of two-storey commercial buildings without scaffolding.',
    recommended_specs: '50-150 Bar · 12-15 LPM · Telescopic Wands · Chemical Softwash Injectors',
    sort_order: 7,
  },
  {
    slug: 'roof-gutter-cleaning',
    name: 'Roof & Gutter Cleaning',
    tagline: 'Moss removal, tile softwashing, downpipe clearing, and high-level washdown.',
    hero_image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=2000&q=80',
    editorial_intro: 'Roof restoration requires specialised angled surface cleaners and extended hoses to safely wash roofs from gutter line or mobile access platforms.',
    buying_guidance: 'Use lightweight 1-wire hoses and high-pressure curved wands with 40° flat fan nozzles.',
    recommended_specs: '100-180 Bar · 13-16 LPM · Curved Gutter Wands · 30m Light Hoses',
    sort_order: 8,
  },
  {
    slug: 'graffiti-surface-restoration',
    name: 'Graffiti & Surface Restoration',
    tagline: 'Paint stripping, heritage masonry cleaning, chewing gum removal, and public realm restoration.',
    hero_image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=2000&q=80',
    editorial_intro: 'Graffiti removal combines solvent chemical dwelling with 120°C+ thermal hot water and saturated steam to dissolve pigments without etching underlying stone or brick.',
    buying_guidance: 'Wet sandblasting injection kits and high-temperature steam nozzles provide gentle yet powerful abrasive cleaning for stubborn coatings.',
    recommended_specs: '150-250 Bar · 12-15 LPM · 120-140°C Steam Mode · Wet Sandblast Kits',
    sort_order: 9,
  },
  {
    slug: 'heavy-duty-degreasing',
    name: 'Heavy-Duty Degreasing',
    tagline: 'Earthmoving plant, mining equipment, railway rolling stock, and oil refinery turnarounds.',
    hero_image_url: 'https://images.unsplash.com/photo-1504307651554-6691fc9d0901?auto=format&fit=crop&w=2000&q=80',
    editorial_intro: 'Extreme degreasing operations require the highest thermal energy and pressure output available: 250+ bar at 90°C hot water continuously all day.',
    buying_guidance: 'Alkota 4000 and 5000 series heavy-duty hot water skids with General Pump or Giant Pumps bare-shaft units.',
    recommended_specs: '250-350 Bar · 18-30 LPM · 90-100°C Continuous · Heavy Duty Unloader Valves',
    sort_order: 10,
  },
];

export const COMPREHENSIVE_SUPPLIERS = [
  { slug: 'dual-pumps', name: 'Dual Pumps Ltd', code: 'DP', supplier_type: 'wholesaler', default_margin_pct: 35.0, contact_name: 'Trade Desk', email: 'sales@dualpumps.co.uk', website_url: 'https://dualpumps.co.uk', sort_order: 1 },
  { slug: 'flowjet', name: 'Flowjet Cleaning Equipment', code: 'FJ', supplier_type: 'wholesaler', default_margin_pct: 35.0, contact_name: 'Trade Accounts', email: 'sales@flowjet.co.uk', website_url: 'https://flowjet.co.uk', sort_order: 2 },
  { slug: 'exchange-engineering', name: 'Exchange Engineering Ltd', code: 'EE', supplier_type: 'wholesaler', default_margin_pct: 35.0, contact_name: 'Spares Desk', email: 'sales@exchange-engineering.co.uk', website_url: 'https://exchange-engineering.co.uk', sort_order: 3 },
  { slug: 'gs-penrith', name: 'G&S Penrith Ltd', code: 'GS', supplier_type: 'distributor', default_margin_pct: 32.0, contact_name: 'Parts Division', email: 'sales@gspenrith.co.uk', website_url: 'https://gspenrith.co.uk', sort_order: 4 },
  { slug: 'stinson-equipment', name: 'Stinson Equipment UK', code: 'ST', supplier_type: 'importer', default_margin_pct: 38.0, contact_name: 'Imports Desk', email: 'sales@stinsonequipment.co.uk', website_url: 'https://stinsonequipment.co.uk', sort_order: 5 },
  { slug: 'alkota-oem', name: 'Alkota Manufacturing USA (Direct)', code: 'ALK', supplier_type: 'manufacturer', default_margin_pct: 45.0, contact_name: 'OEM Parts Team', email: 'spares@alkota.co.uk', website_url: 'https://alkota.co.uk', sort_order: 6 },
];

export const COMPREHENSIVE_MACHINE_FAMILIES = [
  { slug: 'alkota-200-series', name: '200 Series Mobile Hot Water', manufacturer: 'Alkota', description: 'Compact mobile oil-fired hot water pressure washers for farm, garage, and commercial duty.', sort_order: 1 },
  { slug: 'alkota-4000-series', name: '4000 Series Industrial Hot Water', manufacturer: 'Alkota', description: 'Heavy-duty industrial workhorse with hydro-insulated Schedule 80 heating coil and stainless steel wrapper.', sort_order: 2 },
  { slug: 'alkota-5000-series', name: '5000 Series Severe-Duty Hot Water', manufacturer: 'Alkota', description: 'Multi-operator severe duty hot water cleaning platforms for continuous 24/7 industrial washing.', sort_order: 3 },
  { slug: 'alkota-rotary-apw', name: 'APW Rotary Parts Washers', manufacturer: 'Alkota', description: 'Aqueous front-loading rotating basket hot parts cleaning machines.', sort_order: 4 },
  { slug: 'alkota-stationary-skid', name: 'Stationary Electric Skids', manufacturer: 'Alkota', description: 'Central wash bay stationary hot water skids with remote push-button operator stations.', sort_order: 5 },
];

export const COMPREHENSIVE_MACHINE_MODELS = [
  { slug: 'alkota-216x4', model_code: '216X4', name: 'Alkota 216X4 Mobile Hot Water', family_slug: 'alkota-200-series', series: '200 Series', pressure_psi: 2000, flow_gpm: 3.0, flow_lpm: 11.4, power_source: 'Electric 240V 1-Phase', heating_type: 'Diesel / Kerosene Fired', specs_summary: '2000 PSI · 11.4 LPM · 2.2kW 240V · Beckett Burner Head · 10m Hose' },
  { slug: 'alkota-311x4', model_code: '311X4', name: 'Alkota 311X4 Mobile Hot Water', family_slug: 'alkota-200-series', series: '200 Series', pressure_psi: 3000, flow_gpm: 3.5, flow_lpm: 13.2, power_source: 'Electric 415V 3-Phase', heating_type: 'Diesel / Kerosene Fired', specs_summary: '3000 PSI · 13.2 LPM · 4.0kW 415V · Riello Burner · General Pump TS2021' },
  { slug: 'alkota-4305', model_code: '4305', name: 'Alkota 4305 Heavy-Duty Hot Water', family_slug: 'alkota-4000-series', series: '4000 Series', pressure_psi: 3000, flow_gpm: 5.0, flow_lpm: 19.0, power_source: 'Electric 415V 3-Phase', heating_type: 'Diesel / Kerosene Fired', specs_summary: '3000 PSI · 19.0 LPM · 7.5kW 415V · Schedule 80 Coil · General Pump TS2041' },
  { slug: 'alkota-4405', model_code: '4405', name: 'Alkota 4405 Industrial Hot Water', family_slug: 'alkota-4000-series', series: '4000 Series', pressure_psi: 4000, flow_gpm: 5.0, flow_lpm: 19.0, power_source: 'Electric 415V 3-Phase', heating_type: 'Diesel / Kerosene Fired', specs_summary: '4000 PSI · 19.0 LPM · 11kW 415V · Schedule 80 Coil · Cat Pump 5CP2120W' },
  { slug: 'alkota-5355', model_code: '5355', name: 'Alkota 5355 Severe-Duty Hot Water', family_slug: 'alkota-5000-series', series: '5000 Series', pressure_psi: 3500, flow_gpm: 5.5, flow_lpm: 21.0, power_source: 'Electric 415V 3-Phase', heating_type: 'Diesel / Kerosene Fired', specs_summary: '3500 PSI · 21.0 LPM · 15kW 415V · Giant Pump P400 Series' },
  { slug: 'alkota-apw-24', model_code: 'APW-24', name: 'Alkota APW-24 Rotary Parts Washer', family_slug: 'alkota-rotary-apw', series: 'APW Series', pressure_psi: 60, flow_gpm: 45.0, flow_lpm: 170.0, power_source: 'Electric 415V 3-Phase', heating_type: 'Electrically Heated 9kW', specs_summary: '24" Turntable · 250kg Capacity · 9kW Electric Heating · Oil Skimmer' },
];
