export interface MasterCategory {
  slug: string;
  name: string;
  shortDesc: string;
  iconName: string;
  isFeatured: boolean;
  subcategories: {
    slug: string;
    name: string;
    shortDesc?: string;
  }[];
}

export const MASTER_TAXONOMY: MasterCategory[] = [
  {
    slug: 'pumps',
    name: 'Pumps & Pump Parts',
    shortDesc: 'Complete triplex plunger pumps, ceramic pistons, manifold heads, and valve repair kits.',
    iconName: 'Gauge',
    isFeatured: true,
    subcategories: [
      { slug: 'complete-pumps', name: 'Complete Pumps', shortDesc: 'Bare-shaft and gearbox-driven triplex plunger pumps.' },
      { slug: 'pump-repair-kits', name: 'Pump Repair Kits', shortDesc: 'Complete major and minor rebuild kits.' },
      { slug: 'seal-kits', name: 'Seal Kits', shortDesc: 'High and low-pressure packing seal assemblies.' },
      { slug: 'seals-packing', name: 'Seals & Packing', shortDesc: 'V-packings, wiper seals, and support rings.' },
      { slug: 'valves', name: 'Valves', shortDesc: 'Inlet and discharge check valves.' },
      { slug: 'valve-kits', name: 'Valve Kits', shortDesc: 'Pre-assembled valve sets with O-rings and cages.' },
      { slug: 'pistons-plungers', name: 'Pistons / Plungers', shortDesc: 'Solid ceramic and stainless plunger rods.' },
      { slug: 'pump-heads', name: 'Pump Heads', shortDesc: 'Forged brass and stainless steel manifold heads.' },
      { slug: 'manifolds', name: 'Manifolds', shortDesc: 'Inlet and bypass manifold assemblies.' },
      { slug: 'bearings', name: 'Bearings', shortDesc: 'Tapered roller and needle crankshaft bearings.' },
      { slug: 'crankcases', name: 'Crankcases / Pump Components', shortDesc: 'Aluminium crankcases, connecting rods, and oil dipsticks.' },
      { slug: 'unloaders', name: 'Unloaders', shortDesc: 'Trapped pressure and flow-actuated unloader valves.' },
      { slug: 'regulators', name: 'Regulators', shortDesc: 'Variable pressure regulating valves.' },
      { slug: 'pressure-regulators', name: 'Pressure Regulators', shortDesc: 'In-line pressure adjustment controls.' },
      { slug: 'pump-accessories', name: 'Pump Accessories', shortDesc: 'Pulsation dampeners, thermal relief, and gauges.' },
      { slug: 'pump-oil', name: 'Pump Oil', shortDesc: 'Non-detergent ISO VG 220 & 100 specialist crankcase lubricants.' },
      { slug: 'pump-service-parts', name: 'Pump Service Parts', shortDesc: 'Scheduled replacement items and seal tools.' },
    ],
  },
  {
    slug: 'hoses',
    name: 'Hoses & Hose Reels',
    shortDesc: 'High-pressure single and double-wire braided hoses, retractable reels, and live swivels.',
    iconName: 'Activity',
    isFeatured: true,
    subcategories: [
      { slug: 'high-pressure-hoses', name: 'High-Pressure Hoses', shortDesc: '1-wire and 2-wire rubber braided hoses up to 500 bar.' },
      { slug: 'low-pressure-hoses', name: 'Low-Pressure Hoses', shortDesc: 'Suction and chemical feed delivery lines.' },
      { slug: 'hose-reels', name: 'Hose Reels', shortDesc: 'Industrial steel and stainless steel storage drums.' },
      { slug: 'manual-hose-reels', name: 'Manual Hose Reels', shortDesc: 'Direct-crank and hand-wind reels.' },
      { slug: 'electric-hose-reels', name: 'Electric Hose Reels', shortDesc: '12V, 24V, and 240V motorised rewinding reels.' },
      { slug: 'retractable-hose-reels', name: 'Retractable Hose Reels', shortDesc: 'Spring-rewind automatic latching reels.' },
      { slug: 'hose-reel-accessories', name: 'Hose Reel Accessories', shortDesc: 'Guide rollers, mounting brackets, and pin locks.' },
      { slug: 'swivels', name: 'Swivels', shortDesc: 'High-pressure 90° and straight live fluid swivels.' },
      { slug: 'hose-fittings', name: 'Hose Fittings', shortDesc: 'Swaged ends, BSP male and female hose tails.' },
      { slug: 'hose-adaptors', name: 'Hose Adaptors', shortDesc: 'Joining nipples, reducing bushes, and union connectors.' },
      { slug: 'hose-repair', name: 'Hose Repair', shortDesc: 'Reusable screw-on repair fittings and joiners.' },
      { slug: 'hose-protection', name: 'Hose Protection', shortDesc: 'Spiral wrap scuff guards and bend restrictors.' },
    ],
  },
  {
    slug: 'trigger-guns',
    name: 'Guns, Lances & Wands',
    shortDesc: 'Fatigue-reducing easy-pull spray guns, insulated wands, telescopic poles, and connectors.',
    iconName: 'Wrench',
    isFeatured: true,
    subcategories: [
      { slug: 'trigger-guns', name: 'Trigger Guns', shortDesc: 'Industrial spray guns rated up to 600 bar and 150°C.' },
      { slug: 'spray-guns', name: 'Spray Guns', shortDesc: 'Open-flow and dump guns for continuous-duty systems.' },
      { slug: 'trigger-gun-accessories', name: 'Trigger Gun Accessories', shortDesc: 'Grip guards, trigger latches, and repair cartridges.' },
      { slug: 'lances', name: 'Lances', shortDesc: 'Stainless steel and zinc-plated spray pipes.' },
      { slug: 'extension-lances', name: 'Extension Lances', shortDesc: 'Intermediate rigid lance extensions.' },
      { slug: 'telescopic-lances', name: 'Telescopic Lances', shortDesc: 'Fibreglass and carbon fibre reach poles up to 10 metres.' },
      { slug: 'insulated-lances', name: 'Insulated Lances', shortDesc: 'Moulded heat-shield grips for hot water applications.' },
      { slug: 'wand-accessories', name: 'Wand Accessories', shortDesc: 'Nozzle holders, rubber boots, and angled bend adapters.' },
      { slug: 'gun-swivels', name: 'Gun Swivels', shortDesc: 'Inlet live swivels preventing hose kinking.' },
      { slug: 'gun-connectors', name: 'Gun Connectors', shortDesc: 'Quick-release adaptors for lance interchange.' },
      { slug: 'gun-repair-parts', name: 'Gun Repair Parts', shortDesc: 'Valve balls, seats, seals, and trigger pins.' },
    ],
  },
  {
    slug: 'lances-nozzles',
    name: 'Nozzles',
    shortDesc: 'Hardened stainless steel flat fan nozzles, rotating turbo tips, and jetting jets.',
    iconName: 'Target',
    isFeatured: true,
    subcategories: [
      { slug: 'high-pressure-nozzles', name: 'High-Pressure Nozzles', shortDesc: 'Standard 1/4" NPT and MEG calibrated jet nozzles.' },
      { slug: 'flat-fan-nozzles', name: 'Flat Fan Nozzles', shortDesc: '0°, 15°, 25°, and 40° spray angle nozzles.' },
      { slug: 'rotary-turbo-nozzles', name: 'Rotary / Turbo Nozzles', shortDesc: 'Rotating point-impact nozzles for maximum cutting force.' },
      { slug: 'sewer-jetting-nozzles', name: 'Sewer & Jetting Nozzles', shortDesc: 'Rear-facing propulsion and forward penetrating nozzles.' },
      { slug: 'drain-cleaning-nozzles', name: 'Drain Cleaning Nozzles', shortDesc: 'Rotating and button drain clearing heads.' },
      { slug: 'foam-nozzles', name: 'Foam Nozzles', shortDesc: 'Low-pressure air-induction foaming inserts.' },
      { slug: 'chemical-nozzles', name: 'Chemical Nozzles', shortDesc: 'High-volume low-pressure detergent soap nozzles (65°).' },
      { slug: 'sandblasting-nozzles', name: 'Sandblasting Nozzles', shortDesc: 'Wet abrasive blast injection heads and carbide nozzles.' },
      { slug: 'nozzle-holders', name: 'Nozzle Holders', shortDesc: 'Multi-nozzle rollover heads and quick-change couplers.' },
      { slug: 'nozzle-protectors', name: 'Nozzle Protectors', shortDesc: 'Rubber impact shrouds and colour-coded nozzle boots.' },
      { slug: 'nozzle-accessories', name: 'Nozzle Accessories', shortDesc: 'Nozzle cleaning needles, adaptors, and sizing gauges.' },
    ],
  },
  {
    slug: 'surface-cleaners',
    name: 'Surface & Floor Cleaning',
    shortDesc: 'Professional rotary flat surface cleaners, undercarriage wash tools, and replacement rotors.',
    iconName: 'RotateCcw',
    isFeatured: true,
    subcategories: [
      { slug: 'surface-cleaners', name: 'Surface Cleaners', shortDesc: 'Complete walk-behind rotary surface cleaners from 12" to 30".' },
      { slug: 'rotary-surface-cleaners', name: 'Rotary Surface Cleaners', shortDesc: 'High-RPM rotating arm ground cleaners.' },
      { slug: 'flat-surface-cleaners', name: 'Flat Surface Cleaners', shortDesc: 'Stainless steel and composite dome units.' },
      { slug: 'heavy-duty-surface-cleaners', name: 'Heavy-Duty Surface Cleaners', shortDesc: 'Contractor-grade recovery and high-flow systems.' },
      { slug: 'industrial-surface-cleaners', name: 'Industrial Surface Cleaners', shortDesc: 'Multi-operator and 500 bar rated cleaning platforms.' },
      { slug: 'replacement-jets', name: 'Replacement Jets', shortDesc: 'Calibrated threaded rotor bar spray nozzles.' },
      { slug: 'replacement-heads', name: 'Replacement Heads', shortDesc: 'Precision stainless steel rotating unions and swivel cores.' },
      { slug: 'wheels-casters', name: 'Wheels & Casters', shortDesc: 'Non-marking stainless sealed bearing caster sets.' },
      { slug: 'surface-cleaner-accessories', name: 'Surface Cleaner Accessories', shortDesc: 'Vacuum recovery ports, handle brackets, and skirt brushes.' },
      { slug: 'surface-cleaner-spares', name: 'Surface Cleaner Spares', shortDesc: 'Rotary arms, mounting hardware, and seal repair kits.' },
    ],
  },
  {
    slug: 'foam-chemical',
    name: 'Foam & Chemical Application',
    shortDesc: 'Snow foam lances, downstream chemical injectors, dosing pumps, and chemical tanks.',
    iconName: 'Layers',
    isFeatured: false,
    subcategories: [
      { slug: 'foam-lances', name: 'Foam Lances', shortDesc: 'High-density foam cannons with adjustable air intake.' },
      { slug: 'foam-guns', name: 'Foam Guns', shortDesc: 'Direct-bottle foaming spray guns.' },
      { slug: 'foam-systems', name: 'Foam Systems', shortDesc: 'Wall-mounted and mobile central foam generator stations.' },
      { slug: 'chemical-injectors', name: 'Chemical Injectors', shortDesc: 'Fixed and adjustable brass & stainless venturi injectors.' },
      { slug: 'downstream-injectors', name: 'Downstream Injectors', shortDesc: 'Post-pump chemical delivery avoiding pump chemical contact.' },
      { slug: 'chemical-bottles', name: 'Chemical Bottles', shortDesc: 'Graduated 1L and 2L wide-mouth chemical reservoirs.' },
      { slug: 'chemical-dosing-equipment', name: 'Chemical Dosing Equipment', shortDesc: 'Proportional water-driven and electronic dosing pumps.' },
      { slug: 'chemical-application-accessories', name: 'Chemical Application Accessories', shortDesc: 'Suction filters, foot valves, and metering restrictor tips.' },
    ],
  },
  {
    slug: 'jetting-drain',
    name: 'Jetting & Drain Cleaning',
    shortDesc: 'Drain jetting nozzles, sewer hoses, root-cutting heads, and pipe cleaning equipment.',
    iconName: 'Target',
    isFeatured: false,
    subcategories: [
      { slug: 'sewer-nozzles', name: 'Sewer Nozzles', shortDesc: 'High-thrust bomb, egg, and torpedo profile jetting nozzles.' },
      { slug: 'drain-cleaning-nozzles', name: 'Drain Cleaning Nozzles', shortDesc: 'Compact 1/8" and 1/4" flexible drain cleaning jets.' },
      { slug: 'jetting-guns', name: 'Jetting Guns', shortDesc: 'Specialist drain flushing foot valves and handheld dump guns.' },
      { slug: 'jetting-hoses', name: 'Jetting Hoses', shortDesc: 'Ultra-slick thermoplastic micro-bore jetting hoses.' },
      { slug: 'pipe-cleaning-equipment', name: 'Pipe Cleaning Equipment', shortDesc: 'Centralizer skids and pipe flushing accessories.' },
      { slug: 'root-cutting-equipment', name: 'Root-Cutting Equipment', shortDesc: 'Turbine-driven chain flails and rotating blade cutters.' },
      { slug: 'jetting-accessories', name: 'Jetting Accessories', shortDesc: 'Tiger tail hose protectors and top-hole roller guides.' },
      { slug: 'drain-cleaning-accessories', name: 'Drain Cleaning Accessories', shortDesc: 'Hose stoppers, manhole brackets, and pressure gauges.' },
    ],
  },
  {
    slug: 'fittings-couplers',
    name: 'Couplings & Fittings',
    shortDesc: 'Quick-release plugs, sockets, BSP adaptors, live swivels, and Viton O-rings.',
    iconName: 'Link2',
    isFeatured: true,
    subcategories: [
      { slug: 'quick-release-couplings', name: 'Quick-Release Couplings', shortDesc: 'Standard and valved quick-disconnect couplers.' },
      { slug: 'quick-release-plugs', name: 'Quick-Release Plugs', shortDesc: 'Hardened steel and stainless steel male nipples.' },
      { slug: 'quick-release-sockets', name: 'Quick-Release Sockets', shortDesc: 'Brass and 316 stainless steel locking coupler female bodies.' },
      { slug: 'adaptors', name: 'Adaptors', shortDesc: 'Thread conversion nipples and bushes (BSP / NPT / Metric).' },
      { slug: 'bsp-fittings', name: 'BSP Fittings', shortDesc: 'British Standard Pipe parallel and taper fittings.' },
      { slug: 'metric-fittings', name: 'Metric Fittings', shortDesc: 'M22, M18, and DIN standard pressure washer fittings.' },
      { slug: 'swivels', name: 'Swivels', shortDesc: 'Full 360-degree rotating inline fluid connectors.' },
      { slug: 'connectors', name: 'Connectors', shortDesc: 'Hose joining splices and compression fittings.' },
      { slug: 'unions', name: 'Unions', shortDesc: 'Cone seat and flat face mechanical unions.' },
      { slug: 'elbows', name: 'Elbows', shortDesc: '90° and 45° forged high-pressure elbows.' },
      { slug: 'tees', name: 'Tees', shortDesc: '3-way branching tee fittings for pressure and bypass lines.' },
      { slug: 'o-rings', name: 'O-Rings', shortDesc: 'High-temperature Viton, EPDM, and NBR replacement seals.' },
      { slug: 'seals', name: 'Seals', shortDesc: 'Bonded Dowty washers, copper crush washers, and PTFE tape.' },
    ],
  },
  {
    slug: 'burners',
    name: 'Burner & Hot Water Parts',
    shortDesc: 'Schedule 80 hydro-insulated coils, Riello & Beckett burners, electrodes, and fuel pumps.',
    iconName: 'Flame',
    isFeatured: true,
    subcategories: [
      { slug: 'burner-pumps', name: 'Burner Pumps', shortDesc: 'Direct-drive fuel delivery pumps and solenoid valves.' },
      { slug: 'fuel-pumps', name: 'Fuel Pumps', shortDesc: 'Suntec and Danfoss diesel pressure pumps.' },
      { slug: 'electrodes', name: 'Electrodes', shortDesc: 'Ignition sparks, ceramic insulators, and electrode pairs.' },
      { slug: 'ignition-components', name: 'Ignition Components', shortDesc: 'High-voltage electronic and iron-core transformers.' },
      { slug: 'solenoids', name: 'Solenoids', shortDesc: '24V, 110V, and 240V fuel cut-off solenoid coils and stems.' },
      { slug: 'fuel-filters', name: 'Fuel Filters', shortDesc: 'Spin-on canister and cleanable bowl diesel filters.' },
      { slug: 'thermostats', name: 'Thermostats', shortDesc: 'Adjustable capillary dials and high-limit safety cut-offs.' },
      { slug: 'flow-switches', name: 'Flow Switches', shortDesc: 'Horizontal and vertical burner interlock flow switches.' },
      { slug: 'temperature-sensors', name: 'Temperature Sensors', shortDesc: 'Thermocouples and PT100 temperature monitoring probes.' },
      { slug: 'burner-motors', name: 'Burner Motors', shortDesc: 'Combustion air blower fan motors and drive couplings.' },
      { slug: 'burner-components', name: 'Burner Components', shortDesc: 'Flame retention heads, blast tubes, and photocells.' },
      { slug: 'heating-coil-components', name: 'Heating Coil Components', shortDesc: 'Ceramic insulation blankets, bottom discs, and steel wraps.' },
      { slug: 'hot-water-controls', name: 'Hot Water Controls', shortDesc: 'Steam mode valves, thermostat wells, and relief valves.' },
      { slug: 'burner-service-kits', name: 'Burner Service Kits', shortDesc: 'Annual maintenance packages including nozzle, filter, and electrodes.' },
    ],
  },
  {
    slug: 'electrical-switches',
    name: 'Electrical & Controls',
    shortDesc: 'Heavy-duty rotary switches, contactors, overload relays, and pressure switches.',
    iconName: 'Zap',
    isFeatured: false,
    subcategories: [
      { slug: 'switches', name: 'Switches', shortDesc: 'Cam rotary power selectors, toggle switches, and rocker switches.' },
      { slug: 'contactors', name: 'Contactors', shortDesc: '3-pole and 4-pole motor switching contactors.' },
      { slug: 'relays', name: 'Relays', shortDesc: 'Thermal overload relays and timed delay circuits.' },
      { slug: 'capacitors', name: 'Capacitors', shortDesc: 'Motor start and motor run capacitors.' },
      { slug: 'motors', name: 'Motors', shortDesc: 'Single-phase and three-phase hollow-shaft TEFC electric motors.' },
      { slug: 'control-boxes', name: 'Control Boxes', shortDesc: 'IP65 waterproof electrical enclosures and faceplates.' },
      { slug: 'sensors', name: 'Sensors', shortDesc: 'Optical flame sensors and water level reed switches.' },
      { slug: 'pressure-switches', name: 'Pressure Switches', shortDesc: 'Auto stop-start pressure switches and differential monitors.' },
      { slug: 'flow-switches', name: 'Flow Switches', shortDesc: 'Magnetic reed flow switches for machine shutdown.' },
      { slug: 'temperature-controls', name: 'Temperature Controls', shortDesc: 'Digital thermostats and mechanical capillary controllers.' },
      { slug: 'electrical-components', name: 'Electrical Components', shortDesc: 'Terminal blocks, cable glands, indicator lamps, and fuses.' },
      { slug: 'wiring-connectors', name: 'Wiring / Connectors', shortDesc: 'Industrial CEEform plugs, sockets, and wiring harnesses.' },
    ],
  },
  {
    slug: 'engines-motors',
    name: 'Engines & Engine Parts',
    shortDesc: 'Honda GX and Vanguard engine service items, carburettors, air filters, and starter cords.',
    iconName: 'Cpu',
    isFeatured: false,
    subcategories: [
      { slug: 'petrol-engines', name: 'Petrol Engines', shortDesc: 'Complete Honda GX200, GX390, and Vanguard commercial engines.' },
      { slug: 'diesel-engines', name: 'Diesel Engines', shortDesc: 'Yanmar and Kohler air-cooled diesel engines.' },
      { slug: 'engine-service-kits', name: 'Engine Service Kits', shortDesc: 'Complete 100-hour and annual engine maintenance packs.' },
      { slug: 'air-filters', name: 'Air Filters', shortDesc: 'Dual-element foam and paper air filter assemblies.' },
      { slug: 'fuel-filters', name: 'Fuel Filters', shortDesc: 'In-tank strainers and inline fuel delivery filters.' },
      { slug: 'oil-filters', name: 'Oil Filters', shortDesc: 'Spin-on engine oil filters for commercial V-twin power plants.' },
      { slug: 'spark-plugs', name: 'Spark Plugs', shortDesc: 'NGK and Champion spark plugs for Honda and Briggs engines.' },
      { slug: 'engine-components', name: 'Engine Components', shortDesc: 'Recoil pull starters, carburettors, and exhaust mufflers.' },
      { slug: 'engine-accessories', name: 'Engine Accessories', shortDesc: 'Key start switch boxes, battery cables, and low-oil sensors.' },
      { slug: 'engine-controls', name: 'Engine Controls', shortDesc: 'Throttle decelerator cables and auto-idle solenoids.' },
    ],
  },
  {
    slug: 'filters',
    name: 'Filters & Water Treatment',
    shortDesc: 'Inlet water strainers, scale-stop cartridges, suction filters, and filter housings.',
    iconName: 'Filter',
    isFeatured: false,
    subcategories: [
      { slug: 'inlet-filters', name: 'Inlet Filters', shortDesc: 'Clear bowl 3/4" and 1" BSP fresh water supply strainers.' },
      { slug: 'water-filters', name: 'Water Filters', shortDesc: 'Fine-mesh sediment and high-capacity water pre-filters.' },
      { slug: 'replacement-filter-elements', name: 'Replacement Filter Elements', shortDesc: 'Washable stainless mesh and 50-mesh nylon cartridges.' },
      { slug: 'water-regulators', name: 'Water Regulators', shortDesc: 'Mains pressure reducing valves and anti-siphon backflow valves.' },
      { slug: 'water-treatment-components', name: 'Water Treatment Components', shortDesc: 'Scale-Stop coil descaling cartridges and water softeners.' },
      { slug: 'filter-housings', name: 'Filter Housings', shortDesc: 'Heavy-duty polypropylene and aluminium filter bodies.' },
      { slug: 'strainers', name: 'Strainers', shortDesc: 'Brass weighted chemical suction strainers with foot valves.' },
    ],
  },
  {
    slug: 'consumables',
    name: 'Consumables & Service',
    shortDesc: 'Scheduled maintenance kits, Viton seal kits, specialist pump lubricants, and O-ring kits.',
    iconName: 'Package',
    isFeatured: true,
    subcategories: [
      { slug: 'o-rings', name: 'O-Rings', shortDesc: 'Multi-compartment metric and imperial O-ring service boxes.' },
      { slug: 'seals', name: 'Seals', shortDesc: 'High-temperature washer and pump shaft oil seals.' },
      { slug: 'filters', name: 'Filters', shortDesc: 'Consumable filter cartridges and disposable strainers.' },
      { slug: 'oils', name: 'Oils', shortDesc: 'Alkota ISO 220 pump oil, 10W-30 engine oil, and hydraulic fluid.' },
      { slug: 'greases', name: 'Greases', shortDesc: 'High-temperature waterproof reel and bearing grease.' },
      { slug: 'lubricants', name: 'Lubricants', shortDesc: 'Anti-seize compound, silicone O-ring grease, and PTFE thread sealant.' },
      { slug: 'service-kits', name: 'Service Kits', shortDesc: 'Pre-packaged routine service packs by machine model.' },
      { slug: 'maintenance-kits', name: 'Maintenance Kits', shortDesc: 'Multi-point preventative maintenance overhaul packs.' },
      { slug: 'cleaning-accessories', name: 'Cleaning Accessories', shortDesc: 'Nozzle cleaning picks, chemical measuring jugs, and wash mitts.' },
      { slug: 'replacement-consumables', name: 'Replacement Consumables', shortDesc: 'Burst discs, shear pins, and quick-wearing consumables.' },
    ],
  },
];

export function getCategoryBySlug(slug: string): MasterCategory | undefined {
  return MASTER_TAXONOMY.find(c => c.slug === slug);
}

export function getSubcategory(catSlug: string, subSlug: string) {
  const cat = getCategoryBySlug(catSlug);
  if (!cat) return undefined;
  return cat.subcategories.find(s => s.slug === subSlug);
}
