import { ChemicalProduct, ChemicalCategoryDefinition } from '@/lib/types/chemical';

// ─── CANONICAL UK CHEMICAL CATEGORIES ─────────────────────────────────────────

export const CHEMICAL_CATEGORIES: ChemicalCategoryDefinition[] = [
  {
    slug: 'fleet-vehicle',
    name: 'Fleet & Commercial Vehicle',
    title: 'Fleet & Commercial Vehicle Chemistry',
    tagline: 'Engineered road-film penetration, insect residue removal and paintwork protection.',
    description: 'High-throughput commercial transport demands formulations that dissolve electrostatic traffic film and diesel carbon without stripping wax, clouding polished aluminium extrusions, or degrading rubber window seals.',
    applicationScope: ['HGV Haulage Fleets', 'Bus & Coach Operators', 'Plant Delivery Transporters', 'Commercial Vans & Utilities'],
    keyContaminants: ['Electrostatic Road Film', 'Diesel Soot & Exhaust Carbon', 'Insect & Bug Splatter', 'Winter Road Salt & Brine'],
    keySurfaces: ['Automotive Clear Coat', 'Polished Aluminium Tanks', 'Painted Steel Chassis', 'Glass & EPDM Seals'],
    equipmentSynergy: 'Pairs with Alkota 4000 Series Hot Water Washers & Automated Wash Gantry Booms',
    heroImagePlaceholder: 'IMAGE SLOT — FLEET CHEMISTRY // CONTROLLED FOAM APPLIED TO HGV SIDE PANEL',
    badge: 'TRANSPORTATION'
  },
  {
    slug: 'degreasers',
    name: 'Industrial Degreasing',
    title: 'Heavy Industrial Degreasers',
    tagline: 'High-alkaline builders and natural solvent-boosted surfactants for extreme hydrocarbon breakdown.',
    description: 'Targeted emulsification for fifth-wheels, heavy equipment engine bays, gearbox castings, hydraulic reservoirs, and workshop floor slabs. Converts heavy petroleum oils and carbonaceous soils into water-soluble suspensions.',
    applicationScope: ['Engineering Workshops', 'Plant Maintenance Bays', 'Mining & Quarrying Gear', 'Rail & Marine Terminals'],
    keyContaminants: ['Heavy Gear Oil & Grease', 'Hydraulic Fluid Residue', 'Baked-on Carbon & Slag', 'Bitumen & Asphalt Splatter'],
    keySurfaces: ['Structural Mild Steel', 'Cast Iron Machinery', 'Hardened Concrete Floors', 'Heavy Excavator Booms'],
    equipmentSynergy: 'Engineered for Schedule 80 Hot Water Systems delivering 80°C–95°C thermal dissolution',
    heroImagePlaceholder: 'IMAGE SLOT — INDUSTRIAL DEGREASING // MACRO HYDROCARBON SEPARATION FROM MILLED STEEL',
    badge: 'HEAVY HEAVY DUTY'
  },
  {
    slug: 'industrial',
    name: 'Agriculture & Heavy Plant',
    title: 'Agricultural & Earthmoving Chemistry',
    tagline: 'Non-corrosive alkaline builders that strip soil and gently remove oxidised paint layers.',
    description: 'Built specifically for the harsh organic soils, clay, manure acids, and field contamination found across UK agriculture and heavy civil earthmoving machinery. Contains unique paint-restoration agents to keep capital assets looking new.',
    applicationScope: ['Arable & Livestock Farms', 'Contract Harvesting Rigs', 'Civil Earthmoving & Demolition', 'Forestry & Quarry Machinery'],
    keyContaminants: ['Heavy Agricultural Clay', 'Organic Soil & Crop Residue', 'Dried Slurry & Silage Acids', 'Field Mud & Dust Cake'],
    keySurfaces: ['Tractor Enamel Paint', 'Combine Harvester Headers', 'Heavy Galvanised Steel', 'Powder-Coated Agricultural Metal'],
    equipmentSynergy: 'Optimal with Alkota High-Volume Triplex Cold/Hot Water Washers (15–30 L/min)',
    heroImagePlaceholder: 'IMAGE SLOT — AGRICULTURE CHEMISTRY // CONTROLLED PRE-SPRAY ON COMBINE HARVESTER',
    badge: 'AG & EARTHMOVING'
  },
  {
    slug: 'parts-washers',
    name: 'Parts Washing & Metal Treatment',
    title: 'Aqueous Parts Washer & Metal Chemistry',
    tagline: 'Zero-foaming aqueous degreasers, rust inhibitors and phosphating treatments.',
    description: 'Purpose-engineered for automatic turntable parts washers, agitation tanks, and ultrasonic wash cabinets. Formulations operate under high spray pressure without foaming and deposit microscopic corrosion-inhibiting barriers upon drying.',
    applicationScope: ['Engine Reconditioning Shops', 'Transmission & Axle Overhaul', 'Aerospace MRO Workshops', 'Precision CNC Machine Shops'],
    keyContaminants: ['Machining Coolants & Swarf', 'Burnt Engine Oil & Sludge', 'Lapping Paste & Polish Residue', 'Preservative Wax Coatings'],
    keySurfaces: ['Precision Aluminium Heads', 'Mild & Tool Steel Castings', 'Brass & Bronze Bushings', 'Stainless Steel Components'],
    equipmentSynergy: 'Directly matched to Alkota APW Aqueous Automatic Parts Washer Series',
    heroImagePlaceholder: 'IMAGE SLOT — PARTS WASHER CHEMISTRY // HIGH-PRESSURE AQUEOUS JET DEGREASING IN ENCLOSED CABINET',
    badge: 'AQUEOUS PROCESS'
  },
  {
    slug: 'food-processing',
    name: 'Food & Process Hygiene',
    title: 'Food Industry Equipment Chemistry',
    tagline: 'Controlled alkaline detergents for animal fat, protein residue and process grime removal.',
    description: 'Engineered for food processing plants, abattoirs, bottling lines, and commercial bakery equipment. Highly free-rinsing formulations designed to lift stubborn animal tallow, vegetable oils, and starch residues. (Always followed by potable water rinse as directed).',
    applicationScope: ['Abattoirs & Meat Processing', 'Commercial Bakeries & Ovens', 'Dairies & Bottling Plants', 'Fish Processing Stations'],
    keyContaminants: ['Animal Tallow & Rendered Fats', 'Proteinaceous Soil & Blood', 'Caramelised Sugars & Starches', 'Vegetable Oil Build-up'],
    keySurfaces: ['304/316 Food Grade Stainless', 'Polyethylene Cutting Boards', 'Tiled Walls & Epoxied Bays', 'Food Transport Trailers'],
    equipmentSynergy: 'Designed for Alkota Dry Steam Cleaners and Hot Water Washers',
    heroImagePlaceholder: 'IMAGE SLOT — FOOD PROCESSING CHEMISTRY // HIGH DENSITY WASH ON 316 STAINLESS PRODUCTION LINE',
    badge: 'FOOD SECTOR'
  },
  {
    slug: 'specialty',
    name: 'Scale Stop & Machine Care',
    title: 'Equipment Protection & Water Additives',
    tagline: 'Specialist anti-scale chemistry designed to preserve heating coils in hard water zones.',
    description: 'UK tap water in many regions carries high calcium and magnesium carbonates. When heated to 85°C+, these minerals crystallise into rock-hard coil scale that strangles water flow, degrades burner efficiency, and causes coil blowout. Scale Stop chelates minerals on the fly.',
    applicationScope: ['Every Hot Water Pressure Washer', 'Centralised Fixed Wash Plants', 'Steam Cleaner Coil Loops', 'Trailer Mobile Rigs'],
    keyContaminants: ['Calcium Carbonate Scale', 'Magnesium Mineral Fur', 'Iron Oxide Deposit Inside Coils', 'Lime Encrustation'],
    keySurfaces: ['ASTM A53 Schedule 80 Heating Coils', 'Ceramic Plungers & Brass Manifolds', 'High-Pressure Swivels & Unloaders'],
    equipmentSynergy: 'Essential preventative maintenance for all Alkota Hot Water & Steam equipment',
    heroImagePlaceholder: 'IMAGE SLOT — SCALE STOP // CROSS SECTION SHOWING SCALE FREE CONTINUOUS WOUND HEATING COIL',
    badge: 'EQUIPMENT CARE'
  },
  {
    slug: 'masonry',
    name: 'Masonry & Surface Restoration',
    title: 'Masonry, Concrete & Asphalt Chemistry',
    tagline: 'Deep-penetrating restorative chemistry for pavers, architectural stone and concrete.',
    description: 'Removes atmospheric carbon crusting, efflorescence salt blooming, deep fuel stains, and bitumen splatter from civil infrastructure, brickwork, and warehouse concrete pads without attacking surface aggregate.',
    applicationScope: ['Heritage Restoration Contractors', 'Commercial Property Facilities', 'Forecourt & Car Park Maintenance', 'Construction Handover Cleaners'],
    keyContaminants: ['Diesel & Engine Oil Stains', 'Efflorescence & Limescale Blooming', 'Atmospheric Pollution Soot', 'Bitumen & Asphalt Tack Coat'],
    keySurfaces: ['Engineered Concrete Pads', 'Granite & Natural Sandstone', 'Clay Facing Brickwork', 'Tarmacadam & Asphalt'],
    equipmentSynergy: 'Pairs with Alkota Hot Water Washers and Flat Surface Rotary Cleaners',
    heroImagePlaceholder: 'IMAGE SLOT — MASONRY CHEMISTRY // DEEP SURFACE RESTORATION ON AGED CONCRETE SLAB',
    badge: 'SURFACE CARE'
  }
];

// ─── CANONICAL VERIFIED CHEMICAL PRODUCTS ─────────────────────────────────────

export const VERIFIED_CHEMICAL_PRODUCTS: ChemicalProduct[] = [
  // ─── 01. FARM SOAP TR-440 ──────────────────────────────────────────────────
  {
    id: 'chem-tr440',
    slug: 'farm-soap-tr440',
    name: 'Farm Soap TR-440',
    code: 'TR-440',
    category: 'industrial',
    tagline: 'Alkota\'s flagship agricultural & equipment detergent — removes oxidation and renews paint.',
    description: 'Farm Soap TR-440 is the undisputed benchmark for agricultural machinery, civil earthmoving equipment, and heavy transport. Formulated with a proprietary blend of alkaline builders, wetting surfactants, natural citrus solvency, and water-softening agents. TR-440 actively breaks down micro-oxidised surface paint layers on weathered equipment, restoring deep luster while emulsifying caked clay, manure grease, and hydraulic oil.',
    active: true,
    featured: true,
    uk_status: 'published',
    sort_order: 10,
    form: 'Concentrated Liquid',
    appearance: 'Clear Amber Liquid with Subtle Citrus Aroma',
    ph_level: '11.8 – 12.2 (10% Solution)',
    specific_gravity: '1.09 @ 20°C',
    active_ingredients: ['Alkaline Builders', 'Linear Alkyl Surfactants', 'd-Limonene Citrus Fraction', 'Chelating Scale Inhibitor'],
    voc_content: 'Low VOC (<15 g/L)',
    biodegradability_claim: 'Readily Biodegradable — OECD 301B compliant surfactant package',
    biodegradable: true,
    hazardous: false,
    food_safe: false,
    food_process_status: 'non_food',
    use_cases: ['Tractors & Combines', 'Heavy Excavators & Loading Shovels', 'Agricultural Trailers & Implements', 'Grain Processing Plant', 'Chassis Pre-Moisturising'],
    compatible_surfaces: ['Painted Mild Steel', 'Powder-Coated Agricultural Panels', 'Cast Iron Frames', 'Heavy Galvanised Steel', 'Tough Vehicle Enamels'],
    not_suitable_for: ['Polished Unlacquered Aluminium', 'Magnesium Alloy Components'],
    contamination_types: ['Heavy Agricultural Soil & Clay', 'Manure & Slurry Organic Residues', 'Hydraulic Oil & Grease', 'Faded Oxidised Paint Micro-Films', 'Road Salt & Dust Grime'],
    application_methods: ['Hot Water Pressure Washer Downstream Injector', 'Low-Pressure Foam Cannon Pre-Spray', 'Manual Brush Wash Application', 'Cold Water Pressure Washer'],
    compatible_equipment_types: ['Hot Water Pressure Washers', 'Cold Water High-Volume Units', 'Trailer Rigs', 'Foam Lances'],
    dilution_hot: '1:50 to 1:120 (approx. 10–20 ml per litre)',
    dilution_cold: '1:30 to 1:80 (approx. 15–30 ml per litre)',
    surface_notes: 'Safe for modern tractor finishes and baked enamels. Do not allow to dry in direct sunlight on bare polished aluminium.',
    application_notes: 'Apply from the bottom up to prevent streaking. Allow 3–5 minutes dwell time before rinsing from the top down with high-pressure hot water (70°C+).',
    water_recovery_compatible: true,
    separator_compatible: true,
    recycling_compatible: true,
    water_recovery_notes: 'Quick-release surfactant chemistry allows free hydrocarbons to separate cleanly in standard coalescing oil-water separators.',
    storage_notes: 'Store in original tightly closed container above 5°C. Keep out of direct frost.',
    shelf_life: '24 Months when stored under ambient warehouse conditions (5°C–25°C)',
    available_sizes: ['5L Container', '25L Heavy Duty Drum', '200L Steel/Poly Drum', '1000L Intermediate Bulk Container (IBC)'],
    price_5l: 22.50,
    price_25l: 85.00,
    price_200l: 340.00,
    price_1000l: 1450.00,
    manufacturer: 'Hydrus Detergents / Alkota Cleaning Systems',
    country_of_origin: 'USA / UK Packaged',
    features: [
      'Paint-restoration technology micro-cleans faded surface oxidation',
      'Integrated scale inhibitor protects Schedule 80 heating coils',
      'Free-rinsing formulation leaves zero powdery streak marks',
      'Fast-acting citrus solvency accelerates cold-water grease dissolution'
    ],
    hazard_classification: 'Skin Irrit. 2; Eye Irrit. 2 (GB CLP / UK REACH)',
    signal_word: 'WARNING',
    hazard_pictograms: ['exclamation'],
    hazard_statements: [
      'H315: Causes skin irritation',
      'H319: Causes serious eye irritation'
    ],
    precautionary_statements: [
      'P264: Wash skin thoroughly after handling',
      'P280: Wear protective gloves and eye/face protection',
      'P305+P351+P338: IF IN EYES: Rinse cautiously with water for several minutes',
      'P337+P313: If eye irritation persists: Get medical advice/attention'
    ],
    sds_url: '/documents/sds/alkota-sds-tr440-farm-soap.pdf',
    sds_revision_date: '14 January 2024 (Rev 4.1)',
    tds_url: '/documents/tds/alkota-tds-tr440-farm-soap.pdf',
    tds_revision_date: '02 March 2024',
    label_url: '/documents/labels/alkota-label-tr440.pdf',
    primary_image_url: '/assets/products/tr440-farm-soap.png',
    image_url: '/assets/products/tr440-farm-soap.png',
    media_status: 'media_verified',
    meta_title: 'Farm Soap TR-440 | Agricultural & Heavy Machinery Cleaner UK | Alkota',
    meta_description: 'Alkota TR-440 Farm Soap is the UK\'s premier agricultural detergent. Penetrates heavy clay, manure, and oil while restoring oxidised equipment paint.'
  },

  // ─── 02. GREASE CUTTER DE-703 ──────────────────────────────────────────────
  {
    id: 'chem-de703',
    slug: 'grease-cutter-de703',
    name: 'Grease Cutter DE-703',
    code: 'DE-703',
    category: 'degreasers',
    tagline: 'High-alkaline hydrocarbon dissolver for fifth wheels, engine blocks and industrial grease.',
    description: 'Grease Cutter DE-703 is a concentrated industrial degreaser engineered to attack heavy grease, crude oil residues, bitumen, and carbon deposits on contact. Formulated with synergistic solvent-boosted surfactants that penetrate dense hydrocarbon sludge, creating a chemical barrier that prevents soil redeposition during high-pressure washdown. Rinses cleanly with hot or cold water.',
    active: true,
    featured: true,
    uk_status: 'published',
    sort_order: 20,
    form: 'Concentrated Liquid',
    appearance: 'Clear Fluorescent Green Liquid',
    ph_level: '12.8 – 13.2 (Concentrate)',
    specific_gravity: '1.07 @ 20°C',
    active_ingredients: ['Potassium Hydroxide Builders', 'Solvent-Coupled Surfactants', 'Soil Penetration Promoters'],
    voc_content: 'Low VOC (<25 g/L)',
    biodegradability_claim: 'Readily Biodegradable Surfactant Base (OECD 301D)',
    biodegradable: true,
    hazardous: true,
    food_safe: false,
    food_process_status: 'non_food',
    use_cases: ['HGV Fifth-Wheel Couplings', 'Diesel Engine Blocks & Sump Pans', 'Forklift Mast Chains & Carriages', 'Drilling Rig Substructures', 'Plant Workshop Concrete Pits'],
    compatible_surfaces: ['Heavy Carbon Steel', 'Cast Iron Machine Blocks', 'Industrial Concrete Floors', 'Epoxy Floor Coatings'],
    not_suitable_for: ['Polished Aluminium Wheels', 'Soft Aluminium Panels', 'Galvanised Metal (Prolonged Contact)'],
    contamination_types: ['Heavy Mineral Grease & Pitch', 'Burnt Engine Oil & Sludge', 'Bitumen & Asphalt Tack', 'Brake Carbon & Tramp Oils'],
    application_methods: ['Hot Water Pressure Washer Chemical Injector', 'Manual Pre-Sprayer (5–10 min dwell)', 'Immersion Soak Tank'],
    compatible_equipment_types: ['Alkota Hot Water Washers', 'Alkota Steam Cleaners', 'Portable Pre-Spray Units'],
    dilution_hot: '1:30 to 1:60 for severe grease; 1:80 for general degreasing',
    dilution_cold: '1:15 to 1:30 (apply as pre-spray for best results)',
    surface_notes: 'Not recommended for prolonged contact on unlacquered aluminium. Test in an inconspicuous area on sensitive coatings.',
    application_notes: 'For heavy fifth-wheel grease, pre-spray neat to 1:5, dwell for 5 minutes, then blast off with 90°C hot water at 200 BAR.',
    water_recovery_compatible: true,
    separator_compatible: true,
    recycling_compatible: false,
    water_recovery_notes: 'Formulated to release emulsified oils in standard coalescing separators within 30 minutes of retention time.',
    storage_notes: 'Store upright in original container away from strong acids and oxidisers.',
    shelf_life: '24 Months',
    available_sizes: ['5L Container', '25L Heavy Duty Drum', '200L Poly Drum', '1000L IBC'],
    price_5l: 26.00,
    price_25l: 96.00,
    price_200l: 375.00,
    price_1000l: 1580.00,
    manufacturer: 'Hydrus Detergents / Alkota Cleaning Systems',
    country_of_origin: 'USA / UK Formulated',
    features: [
      'Fast-acting penetration dissolves dried fifth-wheel grease and tar',
      'Non-redeposition chemistry ensures clean rinse without oil slick backwash',
      'Optimised for thermal activation in 80°C–95°C hot water washers',
      'Corrosion inhibitors protect bare steel surfaces post-wash'
    ],
    hazard_classification: 'Skin Corr. 1B; Eye Dam. 1 (GB CLP / UK REACH)',
    signal_word: 'DANGER',
    hazard_pictograms: ['corrosive'],
    hazard_statements: [
      'H314: Causes severe skin burns and eye damage',
      'H318: Causes serious eye damage'
    ],
    precautionary_statements: [
      'P260: Do not breathe mists/spray',
      'P280: Wear protective gloves, protective clothing and eye/face protection',
      'P301+P330+P331: IF SWALLOWED: Rinse mouth. Do NOT induce vomiting',
      'P303+P361+P353: IF ON SKIN: Take off immediately all contaminated clothing. Rinse skin with water',
      'P305+P351+P338: IF IN EYES: Rinse cautiously with water for several minutes'
    ],
    sds_url: '/documents/sds/alkota-sds-de703-grease-cutter.pdf',
    sds_revision_date: '08 February 2024 (Rev 3.2)',
    tds_url: '/documents/tds/alkota-tds-de703-grease-cutter.pdf',
    tds_revision_date: '10 February 2024',
    label_url: '/documents/labels/alkota-label-de703.pdf',
    primary_image_url: '/assets/products/de703-grease-cutter.png',
    image_url: '/assets/products/de703-grease-cutter.png',
    media_status: 'media_verified',
    meta_title: 'Grease Cutter DE-703 | Industrial Heavy Duty Degreaser UK | Alkota',
    meta_description: 'Industrial alkaline degreaser DE-703 dissolves heavy fifth-wheel grease, bitumen, and oil on machinery and workshop floors with Alkota hot water washers.'
  },

  // ─── 03. POWER BLAST TR-407 ───────────────────────────────────────────────
  {
    id: 'chem-tr407',
    slug: 'power-blast-tr407',
    name: 'Power Blast TR-407',
    code: 'TR-407',
    category: 'fleet-vehicle',
    tagline: 'All-round commercial fleet & HGV wash — safe across paint, glass, and polished metal.',
    description: 'Power Blast TR-407 is the foundational fleet detergent for high-volume commercial vehicle operations. Engineered to dissolve stubborn electrostatic road film, diesel soot, and bug residue without damaging vehicle clear coats, polished aluminium trim, or window rubbers. 100% biodegradable and free-rinsing, leaving an exceptionally clean, streak-free surface.',
    active: true,
    featured: true,
    uk_status: 'published',
    sort_order: 30,
    form: 'Concentrated Liquid',
    appearance: 'Clear Blue Liquid',
    ph_level: '9.5 – 10.2 (Balanced Alkaline)',
    specific_gravity: '1.04 @ 20°C',
    active_ingredients: ['Biodegradable Wetting Agents', 'Anti-Static Surfactants', 'Water Conditioners'],
    voc_content: 'Zero VOC (<1 g/L)',
    biodegradability_claim: '100% Readily Biodegradable (OECD 301B)',
    biodegradable: true,
    hazardous: false,
    food_safe: false,
    food_process_status: 'non_food',
    use_cases: ['HGV Haulage Fleets & Box Trailers', 'Commercial Delivery Vans', 'Bus & Coach Public Transport', 'Municipal Fleet Vehicles'],
    compatible_surfaces: ['Automotive Vehicle Paintwork', 'Commercial Polyurethane Finishes', 'Polished Aluminium Wheels & Tanks', 'Glass & Mirror Systems', 'Rubber & Plastic Body Trims'],
    not_suitable_for: [],
    contamination_types: ['Electrostatic Traffic Film', 'Diesel Exhaust Smoke Stains', 'Bug & Insect Splatter', 'Winter Salt & Grime Slush'],
    application_methods: ['Downstream Chemical Injector (Hot/Cold)', 'Low-Pressure Foam Arch / Lance', 'Drive-Through Fleet Wash Gantries', 'Hand Wash Sponge / Brush'],
    compatible_equipment_types: ['Hot Water Pressure Washers', 'Cold Water Washers', 'Alkota Wash Trailers', 'Gantry Systems'],
    dilution_hot: '1:60 to 1:120',
    dilution_cold: '1:40 to 1:80',
    surface_notes: 'Fully aluminium-safe at directed dilution rates. Excellent gloss retention on modern clear coats.',
    application_notes: 'Apply via foam lance or injector from bottom up. Dwell 2–3 minutes without allowing to dry, then rinse from top to bottom.',
    water_recovery_compatible: true,
    separator_compatible: true,
    recycling_compatible: true,
    water_recovery_notes: 'Designed specifically for compatibility with water recycling systems and automated wash bays.',
    storage_notes: 'Keep from freezing. Store between 5°C and 30°C.',
    shelf_life: '36 Months',
    available_sizes: ['5L Container', '25L Heavy Duty Drum', '200L Poly Drum', '1000L IBC'],
    price_5l: 19.50,
    price_25l: 76.00,
    price_200l: 295.00,
    price_1000l: 1280.00,
    manufacturer: 'Hydrus Detergents / Alkota Cleaning Systems',
    country_of_origin: 'USA / UK Formulated',
    features: [
      'Electrostatic film neutralisation lifts traffic film with minimal brushing',
      'Polished aluminium and clear coat safe across all commercial brands',
      'Ultra-dense foam clinging action extends chemical contact dwell time',
      '100% biodegradable and compatible with water reclamation loops'
    ],
    hazard_classification: 'Eye Irrit. 2 (GB CLP / UK REACH)',
    signal_word: 'WARNING',
    hazard_pictograms: ['exclamation'],
    hazard_statements: [
      'H319: Causes serious eye irritation'
    ],
    precautionary_statements: [
      'P264: Wash hands thoroughly after handling',
      'P280: Wear eye protection',
      'P305+P351+P338: IF IN EYES: Rinse cautiously with water for several minutes',
      'P337+P313: If eye irritation persists: Get medical advice/attention'
    ],
    sds_url: '/documents/sds/alkota-sds-tr407-power-blast.pdf',
    sds_revision_date: '20 January 2024 (Rev 5.0)',
    tds_url: '/documents/tds/alkota-tds-tr407-power-blast.pdf',
    tds_revision_date: '22 January 2024',
    label_url: '/documents/labels/alkota-label-tr407.pdf',
    primary_image_url: '/assets/products/truck-plant-wash.png',
    image_url: '/assets/products/truck-plant-wash.png',
    media_status: 'media_verified',
    meta_title: 'Power Blast TR-407 | Commercial HGV & Fleet Wash Detergent UK | Alkota',
    meta_description: 'Alkota TR-407 Power Blast vehicle wash dissolves road film, bugs, and diesel carbon without damaging paint, polished aluminium, or seals.'
  },

  // ─── 04. TOUCHLESS TR-470 ──────────────────────────────────────────────────
  {
    id: 'chem-tr470',
    slug: 'touchless-tr470',
    name: 'Touchless TR-470',
    code: 'TR-470',
    category: 'fleet-vehicle',
    tagline: 'High-performance touchless vehicle wash — road film elimination with zero brush contact.',
    description: 'Touchless TR-470 is formulated specifically for operators who want high-gloss wash quality without physical brush contact. Its advanced surfactant formulation breaks the electrical bond between traffic film and painted bodywork, allowing road film, bug proteins, and salt crust to slide away during a high-pressure rinse.',
    active: true,
    featured: false,
    uk_status: 'published',
    sort_order: 40,
    form: 'Concentrated Liquid',
    appearance: 'Clear Straw-Coloured Liquid',
    ph_level: '10.5 – 11.0 (Mild Alkaline)',
    specific_gravity: '1.06 @ 20°C',
    active_ingredients: ['Ionic & Non-Ionic Surfactants', 'Sequestering Agents', 'Optical Brighteners'],
    voc_content: 'Low VOC (<5 g/L)',
    biodegradability_claim: 'Readily Biodegradable (OECD 301B)',
    biodegradable: true,
    hazardous: false,
    food_safe: false,
    food_process_status: 'non_food',
    use_cases: ['Touchless Drive-Through Fleet Bays', 'Curtainsider HGV Cleaning', 'Livery Protected Vans & Tankers', 'Fleet Yards with Limited Brush Labour'],
    compatible_surfaces: ['Vinyl Fleet Liveries & Wraps', 'Commercial Vehicle Enamels', 'Aluminium Extrusions', 'FRP Box Panels'],
    not_suitable_for: [],
    contamination_types: ['Electrostatic Traffic Film', 'Diesel Exhaust Staining', 'Tree Sap & Organic Spores', 'Road De-icing Salts'],
    application_methods: ['High-Pressure Foam Cannon / Lance', 'Drive-Through Automated Arch', 'Low-Pressure Chemical Sprayer'],
    compatible_equipment_types: ['Hot Water Pressure Washers', 'Cold Water Washers', 'Automated Wash Plants'],
    dilution_hot: '1:40 to 1:80',
    dilution_cold: '1:20 to 1:50',
    surface_notes: 'Safe for commercial vinyl wraps, decals, and reflective chevron markings.',
    application_notes: 'Apply dense foam evenly across dry vehicle panels. Allow 3–4 minutes dwell time. Rinse off with minimum 130 BAR at 45° angle.',
    water_recovery_compatible: true,
    separator_compatible: true,
    recycling_compatible: true,
    water_recovery_notes: 'Low chemical dragout; compatible with standard wash-pad interceptors.',
    storage_notes: 'Store above 5°C in original container.',
    shelf_life: '24 Months',
    available_sizes: ['25L Drum', '200L Drum', '1000L IBC'],
    price_25l: 88.00,
    price_200l: 345.00,
    price_1000l: 1490.00,
    manufacturer: 'Hydrus Detergents / Alkota Cleaning Systems',
    country_of_origin: 'USA / UK Formulated',
    features: [
      'Eliminates brush swirl marks and livery abrasion on new commercial fleets',
      'Safe for aluminium tanks, steps, mirrors, and reflective safety chevrons',
      'Leaves water-repelling sheen that slows down future road-film buildup'
    ],
    hazard_classification: 'Skin Irrit. 2; Eye Irrit. 2 (GB CLP / UK REACH)',
    signal_word: 'WARNING',
    hazard_pictograms: ['exclamation'],
    hazard_statements: [
      'H315: Causes skin irritation',
      'H319: Causes serious eye irritation'
    ],
    precautionary_statements: [
      'P280: Wear protective gloves and eye protection',
      'P305+P351+P338: IF IN EYES: Rinse cautiously with water for several minutes'
    ],
    sds_url: '/documents/sds/alkota-sds-tr470-touchless.pdf',
    sds_revision_date: '04 February 2024',
    tds_url: '/documents/tds/alkota-tds-tr470-touchless.pdf',
    tds_revision_date: '04 February 2024',
    label_url: '/documents/labels/alkota-label-tr470.pdf',
    primary_image_url: '/assets/products/auto-shampoo.png',
    image_url: '/assets/products/auto-shampoo.png',
    media_status: 'media_verified',
    meta_title: 'Touchless TR-470 | Commercial Vehicle Wash UK | Alkota',
    meta_description: 'Touchless vehicle wash detergent TR-470 dissolves traffic film without brushing. Safe on vinyl wraps, liveries, and aluminium.'
  },

  // ─── 05. SUPER LUSTER TR-600 ───────────────────────────────────────────────
  {
    id: 'chem-tr600',
    slug: 'super-luster-tr600',
    name: 'Super Luster TR-600',
    code: 'TR-600',
    category: 'fleet-vehicle',
    tagline: 'Heavy-duty commercial tanker and stainless transporter wash with optical brightening.',
    description: 'A heavy-duty transport cleaner formulated for road tankers, bulk powder trailers, garbage vehicles, and mining support transports. Built with sodium hydroxide, natural citrus degreasers, and wetting agents to tackle the most stubborn road films while leaving a streak-free optical shine on stainless steel and painted bodywork.',
    active: true,
    featured: true,
    uk_status: 'published',
    sort_order: 50,
    form: 'Concentrated Liquid',
    appearance: 'Clear Amber Solution',
    ph_level: '12.5 – 13.0',
    specific_gravity: '1.08 @ 20°C',
    active_ingredients: ['Sodium Hydroxide', 'Citrus Solvents', 'Surface Brighteners'],
    voc_content: 'Low VOC (<20 g/L)',
    biodegradability_claim: 'Biodegradable Surfactants',
    biodegradable: true,
    hazardous: true,
    food_safe: false,
    food_process_status: 'non_food',
    use_cases: ['Stainless Steel Liquid Road Tankers', 'Bulk Powder & Cement Tankers', 'Refuse Collection Vehicles', 'Quarry & Earthmoving Transports'],
    compatible_surfaces: ['304/316 Stainless Steel', 'Heavy Industrial Enamel', 'Hardened Steel Chassis'],
    not_suitable_for: ['Polished Raw Aluminium', 'Magnesium Castings', 'Soft Anodised Trims'],
    contamination_types: ['Baked Diesel Soot', 'Heavy Road Grime & Tar', 'Cement Powder Dust Film', 'Mineral Slurry Residues'],
    application_methods: ['Downstream Hot Water Injector', 'Low-Pressure Pre-Sprayer'],
    compatible_equipment_types: ['Hot Water Pressure Washers', 'Stationary Wash Gantries'],
    dilution_hot: '1:50 to 1:100',
    dilution_cold: '1:30 to 1:60',
    surface_notes: 'Optimised for stainless steel tankers. Do not apply neat to unlacquered aluminium surfaces.',
    application_notes: 'Pre-spray onto dirty panels, allow 3 minutes dwell time, and wash away using 80°C hot water for instant gleam.',
    water_recovery_compatible: true,
    separator_compatible: true,
    recycling_compatible: false,
    water_recovery_notes: 'Suitable for wash pads with standard oil-water separation equipment.',
    storage_notes: 'Store in cool, well-ventilated area away from acids.',
    shelf_life: '24 Months',
    available_sizes: ['25L Drum', '200L Drum', '1000L IBC'],
    price_25l: 92.00,
    price_200l: 360.00,
    price_1000l: 1520.00,
    manufacturer: 'Hydrus Detergents / Alkota Cleaning Systems',
    country_of_origin: 'USA / UK Formulated',
    features: [
      'Optical brighteners create mirror reflection on stainless transport tanks',
      'Removes baked-on diesel smoke and industrial road fallout',
      'Formulated for extreme duty on garbage and municipal fleets'
    ],
    hazard_classification: 'Skin Corr. 1B; Eye Dam. 1 (GB CLP / UK REACH)',
    signal_word: 'DANGER',
    hazard_pictograms: ['corrosive'],
    hazard_statements: [
      'H314: Causes severe skin burns and eye damage'
    ],
    precautionary_statements: [
      'P280: Wear protective gloves and eye/face protection',
      'P301+P330+P331: IF SWALLOWED: Rinse mouth. Do NOT induce vomiting',
      'P305+P351+P338: IF IN EYES: Rinse cautiously with water for several minutes'
    ],
    sds_url: '/documents/sds/alkota-sds-tr600-super-luster.pdf',
    sds_revision_date: '18 January 2024',
    tds_url: '/documents/tds/alkota-tds-tr600-super-luster.pdf',
    tds_revision_date: '18 January 2024',
    label_url: '/documents/labels/alkota-label-tr600.pdf',
    primary_image_url: '/assets/products/truck-plant-wash.png',
    image_url: '/assets/products/truck-plant-wash.png',
    media_status: 'media_verified',
    meta_title: 'Super Luster TR-600 | Tanker & Heavy Fleet Wash UK | Alkota',
    meta_description: 'TR-600 Super Luster heavy duty transporter wash delivers streak-free shine on stainless tankers and heavy commercial fleets.'
  },

  // ─── 06. APW PRO CLEAN ─────────────────────────────────────────────────────
  {
    id: 'chem-apw-proclean',
    slug: 'apw-pro-clean',
    name: 'APW Pro Clean',
    code: 'APW-PC',
    category: 'parts-washers',
    tagline: 'Multi-metal aqueous parts washer detergent — low foaming with 60-day flash rust inhibition.',
    description: 'APW Pro Clean is an engineered aqueous detergent developed specifically for automatic rotary parts washers and immersion wash tanks. Formulated with low-foaming surfactants that remain stable under 10+ BAR mechanical spray pressures at 60°C–80°C. Delivers rapid degreasing of aluminium cylinder heads, cast iron blocks, and brass valves while leaving a microscopic corrosion-inhibiting monolayer that protects bare ferrous components from flash rusting for up to 60 days.',
    active: true,
    featured: true,
    uk_status: 'published',
    sort_order: 60,
    form: 'Concentrated Liquid / Powder Option',
    appearance: 'Clear Pale Amber Liquid',
    ph_level: '9.2 – 9.8 (Multi-Metal Safe Alkaline)',
    specific_gravity: '1.05 @ 20°C',
    active_ingredients: ['Non-Foaming Surfactants', 'Vapour Phase Rust Inhibitors', 'Silicate-Free Buffers'],
    voc_content: 'Zero VOC (<1 g/L)',
    biodegradability_claim: '100% Readily Biodegradable (OECD 301B)',
    biodegradable: true,
    hazardous: false,
    food_safe: false,
    food_process_status: 'non_food',
    use_cases: ['Automatic Turntable Parts Washers', 'Ultrasonic Cleaning Tanks', 'Manual Soak Degreasing Vats', 'Engine Rebuild Workshops', 'Aerospace Component Maintenance'],
    compatible_surfaces: ['Cast & Billet Aluminium', 'Mild & Alloy Tool Steels', 'Cast Iron Engine Blocks', 'Brass, Copper & Bronze Bushings', 'Synthetic Rubber O-Rings'],
    not_suitable_for: [],
    contamination_types: ['Synthetic & Mineral Engine Oils', 'Machining Coolants & Fine Swarf', 'Heavy Gear Lube & Carbon Slag', 'Grinding Pastes & Polish Greases'],
    application_methods: ['Automatic Parts Washer Tank Charge (5–10% Vol)', 'Immersion Soak Tank with Agitation', 'Ultrasonic Bath at 50°C–70°C'],
    compatible_equipment_types: ['Alkota APW Automatic Parts Washers', 'Heated Soak Tanks', 'Ultrasonic Units'],
    dilution_hot: '3% to 8% concentration by volume in water reservoir (approx. 1:12 to 1:30)',
    dilution_cold: '5% to 10% concentration',
    surface_notes: '100% safe on soft aluminium alloys, brass, and bronze. Will not etch or discolour precision machined surfaces.',
    application_notes: 'Charge tank with water, add APW Pro Clean, and set heater to 60°C–75°C. Run standard 10–15 minute wash cycle.',
    water_recovery_compatible: true,
    separator_compatible: true,
    recycling_compatible: true,
    water_recovery_notes: 'Closed-loop tank formulation; works with disc skimmers and coalescing tramp-oil separators.',
    storage_notes: 'Store in dry area above 0°C.',
    shelf_life: '36 Months',
    available_sizes: ['25L Drum', '200L Poly Drum', '20kg Powder Tub'],
    price_25l: 98.00,
    price_200l: 390.00,
    manufacturer: 'Hydrus Detergents / Alkota Cleaning Systems',
    country_of_origin: 'USA / UK Formulated',
    features: [
      'Non-foaming at high spray pressures above 45°C',
      'Multi-metal compatibility protects aluminium heads and bronze bearings',
      'Provides up to 60 days flash rust protection on bare cast iron inside workshop',
      'Splits free tramp oils to surface for easy disc skimmer removal'
    ],
    hazard_classification: 'Eye Irrit. 2 (GB CLP / UK REACH)',
    signal_word: 'WARNING',
    hazard_pictograms: ['exclamation'],
    hazard_statements: [
      'H319: Causes serious eye irritation'
    ],
    precautionary_statements: [
      'P280: Wear eye protection',
      'P305+P351+P338: IF IN EYES: Rinse cautiously with water for several minutes'
    ],
    sds_url: '/documents/sds/alkota-sds-apw-pro-clean.pdf',
    sds_revision_date: '12 January 2024 (Rev 4.0)',
    tds_url: '/documents/tds/alkota-tds-apw-pro-clean.pdf',
    tds_revision_date: '15 January 2024',
    label_url: '/documents/labels/alkota-label-apw-proclean.pdf',
    primary_image_url: '/assets/products/food-safe-cleaner.png',
    image_url: '/assets/products/food-safe-cleaner.png',
    media_status: 'media_verified',
    meta_title: 'APW Pro Clean | Aqueous Parts Washer Detergent UK | Alkota',
    meta_description: 'Non-foaming aqueous parts washer detergent APW Pro Clean cleans aluminium and cast iron without corrosion. 60-day flash rust protection.'
  },

  // ─── 07. SCALE STOP COIL PROTECTOR ─────────────────────────────────────────
  {
    id: 'chem-scale-stop',
    slug: 'scale-stop-coil-protector',
    name: 'Scale Stop Coil Protector',
    code: 'Scale Stop',
    category: 'specialty',
    tagline: 'Chemicially binds calcium and magnesium carbonates to prevent heating coil burnout.',
    description: 'Much of the UK sits on hard to very hard water chalk aquifers. When water is heated beyond 65°C inside high-pressure Schedule 80 coils, dissolved calcium and magnesium carbonates precipitate out into dense rock-hard limescale. This scale insulates the coil interior, causing severe hot spots, restricted flow, higher burner fuel consumption, and premature coil burnout. Scale Stop is a proprietary liquid conditioning additive that sequesters hard water minerals, keeping them in suspension through the burner loop.',
    active: true,
    featured: true,
    uk_status: 'published',
    sort_order: 70,
    form: 'Liquid Additive',
    appearance: 'Clear Colourless Liquid',
    ph_level: '7.0 – 7.5 (Neutral)',
    specific_gravity: '1.12 @ 20°C',
    active_ingredients: ['Polyphosphates', 'Polymer Dispersants', 'Metal Passivators'],
    voc_content: 'Zero VOC',
    biodegradability_claim: 'Non-persistent, Environmentally Neutral',
    biodegradable: true,
    hazardous: false,
    food_safe: false,
    food_process_status: 'non_food',
    use_cases: ['All Alkota Hot Water Pressure Washers', 'Dry Steam Cleaners', 'Central Boiler Wash Systems', 'Mobile Trailer Wash Units'],
    compatible_surfaces: ['Schedule 80 ASTM A53 Carbon Steel Coils', 'Stainless Steel Heat Exchangers', 'Ceramic Triplex Plungers', 'Brass Pump Heads'],
    not_suitable_for: [],
    contamination_types: ['Calcium Carbonate Limescale', 'Magnesium Mineral Encrustation', 'Internal Thermal Hot-Spot Slag'],
    application_methods: ['Automatic Chemical Float Tank Injection', 'Direct Dosing to Machine Water Tank', 'Continuous Metering Pump'],
    compatible_equipment_types: ['All Alkota Hot Water Machines', 'All Alkota Steamers', 'Bespoke Trailers'],
    dilution_hot: 'Continuous metering at approx. 1:1000 to 1:2000 (approx. 50–100 ml per 100 litres water)',
    dilution_cold: 'Not required for cold water operation',
    surface_notes: 'Protects internal metallurgy. Harmless to vehicle paintwork and downstream cleaning targets.',
    application_notes: 'Fill the integrated anti-scale reservoir on your Alkota machine or add directly to the header tank at the start of each operating shift.',
    water_recovery_compatible: true,
    separator_compatible: true,
    recycling_compatible: true,
    water_recovery_notes: 'Neutral chemistry does not interfere with oil-water separation or biological filter beds.',
    storage_notes: 'Store above 0°C in original container.',
    shelf_life: '36 Months',
    available_sizes: ['5L Container', '25L Heavy Duty Drum'],
    price_5l: 24.00,
    price_25l: 92.00,
    manufacturer: 'Hydrus Detergents / Alkota Cleaning Systems',
    country_of_origin: 'USA / UK Formulated',
    features: [
      'Preserves 7-Year Alkota coil warranty in designated hard water counties',
      'Maintains 90%+ thermal heat-transfer efficiency from burner to water stream',
      'Prevents expensive machine downtime and premature burner failure',
      'Neutral pH formula is non-corrosive to pumps, brass valves, and high-pressure hoses'
    ],
    hazard_classification: 'Non-Hazardous according to GB CLP regulations',
    signal_word: 'NONE',
    hazard_pictograms: [],
    hazard_statements: [],
    precautionary_statements: [
      'P102: Keep out of reach of children',
      'P262: Do not get in eyes, on skin, or on clothing'
    ],
    sds_url: '/documents/sds/alkota-sds-scale-stop.pdf',
    sds_revision_date: '02 January 2024 (Rev 6.0)',
    tds_url: '/documents/tds/alkota-tds-scale-stop.pdf',
    tds_revision_date: '02 January 2024',
    label_url: '/documents/labels/alkota-label-scale-stop.pdf',
    primary_image_url: '/assets/products/scale-stop.png',
    image_url: '/assets/products/scale-stop.png',
    media_status: 'media_verified',
    meta_title: 'Scale Stop Coil Protector | Hard Water Pressure Washer Additive UK | Alkota',
    meta_description: 'Protect your pressure washer coil from hard water limescale. Alkota Scale Stop prevents coil burnout and preserves heating efficiency.'
  },

  // ─── 08. CITRUS BLAST DE-721 ───────────────────────────────────────────────
  {
    id: 'chem-de721',
    slug: 'citrus-blast-de721',
    name: 'Citrus Blast DE-721',
    code: 'DE-721',
    category: 'degreasers',
    tagline: 'Neutral pH natural citrus degreaser — green, powerful, and safe on polished metals.',
    description: 'A chemically neutral, non-acid, non-alkaline heavy duty degreaser powered by concentrated natural citrus terpenes. Releases natural solvency to break down hydrocarbon grease, adhesive residues, and bitumen without attacking polished aluminium, sensitive copper, brass, or painted surfaces. Widely utilised across facilities where aggressive alkaline chemicals are prohibited by environmental or discharge permits.',
    active: true,
    featured: false,
    uk_status: 'published',
    sort_order: 80,
    form: 'Concentrated Liquid',
    appearance: 'Clear Golden Liquid with Fresh Orange Scent',
    ph_level: '7.0 – 7.5 (Neutral)',
    specific_gravity: '0.98 @ 20°C',
    active_ingredients: ['High Purity d-Limonene', 'Non-Ionic Surfactants', 'Natural Emulsifiers'],
    voc_content: 'Medium VOC (Natural Terpenes)',
    biodegradability_claim: '100% Readily Biodegradable (OECD 301B)',
    biodegradable: true,
    hazardous: false,
    food_safe: false,
    food_process_status: 'rinse_required',
    use_cases: ['Polished Aluminium Tanker Degreasing', 'Food Preparation Equipment (Rinse after)', 'Architectural Cladding & Signs', 'Engineering Workbenches & Tools'],
    compatible_surfaces: ['Mirror Polished Aluminium', 'Stainless Steel', 'Anodised Metal & Brass', 'Painted Glass & Composites'],
    not_suitable_for: [],
    contamination_types: ['Heavy Grease & Industrial Oils', 'Adhesive Tape & Decal Glue Residue', 'Bitumen & Asphalt Splatter', 'Food Fats & Grease Films'],
    application_methods: ['Pre-Spray Manual Trigger / Pump', 'Hot Water Pressure Washer', 'Cold Water Wash'],
    compatible_equipment_types: ['Hot Water Pressure Washers', 'Cold Water Washers'],
    dilution_hot: '1:30 to 1:80',
    dilution_cold: '1:10 to 1:40 (or neat for stubborn tar)',
    surface_notes: '100% safe on mirror polished aluminium and delicate decorative metals.',
    application_notes: 'Spray directly on contamination, allow 3–5 minutes for citrus solvency to penetrate, then rinse away.',
    water_recovery_compatible: true,
    separator_compatible: true,
    recycling_compatible: true,
    water_recovery_notes: 'Natural citrus fraction separates rapidly in water recovery settlement tanks.',
    storage_notes: 'Store in cool dry place away from heat and open flame.',
    shelf_life: '24 Months',
    available_sizes: ['5L Container', '25L Heavy Duty Drum', '200L Drum'],
    price_5l: 28.00,
    price_25l: 110.00,
    price_200l: 420.00,
    manufacturer: 'Hydrus Detergents / Alkota Cleaning Systems',
    country_of_origin: 'USA / UK Formulated',
    features: [
      'Natural citrus solvent dissolves grease without alkaline caustic attack',
      'Completely safe for polished aluminium, chrome, and unlacquered wheels',
      'Fresh natural orange scent improves operator working environment in enclosed areas'
    ],
    hazard_classification: 'Skin Sens. 1; Eye Irrit. 2 (GB CLP / UK REACH)',
    signal_word: 'WARNING',
    hazard_pictograms: ['exclamation'],
    hazard_statements: [
      'H317: May cause an allergic skin reaction',
      'H319: Causes serious eye irritation'
    ],
    precautionary_statements: [
      'P280: Wear protective gloves and eye protection',
      'P302+P352: IF ON SKIN: Wash with plenty of water'
    ],
    sds_url: '/documents/sds/alkota-sds-de721-citrus-blast.pdf',
    sds_revision_date: '10 January 2024',
    tds_url: '/documents/tds/alkota-tds-de721-citrus-blast.pdf',
    tds_revision_date: '10 January 2024',
    label_url: '/documents/labels/alkota-label-de721.pdf',
    primary_image_url: '/assets/products/food-safe-cleaner.png',
    image_url: '/assets/products/food-safe-cleaner.png',
    media_status: 'media_verified',
    meta_title: 'Citrus Blast DE-721 | Neutral Citrus Degreaser UK | Alkota',
    meta_description: 'Natural citrus terpene degreaser DE-721. Safe for polished aluminium, food prep equipment, and eco-sensitive wash bays.'
  },

  // ─── 09. RAPTOR TR-428 ─────────────────────────────────────────────────────
  {
    id: 'chem-tr428',
    slug: 'raptor-tr428',
    name: 'Raptor TR-428',
    code: 'TR-428',
    category: 'industrial',
    tagline: 'Biodegradable industrial detergent — tough on off-road grime, free-rinsing finish.',
    description: 'A heavy-duty biodegradable industrial detergent for earthmoving equipment, agricultural rigs, and construction plant. Features a natural citrus solvency package combined with non-ionic builders that strip off road slime, dried loam, and oil mist. Safe on stainless steel, aluminium, and painted surfaces when used as directed.',
    active: true,
    featured: false,
    uk_status: 'published',
    sort_order: 90,
    form: 'Concentrated Liquid',
    appearance: 'Clear Gold Liquid',
    ph_level: '10.8 – 11.4',
    specific_gravity: '1.05 @ 20°C',
    active_ingredients: ['Natural Citrus Terpenes', 'Alkaline Builders', 'Biodegradable Wetting Agents'],
    voc_content: 'Low VOC (<10 g/L)',
    biodegradability_claim: 'Readily Biodegradable (OECD 301B)',
    biodegradable: true,
    hazardous: false,
    food_safe: false,
    food_process_status: 'rinse_required',
    use_cases: ['Excavators & Loading Shovels', 'Agricultural Machinery', 'Site Dumpers & Telehandlers', 'Plant Hire Fleet Turnaround'],
    compatible_surfaces: ['Painted Steel', 'Aluminium Panels', 'Galvanised Metal', 'Rubber Tracks'],
    not_suitable_for: [],
    contamination_types: ['Heavy Clay Mud', 'Silting Dust', 'Hydraulic Oil Films', 'Vegetation & Organic Sap'],
    application_methods: ['Hot/Cold Pressure Washer Injector', 'Low-Pressure Pre-Sprayer'],
    compatible_equipment_types: ['Hot Water Pressure Washers', 'Cold Water Washers'],
    dilution_hot: '1:40 to 1:100',
    dilution_cold: '1:20 to 1:60',
    surface_notes: 'Safe on painted machinery and aluminium when rinsed thoroughly.',
    application_notes: 'Apply via injector from bottom up. Dwell 3–5 minutes and pressure-wash clean.',
    water_recovery_compatible: true,
    separator_compatible: true,
    recycling_compatible: true,
    water_recovery_notes: 'Free-rinsing chemistry separates cleanly in settlement interceptors.',
    storage_notes: 'Keep above 5°C.',
    shelf_life: '24 Months',
    available_sizes: ['25L Drum', '200L Drum', '1000L IBC'],
    price_25l: 82.00,
    price_200l: 315.00,
    price_1000l: 1350.00,
    manufacturer: 'Hydrus Detergents / Alkota Cleaning Systems',
    country_of_origin: 'USA / UK Formulated',
    features: [
      'Multi-surface versatility across plant and agricultural equipment',
      'Free-rinsing surfactant package leaves zero film',
      'Natural citrus boost dissolves hydrocarbon deposits'
    ],
    hazard_classification: 'Skin Irrit. 2; Eye Irrit. 2 (GB CLP / UK REACH)',
    signal_word: 'WARNING',
    hazard_pictograms: ['exclamation'],
    hazard_statements: ['H315: Causes skin irritation', 'H319: Causes serious eye irritation'],
    precautionary_statements: ['P280: Wear protective gloves and eye protection'],
    sds_url: '/documents/sds/alkota-sds-tr428-raptor.pdf',
    sds_revision_date: '15 January 2024',
    tds_url: '/documents/tds/alkota-tds-tr428-raptor.pdf',
    tds_revision_date: '15 January 2024',
    label_url: '/documents/labels/alkota-label-tr428.pdf',
    primary_image_url: '/assets/products/truck-plant-wash.png',
    image_url: '/assets/products/truck-plant-wash.png',
    media_status: 'media_verified',
    meta_title: 'Raptor TR-428 | Plant & Off-Road Detergent UK | Alkota',
    meta_description: 'Alkota Raptor TR-428 heavy plant detergent removes clay, slurry, and grease from earthmoving equipment with rapid turnaround.'
  },

  // ─── 10. CRETE CLEAN ───────────────────────────────────────────────────────
  {
    id: 'chem-crete-clean',
    slug: 'crete-clean',
    name: 'Crete Clean Masonry Restorer',
    code: 'Crete Clean',
    category: 'masonry',
    tagline: 'Deep-penetrating masonry & concrete restorer — removes efflorescence, cement scale, and rust stains.',
    description: 'A specialised acidic cleaning formulation engineered for commercial concrete slabs, architectural block paving, and clay brickwork. Penetrates dense pores to dissolve carbonate efflorescence blooms, mortar smear, iron oxidation rust stains, and atmospheric grime. Rinses clean with hot water to leave pristine masonry.',
    active: true,
    featured: false,
    uk_status: 'published',
    sort_order: 100,
    form: 'Liquid Concentrate',
    appearance: 'Clear Light Straw Liquid',
    ph_level: '1.5 – 2.0 (Acidic)',
    specific_gravity: '1.10 @ 20°C',
    active_ingredients: ['Inhibited Organic Acids', 'Surfactant Penetrants', 'Rust Dissolvers'],
    voc_content: 'Zero VOC',
    biodegradability_claim: 'Biodegradable Organic Acid Surfactants',
    biodegradable: true,
    hazardous: true,
    food_safe: false,
    food_process_status: 'non_food',
    use_cases: ['New Build Brickwork Mortar Cleanup', 'Warehouse Concrete Floor Efflorescence', 'Commercial Block Paved Forecourts', 'Granite & Sandstone Atmospheric Soot Removal'],
    compatible_surfaces: ['Engineered Concrete', 'Clay Brickwork', 'Granite & Dense Natural Stone', 'Unglazed Quarry Tiles'],
    not_suitable_for: ['Polished Marble', 'Limestone', 'Travertine', 'Raw Aluminium', 'Galvanised Metal'],
    contamination_types: ['Mortar Smear & Cement Splatter', 'Efflorescence Salt Blooms', 'Iron Rust Stains', 'Atmospheric Carbon Crust'],
    application_methods: ['Low-Pressure Acid-Resistant Pump Sprayer', 'Manual Stiff Broom Agitation', 'Hot Water Pressure Washer Rinse'],
    compatible_equipment_types: ['Alkota Hot Water Washers', 'Flat Surface Rotary Cleaners'],
    dilution_hot: '1:5 to 1:20 (apply cold, rinse with hot water)',
    dilution_cold: '1:3 to 1:10 depending on mortar thickness',
    surface_notes: 'Pre-wet all brickwork with clean water before applying. Never use on limestone or polished marble.',
    application_notes: 'Apply generously, allow 5–10 minutes to react with efflorescence/mortar, agitate with stiff brush if needed, and rinse thoroughly with high pressure.',
    water_recovery_compatible: false,
    separator_compatible: false,
    recycling_compatible: false,
    water_recovery_notes: 'Acidic runoff must be neutralised or collected in accordance with UK EA discharge consents.',
    storage_notes: 'Store in acid-resistant polyethylene container away from alkalis and bleach.',
    shelf_life: '24 Months',
    available_sizes: ['5L Container', '25L Heavy Duty Drum'],
    price_5l: 22.00,
    price_25l: 86.00,
    manufacturer: 'Hydrus Detergents / Alkota Cleaning Systems',
    country_of_origin: 'USA / UK Formulated',
    features: [
      'Inhibited acid formulation removes mortar smear without burning brick faces',
      'Dissolves tough mineral efflorescence salt deposits from concrete',
      'Lifts stubborn iron rust and bore-water irrigation stains'
    ],
    hazard_classification: 'Skin Corr. 1B; Eye Dam. 1 (GB CLP / UK REACH)',
    signal_word: 'DANGER',
    hazard_pictograms: ['corrosive'],
    hazard_statements: ['H314: Causes severe skin burns and eye damage'],
    precautionary_statements: [
      'P280: Wear acid-resistant gloves, clothing, and eye protection',
      'P301+P330+P331: IF SWALLOWED: Rinse mouth. Do NOT induce vomiting',
      'P305+P351+P338: IF IN EYES: Rinse cautiously with water for several minutes'
    ],
    sds_url: '/documents/sds/alkota-sds-crete-clean.pdf',
    sds_revision_date: '05 January 2024',
    tds_url: '/documents/tds/alkota-tds-crete-clean.pdf',
    tds_revision_date: '05 January 2024',
    label_url: '/documents/labels/alkota-label-crete-clean.pdf',
    primary_image_url: '/assets/products/masonry-cleaner.png',
    image_url: '/assets/products/masonry-cleaner.png',
    media_status: 'media_verified',
    meta_title: 'Crete Clean | Concrete & Masonry Efflorescence Cleaner UK | Alkota',
    meta_description: 'Crete Clean concrete and masonry restorer removes efflorescence, mortar smear, and rust stains from industrial brickwork and paving.'
  }
];

export function getChemicalBySlug(slug: string): ChemicalProduct | undefined {
  return VERIFIED_CHEMICAL_PRODUCTS.find(p => p.slug === slug || p.slug === slug.toLowerCase());
}

export function getChemicalsByCategory(categorySlug: string): ChemicalProduct[] {
  return VERIFIED_CHEMICAL_PRODUCTS.filter(p => {
    if (categorySlug === 'fleet-vehicle' && (p.category === 'fleet-vehicle' || p.category === 'transportation-fleet' || p.category === 'auto-truck-wash')) return true;
    if (categorySlug === 'degreasers' && (p.category === 'degreasers' || p.category === 'degreaser')) return true;
    if (categorySlug === 'industrial' && (p.category === 'industrial' || p.category === 'farm-ag' || p.category === 'heavy-industrial')) return true;
    if (categorySlug === 'parts-washers' && (p.category === 'parts-washers' || p.category === 'parts-washer' || p.category === 'parts-washer-solution')) return true;
    if (categorySlug === 'food-processing' && p.category === 'food-processing') return true;
    if (categorySlug === 'specialty' && (p.category === 'specialty' || p.category === 'scale-stop' || p.category === 'additives')) return true;
    if (categorySlug === 'masonry' && (p.category === 'masonry' || p.category === 'masonry-asphalt')) return true;
    return p.category === categorySlug;
  });
}
