'use client';

import { useState } from 'react';
import Navigation from '@/components/Navigation';
import Breadcrumbs from '@/components/Breadcrumbs';
import Footer from '@/components/Footer';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Beaker,
  ShieldCheck,
  ArrowRight,
  Droplets,
  Flame,
  Gauge,
  Wind,
  CheckCircle2,
  AlertTriangle,
  FileText,
  Sliders,
  Layers,
  Sparkles,
  Truck,
  Factory,
  Tractor,
  Settings,
  ShieldAlert,
  ChevronRight,
  Search,
  ExternalLink,
  Download,
  Info,
  HelpCircle,
  Clock,
  Zap,
  Building2,
  RefreshCw,
  Award
} from 'lucide-react';
import Link from 'next/link';
import {
  CHEMICAL_CATEGORIES,
  VERIFIED_CHEMICAL_PRODUCTS,
} from '@/lib/chemicals/seed-data';
import {
  CONTAMINATION_OPTIONS,
  SURFACE_OPTIONS,
  EQUIPMENT_OPTIONS,
  runChemicalMatch,
} from '@/lib/chemicals/matching-engine';
import {
  COMMON_TANK_PRESETS,
  COMMON_DILUTION_RATIOS,
  calculateChemicalDosing,
} from '@/lib/chemicals/dilution-calculator';

// ─── 02. THE 4-PART SYSTEM QUADRANT DATA ─────────────────────────────────────
const SYSTEM_PILLARS = [
  {
    id: 'pressure',
    title: 'PRESSURE',
    subtitle: 'Mechanical Shearing Force',
    unit: '100 – 350 BAR',
    description: 'High kinetic water pressure breaks the mechanical adhesion between soil deposits and the substrate. Pressure shears through encrusted clay, lime mortar, and dried mud cake.',
    synergy: 'Delivered by Alkota slow-turning ceramic triplex plunger pumps.',
    linkHref: '/machines/cold-water',
    linkText: 'Explore Cold Water Systems',
    icon: Gauge,
    color: 'border-blue-500/40 text-blue-400'
  },
  {
    id: 'flow',
    title: 'FLOW',
    subtitle: 'High-Volume Fluvial Evacuation',
    unit: '15 – 35 L/MIN',
    description: 'Pressure alone only dislodges particles; high water volume is required to carry heavy particulate, aggregate, and suspended slurry away before it can resettle.',
    synergy: 'Optimised through oversized brass manifolds and industrial nozzles.',
    linkHref: '/machines/hot-water',
    linkText: 'Explore High-Flow Washers',
    icon: Droplets,
    color: 'border-cyan-500/40 text-cyan-400'
  },
  {
    id: 'heat',
    title: 'HEAT',
    subtitle: 'Thermal Emulsification & Reaction',
    unit: 'Up to 95°C / 140°C Steam',
    description: 'Thermal energy drastically lowers hydrocarbon viscosity. Heavy grease, bitumen, and animal tallow liquefy on contact while chemical reaction rates multiply exponentially.',
    synergy: 'Generated by continuous-wound Schedule 80 hydro-formed heating coils.',
    linkHref: '/machines/steam',
    linkText: 'Explore Dry Steam Units',
    icon: Flame,
    color: 'border-amber-500/40 text-amber-400'
  },
  {
    id: 'chemistry',
    title: 'CHEMISTRY',
    subtitle: 'Engineered Molecular Breakdown',
    unit: 'Hydrus Formulations',
    description: 'Chemical builders reduce surface tension, saponify organic fats, neutralise electrostatic road film bonds, and encapsulate free oil droplets for rapid rinse-off.',
    synergy: 'Formulated specifically not to degrade heating coils, packings, or seals.',
    linkHref: '/chemicals/match',
    linkText: 'Run Chemical Matcher',
    icon: Beaker,
    color: 'border-alkota-orange/60 text-alkota-orange'
  }
];

export default function ChemicalsFlagshipPage() {
  // ─── Interactive States ───────────────────────────────────────────────────
  const [activePillar, setActivePillar] = useState<string>('chemistry');
  const [activeCategorySlug, setActiveCategorySlug] = useState<string>('fleet-vehicle');

  // Quick Matcher State
  const [selectedContam, setSelectedContam] = useState<string>('road_film');
  const [selectedSurface, setSelectedSurface] = useState<string>('painted_vehicle');
  const [selectedEquip, setSelectedEquip] = useState<string>('hot_water');

  // Dilution Calculator State
  const [calcTankLiters, setCalcTankLiters] = useState<number>(25);
  const [calcDilutionPart, setCalcDilutionPart] = useState<number>(60);

  // Quick match results
  const quickMatchResults = runChemicalMatch({
    contamination: selectedContam,
    surface: selectedSurface,
    equipmentType: selectedEquip,
  });

  const activeCategory = CHEMICAL_CATEGORIES.find(c => c.slug === activeCategorySlug) || CHEMICAL_CATEGORIES[0];
  const categoryProducts = VERIFIED_CHEMICAL_PRODUCTS.filter(p => {
    if (activeCategory.slug === 'fleet-vehicle') return p.category === 'fleet-vehicle';
    if (activeCategory.slug === 'degreasers') return p.category === 'degreasers';
    if (activeCategory.slug === 'industrial') return p.category === 'industrial';
    if (activeCategory.slug === 'parts-washers') return p.category === 'parts-washers';
    if (activeCategory.slug === 'specialty') return p.category === 'specialty';
    if (activeCategory.slug === 'masonry') return p.category === 'masonry';
    if (activeCategory.slug === 'food-processing') return p.category === 'food-processing';
    return true;
  });

  const featuredProducts = VERIFIED_CHEMICAL_PRODUCTS.filter(p => p.featured);
  const dosingResult = calculateChemicalDosing(calcTankLiters, calcDilutionPart);

  return (
    <main className="min-h-screen bg-[#0D0D0D] text-white selection:bg-alkota-orange selection:text-white pt-28 pb-0">
      <Navigation />

      {/* ─── 01. FLAGSHIP HERO ──────────────────────────────────────────────── */}
      <section className="relative border-b border-[#222] bg-[#0A0A0A] overflow-hidden">
        {/* Subtle geometric background lines */}
        <div className="absolute inset-0 bg-[radial-gradient(#1A1A1A_1px,transparent_1px)] [background-size:24px_24px] opacity-40" />
        <div className="absolute top-0 right-1/4 w-[600px] h-[600px] bg-alkota-orange/5 rounded-full blur-3xl pointer-events-none" />

        <div className="relative mx-auto max-w-7xl px-6 sm:px-12 pt-12 pb-20">
          <Breadcrumbs items={[{ label: 'Chemicals' }]} />

          <div className="mt-8 max-w-5xl">
            <div className="mb-6 flex items-center gap-3">
              <span className="h-2 w-2 rounded-full bg-alkota-orange animate-pulse" />
              <span className="font-ibm-plex-mono text-[11px] font-bold uppercase tracking-[0.3em] text-alkota-orange">
                // ALKOTA UK INDUSTRIAL CHEMISTRY // HYDRUS FORMULATIONS
              </span>
            </div>

            <h1 className="text-4xl sm:text-6xl lg:text-7xl font-extralight tracking-tight uppercase leading-[0.95] text-white mb-6">
              THE CLEAN IS <br />
              <span className="text-alkota-orange font-light">MORE THAN PRESSURE.</span>
            </h1>

            <p className="text-base sm:text-lg text-[#AAA] max-w-3xl leading-relaxed font-normal mb-10">
              Alkota cleaning formulations are engineered as a fundamental mechanical component of the complete cleaning system. Formulated by Hydrus to dissolve stubborn hydrocarbons, traffic film, and agricultural soils without attacking coils, pumps, or sensitive aluminium surfaces.
            </p>

            <div className="flex flex-wrap items-center gap-4">
              <Link
                href="/chemicals/match"
                className="inline-flex items-center gap-3 bg-alkota-orange text-white px-7 py-3.5 text-xs uppercase tracking-widest hover:bg-white hover:text-black transition-all font-normal shadow-lg shadow-alkota-orange/20"
              >
                <span>Launch Chemical Match</span>
                <ArrowRight className="h-4 w-4" />
              </Link>
              <a
                href="#families"
                className="inline-flex items-center gap-2 border border-[#333] bg-[#141414] text-[#CCC] px-6 py-3.5 text-xs uppercase tracking-widest hover:border-white hover:text-white transition-all font-normal"
              >
                <span>Explore Formulations</span>
                <ChevronRight className="h-4 w-4 text-alkota-orange" />
              </a>
              <Link
                href="/chemicals/safety-data"
                className="inline-flex items-center gap-2 border border-[#222] bg-transparent text-[#888] px-5 py-3.5 text-xs uppercase tracking-widest hover:text-white hover:border-[#444] transition-all font-normal"
              >
                <FileText className="h-3.5 w-3.5 text-alkota-orange" />
                <span>Safety Data (SDS)</span>
              </Link>
            </div>
          </div>

          {/* Quick Metrics Bar */}
          <div className="mt-16 grid grid-cols-2 sm:grid-cols-4 gap-px bg-[#222] border border-[#222]">
            <div className="bg-[#111] p-5">
              <span className="block font-ibm-plex-mono text-[9px] uppercase tracking-widest text-[#666] mb-1">
                UK Compliance
              </span>
              <span className="text-sm font-normal text-white flex items-center gap-1.5">
                <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0" />
                <span>GB CLP & UK REACH</span>
              </span>
            </div>
            <div className="bg-[#111] p-5">
              <span className="block font-ibm-plex-mono text-[9px] uppercase tracking-widest text-[#666] mb-1">
                Equipment Protection
              </span>
              <span className="text-sm font-normal text-white flex items-center gap-1.5">
                <ShieldCheck className="h-4 w-4 text-alkota-orange shrink-0" />
                <span>Scale Stop Technology</span>
              </span>
            </div>
            <div className="bg-[#111] p-5">
              <span className="block font-ibm-plex-mono text-[9px] uppercase tracking-widest text-[#666] mb-1">
                Substrate Safety
              </span>
              <span className="text-sm font-normal text-white flex items-center gap-1.5">
                <Sparkles className="h-4 w-4 text-cyan-400 shrink-0" />
                <span>Aluminium Safe Range</span>
              </span>
            </div>
            <div className="bg-[#111] p-5">
              <span className="block font-ibm-plex-mono text-[9px] uppercase tracking-widest text-[#666] mb-1">
                COSHH Documentation
              </span>
              <span className="text-sm font-normal text-white flex items-center gap-1.5">
                <FileText className="h-4 w-4 text-alkota-orange shrink-0" />
                <span>Verified SDS & TDS</span>
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* ─── 02. PRESSURE + FLOW + HEAT + CHEMISTRY (THE 4-PART SYSTEM) ─────── */}
      <section className="py-20 border-b border-[#222] bg-[#111111]">
        <div className="mx-auto max-w-7xl px-6 sm:px-12">
          <div className="flex items-center gap-4 mb-6">
            <span className="font-ibm-plex-mono text-[10px] font-bold text-alkota-orange tracking-[0.4em] uppercase">
              CHAPTER 02
            </span>
            <span className="h-px w-12 bg-[#333]" />
            <span className="font-ibm-plex-mono text-[10px] font-bold tracking-[0.3em] uppercase text-[#777]">
              THE COMPLETE CLEANING SYSTEM
            </span>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
            <div className="lg:col-span-5 space-y-6">
              <h2 className="text-3xl sm:text-5xl font-extralight uppercase tracking-tight text-white leading-tight">
                FOUR FORCES. <br />
                <span className="text-alkota-orange font-light">ONE ENGINEERED OUTCOME.</span>
              </h2>
              <p className="text-sm text-[#AAA] leading-relaxed font-normal">
                Industrial cleaning is a physical and chemical system. Relying solely on high pressure causes surface damage and water waste. Relying on generic chemicals leads to coil scaling, pump erosion, and failed effluent discharge.
              </p>
              <p className="text-xs text-[#777] leading-relaxed font-normal">
                Selecting any force reveals its mechanical function and its relationship to the other three pillars in the Alkota cleaning loop.
              </p>

              <div className="p-4 bg-[#181818] border-l-2 border-alkota-orange">
                <span className="text-[10px] font-ibm-plex-mono uppercase tracking-widest text-alkota-orange block mb-1">
                  // Alkota Engineering Principle
                </span>
                <p className="text-xs text-[#BBB] leading-relaxed font-normal">
                  "Chemical formulations must respect the machine metallurgy just as the machine must respect the surface metallurgy."
                </p>
              </div>
            </div>

            {/* Interactive Pillar Grid */}
            <div className="lg:col-span-7 grid grid-cols-1 sm:grid-cols-2 gap-4">
              {SYSTEM_PILLARS.map((pillar) => {
                const isSelected = activePillar === pillar.id;
                const IconComponent = pillar.icon;
                return (
                  <div
                    key={pillar.id}
                    onClick={() => setActivePillar(pillar.id)}
                    className={`p-6 cursor-pointer transition-all border ${
                      isSelected
                        ? 'bg-[#1C1C1A] border-alkota-orange shadow-xl'
                        : 'bg-[#141414] border-[#262626] hover:border-[#444]'
                    }`}
                  >
                    <div className="flex items-center justify-between mb-4">
                      <div className={`p-2 rounded bg-black/40 border ${pillar.color}`}>
                        <IconComponent className="h-5 w-5" />
                      </div>
                      <span className="font-ibm-plex-mono text-[10px] uppercase text-[#777] tracking-widest">
                        {pillar.unit}
                      </span>
                    </div>

                    <h3 className={`text-lg uppercase tracking-tight font-light mb-1 ${isSelected ? 'text-alkota-orange font-normal' : 'text-white'}`}>
                      {pillar.title}
                    </h3>
                    <span className="text-[11px] text-[#888] font-normal block mb-3">
                      {pillar.subtitle}
                    </span>

                    <p className="text-xs text-[#AAA] leading-relaxed font-normal mb-4">
                      {pillar.description}
                    </p>

                    <div className="pt-3 border-t border-[#2A2A2A] flex items-center justify-between">
                      <span className="text-[10px] text-[#666] font-normal">
                        {pillar.synergy}
                      </span>
                      <Link
                        href={pillar.linkHref}
                        className="text-[10px] uppercase tracking-wider text-alkota-orange hover:text-white transition-colors shrink-0 ml-2 inline-flex items-center gap-1"
                        onClick={(e) => e.stopPropagation()}
                      >
                        <span>Learn</span>
                        <ArrowRight className="h-2.5 w-2.5" />
                      </Link>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* ─── 03. SIGNATURE FEATURE: CHEMICAL MATCH ──────────────────────────── */}
      <section id="match" className="py-20 border-b border-[#222] bg-[#0A0A0A] relative overflow-hidden">
        <div className="mx-auto max-w-7xl px-6 sm:px-12">
          <div className="flex items-center gap-4 mb-6">
            <span className="font-ibm-plex-mono text-[10px] font-bold text-alkota-orange tracking-[0.4em] uppercase">
              CHAPTER 03
            </span>
            <span className="h-px w-12 bg-[#333]" />
            <span className="font-ibm-plex-mono text-[10px] font-bold tracking-[0.3em] uppercase text-[#777]">
              STRUCTURED COMPATIBILITY ENGINE
            </span>
          </div>

          <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-6 mb-12">
            <div>
              <h2 className="text-3xl sm:text-5xl font-extralight uppercase tracking-tight text-white leading-tight">
                CHEMICAL MATCH <br />
                <span className="text-alkota-orange font-light">START WITH THE CONTAMINATION.</span>
              </h2>
              <p className="text-sm text-[#AAA] max-w-2xl mt-3 font-normal">
                Instead of browsing generic detergent bottles, specify the exact soil type and substrate metallurgy. Our compatibility engine matches formulations using structured lab rules.
              </p>
            </div>
            <Link
              href="/chemicals/match"
              className="inline-flex items-center gap-2 bg-[#181818] border border-[#333] hover:border-alkota-orange text-white px-5 py-3 text-xs uppercase tracking-widest transition-all font-normal shrink-0"
            >
              <span>Full Diagnostic Matcher</span>
              <ArrowRight className="h-3.5 w-3.5 text-alkota-orange" />
            </Link>
          </div>

          {/* Embedded Quick Matcher Card */}
          <div className="bg-[#121212] border border-[#262626] p-6 sm:p-10 shadow-2xl">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              {/* Question 1: Contamination */}
              <div>
                <label className="block font-ibm-plex-mono text-[10px] uppercase tracking-widest text-alkota-orange mb-3">
                  01 // Select Contamination Type
                </label>
                <select
                  value={selectedContam}
                  onChange={(e) => setSelectedContam(e.target.value)}
                  className="w-full bg-[#1A1A1A] border border-[#333] text-white px-4 py-3 text-xs font-normal focus:outline-none focus:border-alkota-orange transition-colors"
                >
                  {CONTAMINATION_OPTIONS.map((opt) => (
                    <option key={opt.id} value={opt.id}>
                      {opt.label}
                    </option>
                  ))}
                </select>
                <p className="text-[11px] text-[#777] mt-2 font-normal">
                  {CONTAMINATION_OPTIONS.find(o => o.id === selectedContam)?.sublabel}
                </p>
              </div>

              {/* Question 2: Surface */}
              <div>
                <label className="block font-ibm-plex-mono text-[10px] uppercase tracking-widest text-alkota-orange mb-3">
                  02 // Select Substrate Metallurgy
                </label>
                <select
                  value={selectedSurface}
                  onChange={(e) => setSelectedSurface(e.target.value)}
                  className="w-full bg-[#1A1A1A] border border-[#333] text-white px-4 py-3 text-xs font-normal focus:outline-none focus:border-alkota-orange transition-colors"
                >
                  {SURFACE_OPTIONS.map((opt) => (
                    <option key={opt.id} value={opt.id}>
                      {opt.label}
                    </option>
                  ))}
                </select>
                <p className="text-[11px] text-[#777] mt-2 font-normal">
                  {SURFACE_OPTIONS.find(o => o.id === selectedSurface)?.sublabel}
                </p>
              </div>

              {/* Question 3: Equipment */}
              <div>
                <label className="block font-ibm-plex-mono text-[10px] uppercase tracking-widest text-alkota-orange mb-3">
                  03 // Application Equipment
                </label>
                <select
                  value={selectedEquip}
                  onChange={(e) => setSelectedEquip(e.target.value)}
                  className="w-full bg-[#1A1A1A] border border-[#333] text-white px-4 py-3 text-xs font-normal focus:outline-none focus:border-alkota-orange transition-colors"
                >
                  {EQUIPMENT_OPTIONS.map((opt) => (
                    <option key={opt.id} value={opt.id}>
                      {opt.label}
                    </option>
                  ))}
                </select>
                <p className="text-[11px] text-[#777] mt-2 font-normal">
                  {EQUIPMENT_OPTIONS.find(o => o.id === selectedEquip)?.sublabel}
                </p>
              </div>
            </div>

            {/* Results Display */}
            <div className="pt-6 border-t border-[#222]">
              <div className="flex items-center justify-between mb-4">
                <span className="font-ibm-plex-mono text-[10px] uppercase tracking-widest text-[#777]">
                  // Matching Formulations ({quickMatchResults.length} Verified Solutions)
                </span>
                {quickMatchResults.length > 0 && (
                  <span className="text-[10px] text-emerald-400 font-ibm-plex-mono uppercase">
                    ✓ Compatibility Rules Checked
                  </span>
                )}
              </div>

              {quickMatchResults.length === 0 ? (
                <div className="p-8 text-center bg-[#181818] border border-[#2A2A2A]">
                  <AlertTriangle className="h-8 w-8 text-amber-400 mx-auto mb-3" />
                  <h4 className="text-sm uppercase tracking-wider text-white font-normal mb-1">
                    No Direct Automated Match For This Substrate / Contamination Combination
                  </h4>
                  <p className="text-xs text-[#888] max-w-md mx-auto mb-4 font-normal">
                    This surface and soil configuration may require specialist chemical dilution or neutral testing.
                  </p>
                  <Link
                    href="/contact?subject=Chemical%20Advice"
                    className="inline-flex items-center gap-2 bg-alkota-orange text-white px-5 py-2.5 text-xs uppercase tracking-widest hover:bg-white hover:text-black transition-colors font-normal"
                  >
                    <span>Talk to Alkota Chemical Support</span>
                    <ArrowRight className="h-3 w-3" />
                  </Link>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {quickMatchResults.slice(0, 3).map((match, idx) => (
                    <div
                      key={match.product.id}
                      className="bg-[#181818] border border-[#2A2A2A] hover:border-alkota-orange p-5 flex flex-col justify-between transition-all group"
                    >
                      <div>
                        <div className="flex items-start justify-between gap-2 mb-3">
                          <span className="text-[10px] font-ibm-plex-mono uppercase text-alkota-orange bg-alkota-orange/10 px-2 py-0.5 border border-alkota-orange/30">
                            {idx === 0 ? '★ Primary Match' : 'Alternative Solution'}
                          </span>
                          <span className="text-[10px] font-ibm-plex-mono text-[#888]">
                            pH {match.product.ph_level?.split(' ')[0] || '--'}
                          </span>
                        </div>

                        <h4 className="text-base uppercase tracking-tight text-white font-normal group-hover:text-alkota-orange transition-colors mb-1">
                          {match.product.name}
                        </h4>
                        <p className="text-xs text-[#888] leading-relaxed font-normal mb-3">
                          {match.product.tagline}
                        </p>

                        <div className="p-2.5 bg-black/40 border border-[#222] mb-4 space-y-1.5">
                          <span className="block text-[9px] font-ibm-plex-mono uppercase text-[#666]">
                            Why It Fits:
                          </span>
                          <p className="text-[11px] text-[#CCC] leading-tight font-normal">
                            {match.fitReason}
                          </p>
                          {match.surfaceWarning && (
                            <p className="text-[10px] text-amber-400 font-normal mt-1">
                              {match.surfaceWarning}
                            </p>
                          )}
                        </div>
                      </div>

                      <div className="pt-3 border-t border-[#222] flex items-center justify-between">
                        <span className="text-[10px] text-[#777] font-ibm-plex-mono">
                          Dilution: {match.recommendedDilution}
                        </span>
                        <Link
                          href={`/chemicals/${match.product.category}/${match.product.slug}`}
                          className="inline-flex items-center gap-1 text-xs uppercase tracking-wider text-white group-hover:text-alkota-orange transition-colors font-normal"
                        >
                          <span>Spec</span>
                          <ArrowRight className="h-3 w-3" />
                        </Link>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* ─── 04. CHEMICAL FAMILY NAVIGATOR ─────────────────────────────────── */}
      <section id="families" className="py-20 border-b border-[#222] bg-[#111111]">
        <div className="mx-auto max-w-7xl px-6 sm:px-12">
          <div className="flex items-center gap-4 mb-6">
            <span className="font-ibm-plex-mono text-[10px] font-bold text-alkota-orange tracking-[0.4em] uppercase">
              CHAPTER 04
            </span>
            <span className="h-px w-12 bg-[#333]" />
            <span className="font-ibm-plex-mono text-[10px] font-bold tracking-[0.3em] uppercase text-[#777]">
              INDUSTRIAL CHEMICAL DISCIPLINES
            </span>
          </div>

          <h2 className="text-3xl sm:text-5xl font-extralight uppercase tracking-tight text-white leading-tight mb-8">
            CHEMICAL FAMILIES <br />
            <span className="text-alkota-orange font-light">MATCHED BY INDUSTRY SECTOR.</span>
          </h2>

          {/* Horizontal Family Selector Tabs */}
          <div className="flex flex-wrap gap-2 mb-8 pb-4 border-b border-[#222] overflow-x-auto">
            {CHEMICAL_CATEGORIES.map((cat) => {
              const isActive = activeCategorySlug === cat.slug;
              return (
                <button
                  key={cat.slug}
                  onClick={() => setActiveCategorySlug(cat.slug)}
                  className={`px-4 py-2.5 text-xs uppercase tracking-wider transition-all cursor-pointer font-normal ${
                    isActive
                      ? 'bg-alkota-orange text-white border border-alkota-orange'
                      : 'bg-[#181818] text-[#888] border border-[#2A2A2A] hover:text-white hover:border-[#444]'
                  }`}
                >
                  {cat.name}
                </button>
              );
            })}
          </div>

          {/* Active Family Showcase Plate */}
          <div className="bg-[#141414] border border-[#262626] p-6 sm:p-10 grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
            {/* Left Narrative */}
            <div className="lg:col-span-5 space-y-6">
              <span className="text-[10px] uppercase tracking-[0.25em] text-alkota-orange font-light block">
                // {activeCategory.badge}
              </span>
              <h3 className="text-2xl sm:text-3xl uppercase tracking-tight text-white font-light">
                {activeCategory.title}
              </h3>
              <p className="text-xs text-[#AAA] leading-relaxed font-normal">
                {activeCategory.description}
              </p>

              <div className="space-y-3 pt-2">
                <div>
                  <span className="block font-ibm-plex-mono text-[9px] uppercase tracking-widest text-[#666] mb-1">
                    Target Contamination:
                  </span>
                  <div className="flex flex-wrap gap-1.5">
                    {activeCategory.keyContaminants.map((c, i) => (
                      <span key={i} className="text-[10px] bg-black/40 text-[#CCC] px-2 py-0.5 border border-[#222]">
                        {c}
                      </span>
                    ))}
                  </div>
                </div>

                <div>
                  <span className="block font-ibm-plex-mono text-[9px] uppercase tracking-widest text-[#666] mb-1">
                    Compatible Substrates:
                  </span>
                  <div className="flex flex-wrap gap-1.5">
                    {activeCategory.keySurfaces.map((s, i) => (
                      <span key={i} className="text-[10px] bg-black/40 text-[#CCC] px-2 py-0.5 border border-[#222]">
                        {s}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              <div className="pt-4 border-t border-[#222] flex items-center justify-between">
                <span className="text-[10px] text-alkota-orange font-ibm-plex-mono">
                  {activeCategory.equipmentSynergy}
                </span>
                <Link
                  href={`/chemicals/${activeCategory.slug}`}
                  className="inline-flex items-center gap-2 text-xs uppercase tracking-wider text-white hover:text-alkota-orange transition-colors font-normal"
                >
                  <span>Category Hub</span>
                  <ArrowRight className="h-3 w-3" />
                </Link>
              </div>
            </div>

            {/* Right Product Grid */}
            <div className="lg:col-span-7 grid grid-cols-1 sm:grid-cols-2 gap-4">
              {categoryProducts.map((prod) => (
                <Link
                  key={prod.id}
                  href={`/chemicals/${prod.category}/${prod.slug}`}
                  className="p-5 bg-[#181818] border border-[#262626] hover:border-alkota-orange transition-all no-underline group flex flex-col justify-between"
                >
                  <div>
                    <div className="flex items-center justify-between text-[10px] font-ibm-plex-mono text-[#666] mb-2">
                      <span>{prod.code || 'HYDRUS'}</span>
                      <span className="text-alkota-orange">{prod.form}</span>
                    </div>

                    <h4 className="text-base uppercase tracking-tight text-white font-normal group-hover:text-alkota-orange transition-colors mb-1">
                      {prod.name}
                    </h4>
                    <p className="text-xs text-[#888] line-clamp-2 leading-relaxed font-normal mb-4">
                      {prod.tagline}
                    </p>

                    <div className="grid grid-cols-2 gap-2 text-[10px] font-ibm-plex-mono text-[#777] bg-black/30 p-2.5 border border-[#222] mb-3">
                      <div>
                        <span className="block text-[#555] text-[8px] uppercase">pH Level</span>
                        <span className="text-[#CCC]">{prod.ph_level?.split(' ')[0] || '--'}</span>
                      </div>
                      <div>
                        <span className="block text-[#555] text-[8px] uppercase">Biodegradable</span>
                        <span className={prod.biodegradable ? 'text-emerald-400' : 'text-[#888]'}>
                          {prod.biodegradable ? 'YES (OECD)' : 'NO'}
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="pt-2 flex items-center justify-between text-xs uppercase tracking-wider text-[#888] group-hover:text-white transition-colors font-normal">
                    <span>View Technical Spec</span>
                    <ArrowRight className="h-3 w-3 text-alkota-orange transform group-hover:translate-x-1 transition-transform" />
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ─── 05. FEATURED FORMULATIONS SPOTLIGHT ────────────────────────────── */}
      <section className="py-20 border-b border-[#222] bg-[#0A0A0A]">
        <div className="mx-auto max-w-7xl px-6 sm:px-12">
          <div className="flex items-center gap-4 mb-6">
            <span className="font-ibm-plex-mono text-[10px] font-bold text-alkota-orange tracking-[0.4em] uppercase">
              CHAPTER 05
            </span>
            <span className="h-px w-12 bg-[#333]" />
            <span className="font-ibm-plex-mono text-[10px] font-bold tracking-[0.3em] uppercase text-[#777]">
              BENCHMARK FORMULATIONS
            </span>
          </div>

          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12">
            <div>
              <h2 className="text-3xl sm:text-5xl font-extralight uppercase tracking-tight text-white leading-tight">
                FEATURED FORMULATIONS. <br />
                <span className="text-alkota-orange font-light">PROVEN ON UK FLEETS & INDUSTRY.</span>
              </h2>
              <p className="text-sm text-[#AAA] max-w-2xl mt-3 font-normal">
                Curated hero formulations with verified UK safety documentation and proven compatibility across thousands of machine operating hours.
              </p>
            </div>
            <Link
              href="/chemicals/safety-data"
              className="inline-flex items-center gap-2 text-xs uppercase tracking-wider text-alkota-orange hover:text-white transition-colors font-normal shrink-0"
            >
              <span>Download All Safety Data Sheets</span>
              <Download className="h-3.5 w-3.5" />
            </Link>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {featuredProducts.map((prod) => (
              <div
                key={prod.id}
                className="bg-[#121212] border border-[#262626] hover:border-alkota-orange p-6 flex flex-col justify-between transition-all group"
              >
                <div>
                  <div className="flex items-center justify-between text-[10px] font-ibm-plex-mono text-[#666] mb-3">
                    <span className="bg-alkota-orange/10 text-alkota-orange px-2 py-0.5 border border-alkota-orange/30">
                      {prod.code}
                    </span>
                    <span className="text-[#888]">
                      {prod.category.replace(/-/g, ' ').toUpperCase()}
                    </span>
                  </div>

                  <h3 className="text-xl uppercase tracking-tight text-white font-normal group-hover:text-alkota-orange transition-colors mb-2">
                    {prod.name}
                  </h3>
                  <p className="text-xs text-[#AAA] leading-relaxed font-normal mb-5">
                    {prod.tagline}
                  </p>

                  {/* Surface Compatibility Matrix Snippet */}
                  <div className="p-3 bg-black/40 border border-[#222] mb-5 space-y-2">
                    <span className="block text-[8px] font-ibm-plex-mono uppercase tracking-wider text-[#666]">
                      Surface Suitability:
                    </span>
                    <div className="grid grid-cols-2 gap-1.5 text-[10px] font-normal">
                      <div className="flex items-center gap-1.5 text-[#CCC]">
                        <CheckCircle2 className="h-3 w-3 text-emerald-400 shrink-0" />
                        <span>Painted Steel</span>
                      </div>
                      <div className="flex items-center gap-1.5 text-[#CCC]">
                        {prod.not_suitable_for?.some(s => s.toLowerCase().includes('aluminium')) ? (
                          <span className="flex items-center gap-1.5 text-amber-400">
                            <AlertTriangle className="h-3 w-3 shrink-0" />
                            <span>Aluminium (Caution)</span>
                          </span>
                        ) : (
                          <span className="flex items-center gap-1.5 text-emerald-400">
                            <CheckCircle2 className="h-3 w-3 shrink-0" />
                            <span>Aluminium Safe</span>
                          </span>
                        )}
                      </div>
                      <div className="flex items-center gap-1.5 text-[#CCC]">
                        <CheckCircle2 className="h-3 w-3 text-emerald-400 shrink-0" />
                        <span>Schedule 80 Coils</span>
                      </div>
                      <div className="flex items-center gap-1.5 text-[#CCC]">
                        <CheckCircle2 className="h-3 w-3 text-emerald-400 shrink-0" />
                        <span>Water Recycling</span>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="pt-4 border-t border-[#222] flex items-center justify-between">
                  <span className="text-[10px] font-ibm-plex-mono text-[#888]">
                    pH {prod.ph_level?.split(' ')[0] || '--'}
                  </span>
                  <Link
                    href={`/chemicals/${prod.category}/${prod.slug}`}
                    className="inline-flex items-center gap-2 bg-[#1A1A1A] hover:bg-alkota-orange text-white px-4 py-2 text-xs uppercase tracking-wider transition-all font-normal"
                  >
                    <span>Specification</span>
                    <ArrowRight className="h-3 w-3" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── 06. FLEET, INDUSTRIAL & PARTS WASHER DEEP CHAPTERS ─────────────── */}
      <section className="py-20 border-b border-[#222] bg-[#111111]">
        <div className="mx-auto max-w-7xl px-6 sm:px-12 space-y-20">
          {/* Chapter 06A: Fleet & Aluminium Story */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            <div className="lg:col-span-6 space-y-6">
              <span className="font-ibm-plex-mono text-[10px] font-bold text-alkota-orange tracking-[0.3em] uppercase block">
                // FLEET & TRANSPORT SCIENCE
              </span>
              <h3 className="text-2xl sm:text-4xl font-extralight uppercase tracking-tight text-white leading-tight">
                ROAD FILM. DIESEL SOOT. <br />
                <span className="text-alkota-orange font-light">ZERO ALUMINIUM CLOUDING.</span>
              </h3>
              <p className="text-xs sm:text-sm text-[#AAA] leading-relaxed font-normal">
                Traffic film is not just surface dirt. It is an electrostatic matrix of unburnt diesel fuel, tire carbon, silicate road dust, and oxidised asphalt bitumen held together by ionic surface tension.
              </p>
              <p className="text-xs sm:text-sm text-[#AAA] leading-relaxed font-normal">
                Aggressive commercial vehicle detergents often rely on harsh caustic soda (sodium hydroxide) which strips road film quickly but permanently etches polished aluminium fuel tanks, clouds alloy wheels, and deteriorates window seals. Alkota's <strong>Power Blast TR-407</strong> and <strong>Touchless TR-470</strong> use ionic surfactant decoupling to lift traffic film safely.
              </p>
              <div className="pt-2">
                <Link
                  href="/chemicals/fleet-vehicle"
                  className="inline-flex items-center gap-2 bg-alkota-orange text-white px-6 py-3 text-xs uppercase tracking-widest hover:bg-white hover:text-black transition-colors font-normal"
                >
                  <span>Explore Fleet & Vehicle Chemistry</span>
                  <ArrowRight className="h-3.5 w-3.5" />
                </Link>
              </div>
            </div>

            <div className="lg:col-span-6 bg-[#161614] border border-[#2A2A2A] p-8 space-y-4">
              <div className="flex items-center justify-between pb-3 border-b border-[#2A2A2A]">
                <span className="text-xs uppercase tracking-wider text-white font-normal">
                  Aluminium Compatibility Standard
                </span>
                <span className="text-[10px] font-ibm-plex-mono text-emerald-400 uppercase">
                  ✓ Verified Safe
                </span>
              </div>
              <div className="space-y-3 text-xs text-[#AAA] font-normal">
                <div className="p-3 bg-black/40 border border-[#222]">
                  <h4 className="text-white uppercase font-normal mb-1">Mirror Polished Aluminium</h4>
                  <p className="text-[11px] text-[#888]">
                    Use <strong>Citrus Blast DE-721</strong> or <strong>Power Blast TR-407</strong> at 1:60+. Zero clouding or chemical white-blooming.
                  </p>
                </div>
                <div className="p-3 bg-black/40 border border-[#222]">
                  <h4 className="text-white uppercase font-normal mb-1">Curtainsiders & Vinyl Liveries</h4>
                  <p className="text-[11px] text-[#888]">
                    <strong>Touchless TR-470</strong> lifts road grime without brush friction, preserving reflective safety chevrons and printed advertising.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Chapter 06B: Parts Washer Aqueous Chemistry */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center pt-16 border-t border-[#222]">
            <div className="lg:col-span-6 order-2 lg:order-1 bg-[#161614] border border-[#2A2A2A] p-8 space-y-4">
              <span className="font-ibm-plex-mono text-[10px] text-alkota-orange uppercase tracking-widest block">
                // CLOSED-LOOP AQUEOUS PROCESS
              </span>
              <h4 className="text-lg uppercase text-white font-normal">
                The 4-Stage Mechanical Component Cycle
              </h4>
              <div className="space-y-2 text-xs font-normal">
                <div className="flex items-center gap-3 p-2.5 bg-black/40 border border-[#222]">
                  <span className="font-ibm-plex-mono text-alkota-orange font-bold">01</span>
                  <span className="text-[#CCC]">High-Pressure Aqueous Jet Degreasing (60°C–75°C)</span>
                </div>
                <div className="flex items-center gap-3 p-2.5 bg-black/40 border border-[#222]">
                  <span className="font-ibm-plex-mono text-alkota-orange font-bold">02</span>
                  <span className="text-[#CCC]">Zero-Foam Hydrocarbon Emulsification (APW Pro Clean)</span>
                </div>
                <div className="flex items-center gap-3 p-2.5 bg-black/40 border border-[#222]">
                  <span className="font-ibm-plex-mono text-alkota-orange font-bold">03</span>
                  <span className="text-[#CCC]">Surface Tramp Oil Rejection & Disc Skimmer Separation</span>
                </div>
                <div className="flex items-center gap-3 p-2.5 bg-black/40 border border-[#222]">
                  <span className="font-ibm-plex-mono text-alkota-orange font-bold">04</span>
                  <span className="text-[#CCC]">60-Day Microscopic Monolayer Flash Rust Inhibition</span>
                </div>
              </div>
            </div>

            <div className="lg:col-span-6 order-1 lg:order-2 space-y-6">
              <span className="font-ibm-plex-mono text-[10px] font-bold text-alkota-orange tracking-[0.3em] uppercase block">
                // AQUEOUS PARTS WASHER CHEMISTRY
              </span>
              <h3 className="text-2xl sm:text-4xl font-extralight uppercase tracking-tight text-white leading-tight">
                ZERO SOLVENTS. <br />
                <span className="text-alkota-orange font-light">60-DAY FLASH RUST PROTECTION.</span>
              </h3>
              <p className="text-xs sm:text-sm text-[#AAA] leading-relaxed font-normal">
                Traditional solvent degreasing tanks pose serious fire hazards, VOC emissions, and operator health risks. Alkota aqueous parts washer chemistry replaces solvent tanks with heated, water-based non-foaming detergency.
              </p>
              <p className="text-xs sm:text-sm text-[#AAA] leading-relaxed font-normal">
                Engineered specifically for Alkota APW automatic rotary parts washers. Cleans soft aluminium cylinder heads and bare cast iron blocks simultaneously without surface oxidation.
              </p>
              <div className="pt-2">
                <Link
                  href="/chemicals/parts-washers"
                  className="inline-flex items-center gap-2 bg-[#1A1A1A] border border-[#333] hover:border-alkota-orange text-white px-6 py-3 text-xs uppercase tracking-widest transition-colors font-normal"
                >
                  <span>Explore Parts Washing Solutions</span>
                  <ArrowRight className="h-3.5 w-3.5 text-alkota-orange" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ─── 07. CHEMISTRY + WATER TREATMENT INTEGRATION ────────────────────── */}
      <section className="py-20 border-b border-[#222] bg-[#0A0A0A]">
        <div className="mx-auto max-w-7xl px-6 sm:px-12">
          <div className="bg-[#141412] border border-[#2A2A2A] p-8 sm:p-12 grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            <div className="lg:col-span-8 space-y-6">
              <div className="flex items-center gap-3">
                <RefreshCw className="h-4 w-4 text-alkota-orange animate-spin-slow" />
                <span className="font-ibm-plex-mono text-[10px] uppercase tracking-widest text-alkota-orange">
                  CLOSED-LOOP ECOSYSTEM
                </span>
              </div>
              <h3 className="text-2xl sm:text-4xl font-extralight uppercase tracking-tight text-white leading-tight">
                CLEAN THE EQUIPMENT. <br />
                <span className="text-alkota-orange font-light">THINK ABOUT THE EFFLUENT.</span>
              </h3>
              <p className="text-xs sm:text-sm text-[#AAA] leading-relaxed font-normal">
                Under UK Environment Agency wash-water discharge guidelines, effluent containing emulsified oils cannot be discharged directly into surface drains or groundwater. Alkota chemicals are engineered with "quick-release" surfactant packages that drop suspended hydrocarbons in coalescing oil-water separators, allowing closed-loop recycling and compliant discharge.
              </p>
              <div className="flex flex-wrap gap-4 pt-2">
                <Link
                  href="/water-treatment"
                  className="inline-flex items-center gap-2 bg-alkota-orange text-white px-6 py-3 text-xs uppercase tracking-widest hover:bg-white hover:text-black transition-colors font-normal"
                >
                  <span>Explore Water Treatment & Recycling</span>
                  <ArrowRight className="h-3.5 w-3.5" />
                </Link>
                <Link
                  href="/lobby"
                  className="inline-flex items-center gap-2 border border-[#333] bg-[#1A1A1A] text-[#CCC] px-5 py-3 text-xs uppercase tracking-widest hover:text-white hover:border-white transition-colors font-normal"
                >
                  <span>EA Wash Pad Guidance in The Lobby</span>
                </Link>
              </div>
            </div>

            <div className="lg:col-span-4 bg-black/40 border border-[#222] p-6 space-y-4">
              <span className="text-[10px] font-ibm-plex-mono uppercase text-[#777] block pb-2 border-b border-[#222]">
                // Recycling System Compatibility
              </span>
              <div className="space-y-2 text-xs font-normal">
                <div className="flex items-center justify-between text-[#CCC]">
                  <span>Oil-Water Separators</span>
                  <span className="text-emerald-400 font-ibm-plex-mono">✓ 100% Quick-Break</span>
                </div>
                <div className="flex items-center justify-between text-[#CCC]">
                  <span>Multi-Media Sand Filters</span>
                  <span className="text-emerald-400 font-ibm-plex-mono">✓ Non-Blinding</span>
                </div>
                <div className="flex items-center justify-between text-[#CCC]">
                  <span>Biological Filtration Beds</span>
                  <span className="text-emerald-400 font-ibm-plex-mono">✓ Low Biocide</span>
                </div>
                <div className="flex items-center justify-between text-[#CCC]">
                  <span>Wastewater Evaporators</span>
                  <span className="text-emerald-400 font-ibm-plex-mono">✓ Low Foaming</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ─── 08. DILUTION / USE CALCULATOR ──────────────────────────────────── */}
      <section className="py-20 border-b border-[#222] bg-[#111111]">
        <div className="mx-auto max-w-7xl px-6 sm:px-12">
          <div className="flex items-center gap-4 mb-6">
            <span className="font-ibm-plex-mono text-[10px] font-bold text-alkota-orange tracking-[0.4em] uppercase">
              CHAPTER 08
            </span>
            <span className="h-px w-12 bg-[#333]" />
            <span className="font-ibm-plex-mono text-[10px] font-bold tracking-[0.3em] uppercase text-[#777]">
              OPERATIONAL DOSING & ESTIMATION
            </span>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
            <div className="lg:col-span-5 space-y-6">
              <h2 className="text-3xl sm:text-5xl font-extralight uppercase tracking-tight text-white leading-tight">
                CHEMICAL USE <br />
                <span className="text-alkota-orange font-light">DOSING CALCULATOR.</span>
              </h2>
              <p className="text-sm text-[#AAA] leading-relaxed font-normal">
                Over-concentrating chemical wastefully increases operating cost and risks surface damage. Under-concentrating fails to break surface tension.
              </p>
              <p className="text-xs text-[#777] leading-relaxed font-normal">
                Calculate the precise chemical concentrate volume and clean water volume required for your wash tank, foam lance bottle, or bulk chemical reservoir.
              </p>

              {/* Safety Compliance Callout */}
              <div className="p-4 bg-[#181818] border-l-2 border-amber-400 space-y-1">
                <span className="text-[10px] font-ibm-plex-mono uppercase tracking-widest text-amber-400 flex items-center gap-1.5">
                  <AlertTriangle className="h-3 w-3" /> Mandatory Safety Notice
                </span>
                <p className="text-[11px] text-[#AAA] leading-relaxed font-normal">
                  Always follow container label and Safety Data Sheet (SDS) instructions. Never allow calculator outputs to supersede legal manufacturer instructions.
                </p>
              </div>
            </div>

            {/* Calculator Card */}
            <div className="lg:col-span-7 bg-[#141414] border border-[#262626] p-6 sm:p-8">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-6">
                <div>
                  <label className="block font-ibm-plex-mono text-[10px] uppercase tracking-widest text-alkota-orange mb-2">
                    Total Solution Volume (Litres)
                  </label>
                  <input
                    type="number"
                    min="1"
                    max="10000"
                    value={calcTankLiters}
                    onChange={(e) => setCalcTankLiters(Math.max(1, Number(e.target.value)))}
                    className="w-full bg-[#1C1C1C] border border-[#333] text-white px-4 py-3 text-sm font-normal focus:outline-none focus:border-alkota-orange"
                  />
                  <div className="flex flex-wrap gap-1.5 mt-2">
                    {COMMON_TANK_PRESETS.map((preset) => (
                      <button
                        key={preset.value}
                        type="button"
                        onClick={() => setCalcTankLiters(preset.value)}
                        className={`text-[9px] font-ibm-plex-mono uppercase px-2 py-1 transition-colors ${
                          calcTankLiters === preset.value
                            ? 'bg-alkota-orange text-white'
                            : 'bg-black/40 text-[#777] hover:text-white border border-[#222]'
                        }`}
                      >
                        {preset.label}
                      </button>
                    ))}
                  </div>
                </div>

                <div>
                  <label className="block font-ibm-plex-mono text-[10px] uppercase tracking-widest text-alkota-orange mb-2">
                    Target Dilution Ratio
                  </label>
                  <select
                    value={calcDilutionPart}
                    onChange={(e) => setCalcDilutionPart(Number(e.target.value))}
                    className="w-full bg-[#1C1C1C] border border-[#333] text-white px-4 py-3 text-xs font-normal focus:outline-none focus:border-alkota-orange"
                  >
                    {COMMON_DILUTION_RATIOS.map((r) => (
                      <option key={r.part} value={r.part}>
                        {r.label}
                      </option>
                    ))}
                  </select>
                  <p className="text-[10px] text-[#777] font-ibm-plex-mono mt-2">
                    Selected Ratio: 1 part chemical to {calcDilutionPart} parts water
                  </p>
                </div>
              </div>

              {/* Dosing Calculation Results */}
              <div className="p-5 bg-black/60 border border-[#262626] grid grid-cols-2 sm:grid-cols-3 gap-4 mb-4">
                <div>
                  <span className="block font-ibm-plex-mono text-[9px] uppercase text-[#666] mb-1">
                    Chemical Concentrate
                  </span>
                  <span className="text-xl font-normal text-alkota-orange font-ibm-plex-mono">
                    {dosingResult.chemicalVolumeMl >= 1000
                      ? `${dosingResult.chemicalVolumeLiters} L`
                      : `${dosingResult.chemicalVolumeMl} ml`}
                  </span>
                </div>
                <div>
                  <span className="block font-ibm-plex-mono text-[9px] uppercase text-[#666] mb-1">
                    Clean Water Volume
                  </span>
                  <span className="text-xl font-normal text-white font-ibm-plex-mono">
                    {dosingResult.waterVolumeLiters} L
                  </span>
                </div>
                <div>
                  <span className="block font-ibm-plex-mono text-[9px] uppercase text-[#666] mb-1">
                    Solution Strength
                  </span>
                  <span className="text-xl font-normal text-cyan-400 font-ibm-plex-mono">
                    {dosingResult.percentageStrength}%
                  </span>
                </div>
              </div>

              <p className="text-xs text-[#AAA] font-normal leading-relaxed">
                <strong>Dosing Instructions:</strong> {dosingResult.dosageAdvice} Always add chemical concentrate to water, never water into concentrated acid/caustic.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ─── 09. SAFETY DATA & COSHH CENTRAL REPOSITORY ─────────────────────── */}
      <section className="py-20 border-b border-[#222] bg-[#0A0A0A]">
        <div className="mx-auto max-w-7xl px-6 sm:px-12">
          <div className="flex items-center gap-4 mb-6">
            <span className="font-ibm-plex-mono text-[10px] font-bold text-alkota-orange tracking-[0.4em] uppercase">
              CHAPTER 09
            </span>
            <span className="h-px w-12 bg-[#333]" />
            <span className="font-ibm-plex-mono text-[10px] font-bold tracking-[0.3em] uppercase text-[#777]">
              GB CLP & COSHH DOCUMENTATION
            </span>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            <div className="lg:col-span-7 space-y-6">
              <h2 className="text-3xl sm:text-5xl font-extralight uppercase tracking-tight text-white leading-tight">
                SAFETY DATA SHEETS. <br />
                <span className="text-alkota-orange font-light">LEGAL ACCURACY IS NON-NEGOTIABLE.</span>
              </h2>
              <p className="text-sm text-[#AAA] leading-relaxed font-normal">
                Under UK chemical supply obligations, every industrial cleaning chemical must be accompanied by a current Safety Data Sheet conforming to GB CLP and UK REACH regulations.
              </p>
              <div className="p-4 bg-[#141414] border-l-2 border-alkota-orange space-y-2">
                <span className="text-[10px] font-ibm-plex-mono uppercase tracking-widest text-alkota-orange block">
                  // COSHH Assessment Guidance
                </span>
                <p className="text-xs text-[#CCC] leading-relaxed font-normal">
                  "The Safety Data Sheet provides information required to support your site-specific COSHH assessment. Alkota provides verified SDS and TDS data for every UK approved formulation."
                </p>
              </div>
              <div className="pt-2 flex flex-wrap gap-4">
                <Link
                  href="/chemicals/safety-data"
                  className="inline-flex items-center gap-2 bg-alkota-orange text-white px-6 py-3 text-xs uppercase tracking-widest hover:bg-white hover:text-black transition-colors font-normal"
                >
                  <FileText className="h-4 w-4" />
                  <span>Access Safety Data Library</span>
                </Link>
                <Link
                  href="/lobby"
                  className="inline-flex items-center gap-2 border border-[#333] bg-[#181818] text-[#CCC] px-5 py-3 text-xs uppercase tracking-widest hover:text-white transition-colors font-normal"
                >
                  <span>COSHH Basics in The Lobby</span>
                </Link>
              </div>
            </div>

            <div className="lg:col-span-5 bg-[#141414] border border-[#262626] p-6 space-y-4">
              <span className="text-[10px] font-ibm-plex-mono uppercase text-[#777] block pb-2 border-b border-[#222]">
                // Quick Document Downloads
              </span>
              <div className="space-y-2.5">
                {VERIFIED_CHEMICAL_PRODUCTS.slice(0, 4).map((p) => (
                  <div key={p.id} className="p-3 bg-black/40 border border-[#222] flex items-center justify-between">
                    <div>
                      <h4 className="text-xs uppercase text-white font-normal leading-none mb-1">
                        {p.name}
                      </h4>
                      <span className="text-[10px] font-ibm-plex-mono text-[#777]">
                        SDS {p.sds_revision_date || 'Current'}
                      </span>
                    </div>
                    <a
                      href={p.sds_url || '#'}
                      className="inline-flex items-center gap-1 text-[10px] uppercase font-ibm-plex-mono text-alkota-orange hover:text-white transition-colors"
                    >
                      <Download className="h-3 w-3" />
                      <span>PDF</span>
                    </a>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ─── 10. COMMERCIAL SUPPLY & DEALER INTEGRATION ─────────────────────── */}
      <section className="py-20 bg-[#0A0A0A]">
        <div className="mx-auto max-w-7xl px-6 sm:px-12">
          <div className="bg-[#141412] border border-[#2A2A2A] p-8 sm:p-14 flex flex-col lg:flex-row lg:items-center justify-between gap-8 relative overflow-hidden">
            <div className="space-y-4 max-w-2xl">
              <span className="text-[10px] font-ibm-plex-mono uppercase tracking-[0.25em] text-alkota-orange block">
                // UK COMMERCIAL SUPPLY & PALLET RATES
              </span>
              <h2 className="text-3xl sm:text-5xl font-extralight uppercase tracking-tight text-white leading-tight">
                SCHEDULED SUPPLY. <br />
                <span className="text-alkota-orange font-light">IBC BULK REFILL & LOCAL DEALERS.</span>
              </h2>
              <p className="text-xs sm:text-sm text-[#AAA] leading-relaxed font-normal">
                Alkota chemicals are supplied nationwide across 25L drums, 200L barrels, and 1000L IBC totes. Connect with your authorised regional Alkota dealer for scheduled replenishment contracts, site trials, and volume pricing.
              </p>
            </div>

            <div className="flex flex-col sm:flex-row gap-4 shrink-0">
              <Link
                href="/contact?subject=Chemical%20Order"
                className="inline-flex items-center justify-center gap-2 bg-alkota-orange text-white px-8 py-4 text-xs uppercase tracking-widest hover:bg-white hover:text-black transition-all font-normal shadow-lg shadow-alkota-orange/20"
              >
                <span>Request Pricing / Supply</span>
                <ArrowRight className="h-4 w-4" />
              </Link>
              <Link
                href="/dealers"
                className="inline-flex items-center justify-center gap-2 border border-[#444] bg-[#1C1C1C] text-white px-6 py-4 text-xs uppercase tracking-widest hover:border-white transition-all font-normal"
              >
                <span>Find Local Dealer</span>
              </Link>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
